
# 17 — Validation Synthesis and Final Interpretation  
## Final Evidence Layer for the 5-Variable POSet Framework

This notebook synthesizes the final empirical evidence from:

- Main profile POSet results;
- epsilon-tolerance and epsilon-margin sensitivity;
- GDP recovery validation;
- multi-indicator shock validation;
- diagnostic Fattore-style POSet scores;
- country drilldowns.

It runs after:

```text
16_Multi_Indicator_Shock_Validation_2002_5Var.ipynb
```

## Purpose

This notebook does not create a new method.  
It assembles final report-ready interpretation tables and paragraphs.

## Core final message

The project should be presented as:

```text
A multidimensional structural POSet framework for comparing OECD countries' economic resilience capacity.
```

Not as:

```text
A single universal Economic Resilience Index.
```

## Main outputs

- `final_validation_synthesis.csv`
- `final_interpretation_takeaways.csv`
- `final_mismatch_case_summary.csv`
- `validation_method_comparison.csv`
- `final_methodological_decisions_updated.csv`
- `final_validation_table_updated.csv`
- `report_ready_final_interpretation_paragraphs.csv`
- `report_ready_validation_paragraphs_updated.csv`
- `17_Validation_Synthesis_and_Final_Interpretation_Audit.xlsx`

In [1]:

# ------------------------------------------------------
# IMPORTS AND PATHS
# ------------------------------------------------------

from pathlib import Path
from datetime import datetime
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 300)
pd.set_option("display.max_rows", 300)
pd.set_option("display.float_format", "{:.4f}".format)

PROJECT_ROOT = Path.cwd()

PROFILE_DIR = PROJECT_ROOT / "Data" / "Processed" / "Profile_POSet_Main"
SENSITIVITY_DIR = PROJECT_ROOT / "Data" / "Processed" / "Sensitivity_Analysis"
RECOVERY_DIR = PROJECT_ROOT / "Data" / "Processed" / "Recovery_Validation"
MULTI_VALIDATION_DIR = PROJECT_ROOT / "Data" / "Processed" / "Multi_Indicator_Shock_Validation"
FATTORE_DIR = PROJECT_ROOT / "Data" / "Processed" / "Fattore_Style_POSet_Scores"
COUNTRY_DRILLDOWN_DIR = PROJECT_ROOT / "Data" / "Processed" / "Country_POSet_Diagnostic_Drilldown"

PROCESSED_DIR = PROJECT_ROOT / "Data" / "Processed" / "Validation_Synthesis_Final_Interpretation"
DIAGNOSTICS_DIR = PROJECT_ROOT / "Data" / "Diagnostics" / "17_Validation_Synthesis_Final_Interpretation"
FIGURES_DIR = PROJECT_ROOT / "Outputs" / "Figures" / "Validation_Synthesis_Final_Interpretation"
TABLES_DIR = PROJECT_ROOT / "Outputs" / "Tables" / "Validation_Synthesis_Final_Interpretation"
AUDIT_DIR = PROJECT_ROOT / "Data" / "Audit"

for folder in [PROCESSED_DIR, DIAGNOSTICS_DIR, FIGURES_DIR, TABLES_DIR, AUDIT_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
RUN_TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

print("Run ID:", RUN_ID)
print("Project root:", PROJECT_ROOT.resolve())
print("Processed folder:", PROCESSED_DIR.resolve())

Run ID: 20260624_221342
Project root: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Run_24
Processed folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Run_24\Data\Processed\Validation_Synthesis_Final_Interpretation

In [2]:

# ------------------------------------------------------
# CONFIGURATION AND INPUT FILES
# ------------------------------------------------------

INPUT_FILES = {
    "profile_quality": PROFILE_DIR / "profile_poset_quality_diagnostics.csv",
    "profile_layer_summary": PROFILE_DIR / "profile_layer_summary.csv",
    "profile_pareto_countries": PROFILE_DIR / "profile_pareto_countries.csv",
    "profile_run_summary": PROFILE_DIR / "profile_run_summary.csv",

    "sensitivity_synthesis": SENSITIVITY_DIR / "sensitivity_synthesis.csv",
    "robustness_dashboard": SENSITIVITY_DIR / "robustness_dashboard_table.csv",
    "report_table_epsilon_margin": SENSITIVITY_DIR / "report_table_epsilon_margin.csv",
    "report_table_profile_sensitivity": SENSITIVITY_DIR / "report_table_profile_sensitivity.csv",
    "report_table_recovery_validation": SENSITIVITY_DIR / "report_table_recovery_validation.csv",

    "recovery_takeaways": RECOVERY_DIR / "recovery_validation_takeaway_table.csv",
    "recovery_mismatch_cases": RECOVERY_DIR / "recovery_interpretation_cases.csv",
    "recovery_report_paragraphs": RECOVERY_DIR / "report_ready_recovery_validation_paragraphs.csv",

    "multi_takeaways": MULTI_VALIDATION_DIR / "multi_indicator_validation_takeaways.csv",
    "multi_evidence_matrix": MULTI_VALIDATION_DIR / "validation_evidence_matrix.csv",
    "multi_frontier_validation": MULTI_VALIDATION_DIR / "frontier_vs_nonfrontier_multi_indicator_validation.csv",
    "multi_mismatch_cases": MULTI_VALIDATION_DIR / "multi_indicator_validation_mismatch_cases.csv",
    "multi_report_paragraphs": MULTI_VALIDATION_DIR / "report_ready_multi_indicator_validation_paragraphs.csv",

    "fattore_summary": FATTORE_DIR / "fattore_score_summary_by_shock.csv",
    "fattore_method_note": FATTORE_DIR / "fattore_scoring_method_note.csv",

    "country_drilldown_brief": COUNTRY_DRILLDOWN_DIR / "target_country_problem_brief.csv",
    "country_recovery_alignment": COUNTRY_DRILLDOWN_DIR / "target_recovery_alignment.csv",
    "country_report_paragraphs": COUNTRY_DRILLDOWN_DIR / "report_ready_country_drilldown_paragraphs.csv",
}

REQUIRED_KEYS = [
    "profile_quality",
    "sensitivity_synthesis",
    "robustness_dashboard",
    "recovery_takeaways",
    "multi_takeaways",
    "multi_evidence_matrix",
    "multi_frontier_validation",
    "multi_mismatch_cases",
]

missing = [key for key in REQUIRED_KEYS if not INPUT_FILES[key].exists()]

if missing:
    raise FileNotFoundError(
        "Missing required synthesis inputs:\n"
        + "\n".join([f"- {key}: {INPUT_FILES[key]}" for key in missing])
    )

MAIN_VARIABLE_SET = "baseline_5_variables"
MAIN_LEVELS = 5
MAIN_VARIABLE_COUNT = 5
POSET_TEMPORAL_DESIGN = "2007 and 2019 single pre-shock cross-sections"

print("Main variable set:", MAIN_VARIABLE_SET)
print("Main levels:", MAIN_LEVELS)
print("Temporal design:", POSET_TEMPORAL_DESIGN)

Main variable set: baseline_5_variables
Main levels: 5
Temporal design: 2007 and 2019 single pre-shock cross-sections

In [3]:

# ------------------------------------------------------
# HELPERS
# ------------------------------------------------------

table_inventory = []
figure_inventory = []

def clean_keys(df):
    out = df.copy()

    if "Country" in out.columns:
        out["Country"] = out["Country"].astype(str).str.strip().str.upper()

    if "shock_id" in out.columns:
        out["shock_id"] = out["shock_id"].astype(str).str.replace(r"\.0$", "", regex=True).str.strip()

    if "baseline_year" in out.columns:
        out["baseline_year"] = pd.to_numeric(out["baseline_year"], errors="coerce").astype("Int64")

    return out


def read_optional_csv(path):
    if path.exists():
        return clean_keys(pd.read_csv(path))
    return pd.DataFrame()


def save_table(df, file_name, title, description):
    processed_path = PROCESSED_DIR / file_name
    diagnostics_path = DIAGNOSTICS_DIR / file_name
    table_path = TABLES_DIR / file_name

    df.to_csv(processed_path, index=False)
    df.to_csv(diagnostics_path, index=False)
    df.to_csv(table_path, index=False)

    table_inventory.append({
        "file_name": file_name,
        "title": title,
        "description": description,
        "rows": len(df),
        "columns": len(df.columns),
        "processed_path": str(processed_path),
        "diagnostics_path": str(diagnostics_path),
        "table_path": str(table_path),
        "created_at": RUN_TIMESTAMP,
    })

    print("Saved table:", file_name)


def save_figure(fig, file_name, title, description):
    path = FIGURES_DIR / file_name
    fig.savefig(path, dpi=220, bbox_inches="tight")
    plt.close(fig)

    figure_inventory.append({
        "file_name": file_name,
        "title": title,
        "description": description,
        "path": str(path),
        "created_at": RUN_TIMESTAMP,
    })

    print("Saved figure:", file_name)


def fmt_number(x, digits=2):
    if pd.isna(x):
        return "not available"
    return f"{x:.{digits}f}"

In [4]:

# ------------------------------------------------------
# LOAD INPUTS
# ------------------------------------------------------

profile_quality = read_optional_csv(INPUT_FILES["profile_quality"])
profile_layer_summary = read_optional_csv(INPUT_FILES["profile_layer_summary"])
profile_pareto_countries = read_optional_csv(INPUT_FILES["profile_pareto_countries"])
profile_run_summary = read_optional_csv(INPUT_FILES["profile_run_summary"])

sensitivity_synthesis = read_optional_csv(INPUT_FILES["sensitivity_synthesis"])
robustness_dashboard = read_optional_csv(INPUT_FILES["robustness_dashboard"])
report_table_epsilon_margin = read_optional_csv(INPUT_FILES["report_table_epsilon_margin"])
report_table_profile_sensitivity = read_optional_csv(INPUT_FILES["report_table_profile_sensitivity"])
report_table_recovery_validation = read_optional_csv(INPUT_FILES["report_table_recovery_validation"])

recovery_takeaways = read_optional_csv(INPUT_FILES["recovery_takeaways"])
recovery_mismatch_cases = read_optional_csv(INPUT_FILES["recovery_mismatch_cases"])
recovery_report_paragraphs = read_optional_csv(INPUT_FILES["recovery_report_paragraphs"])

multi_takeaways = read_optional_csv(INPUT_FILES["multi_takeaways"])
multi_evidence_matrix = read_optional_csv(INPUT_FILES["multi_evidence_matrix"])
multi_frontier_validation = read_optional_csv(INPUT_FILES["multi_frontier_validation"])
multi_mismatch_cases = read_optional_csv(INPUT_FILES["multi_mismatch_cases"])
multi_report_paragraphs = read_optional_csv(INPUT_FILES["multi_report_paragraphs"])

fattore_summary = read_optional_csv(INPUT_FILES["fattore_summary"])
fattore_method_note = read_optional_csv(INPUT_FILES["fattore_method_note"])

country_drilldown_brief = read_optional_csv(INPUT_FILES["country_drilldown_brief"])
country_recovery_alignment = read_optional_csv(INPUT_FILES["country_recovery_alignment"])
country_report_paragraphs = read_optional_csv(INPUT_FILES["country_report_paragraphs"])

print("Loaded tables:")
for name, df in [
    ("profile_quality", profile_quality),
    ("sensitivity_synthesis", sensitivity_synthesis),
    ("recovery_takeaways", recovery_takeaways),
    ("multi_takeaways", multi_takeaways),
    ("multi_evidence_matrix", multi_evidence_matrix),
    ("multi_mismatch_cases", multi_mismatch_cases),
    ("country_drilldown_brief", country_drilldown_brief),
]:
    print(f"{name}: {df.shape}")

display(profile_quality)
display(multi_takeaways)

Loaded tables:
profile_quality: (2, 14)
sensitivity_synthesis: (6, 4)
recovery_takeaways: (2, 8)
multi_takeaways: (2, 8)
multi_evidence_matrix: (12, 7)
multi_mismatch_cases: (63, 11)
country_drilldown_brief: (10, 30)

,shock_id,baseline_year,countries,unique_profiles,profile_uniqueness_ratio,dominance_relations,hasse_edges,layers,frontier_profiles,frontier_countries,comparability_ratio,incomparability_ratio,main_variable_set,levels
0,2007,2007,25,25,1.0000,96,52,5,8,8,0.3200,0.6800,baseline_5_variables,5
1,2019,2019,35,34,0.9714,129,64,4,12,13,0.2299,0.7701,baseline_5_variables,5

,shock_id,available_metrics,frontier_better_metrics,nonfrontier_better_metrics,similar_metrics,frontier_better_share,headline,interpretation_caution
0,2007,6,5,1,0,0.8333,Frontier countries outperform non-frontier cou...,Descriptive validation only; no causal claim.
1,2019,6,5,1,0,0.8333,Frontier countries outperform non-frontier cou...,Descriptive validation only; no causal claim.

In [5]:

# ------------------------------------------------------
# FINAL POSET STRUCTURE SYNTHESIS
# ------------------------------------------------------

structure_rows = []

for _, row in profile_quality.iterrows():
    structure_rows.append({
        "shock_id": row.get("shock_id"),
        "baseline_year": row.get("baseline_year"),
        "countries": row.get("countries"),
        "unique_profiles": row.get("unique_profiles"),
        "frontier_countries": row.get("frontier_countries"),
        "layers": row.get("layers"),
        "dominance_relations": row.get("dominance_relations"),
        "hasse_edges": row.get("hasse_edges"),
        "comparability_ratio": row.get("comparability_ratio"),
        "incomparability_ratio": row.get("incomparability_ratio"),
        "interpretation": (
            "High incomparability supports POSet analysis because many countries cannot be ordered without arbitrary trade-offs."
        ),
    })

final_poset_structure_summary = pd.DataFrame(structure_rows)

save_table(
    final_poset_structure_summary,
    "final_poset_structure_summary.csv",
    "Final POSet structure summary",
    "Main profile POSet structure by shock.",
)

display(final_poset_structure_summary)

Saved table: final_poset_structure_summary.csv

,shock_id,baseline_year,countries,unique_profiles,frontier_countries,layers,dominance_relations,hasse_edges,comparability_ratio,incomparability_ratio,interpretation
0,2007,2007,25,25,8,5,96,52,0.3200,0.6800,High incomparability supports POSet analysis b...
1,2019,2019,35,34,13,4,129,64,0.2299,0.7701,High incomparability supports POSet analysis b...

In [6]:

# ------------------------------------------------------
# VALIDATION METHOD COMPARISON
# ------------------------------------------------------

validation_method_comparison = pd.DataFrame([
    {
        "validation_layer": "GDP recovery validation",
        "input_output": "Recovery_2007 and Recovery_2019",
        "purpose": "Checks whether structurally stronger profiles recover faster in GDP terms.",
        "ordering_role": "Not used in ordering",
        "evidence_type": "descriptive outcome validation",
        "main_caveat": "GDP recovery does not capture all dimensions of resilience.",
    },
    {
        "validation_layer": "Multi-indicator macro validation",
        "input_output": "GDP growth, unemployment, inflation, debt, productivity",
        "purpose": "Checks whether frontier profiles outperform non-frontier profiles across broader post-shock outcomes.",
        "ordering_role": "Not used in ordering",
        "evidence_type": "descriptive multi-outcome validation",
        "main_caveat": "Indicators differ in coverage and reflect both structural capacity and policy response.",
    },
    {
        "validation_layer": "Epsilon-tolerance sensitivity",
        "input_output": "Country-level tolerance dominance relation",
        "purpose": "Tests whether dominance structure changes when small score differences are tolerated.",
        "ordering_role": "Diagnostic only",
        "evidence_type": "validity/sensitivity diagnostic",
        "main_caveat": "Higher tolerance values can create cycles or reciprocal dominance.",
    },
    {
        "validation_layer": "Epsilon-margin robustness",
        "input_output": "Country-level required-margin dominance relation",
        "purpose": "Tests dominance under a stricter minimum-advantage rule.",
        "ordering_role": "Robustness only",
        "evidence_type": "robustness diagnostic",
        "main_caveat": "Does not replace the main profile-level POSet.",
    },
    {
        "validation_layer": "Fattore-style POSet scores",
        "input_output": "Dominance, incomparability, embedded/separation scores",
        "purpose": "Quantifies profile position for interpretation.",
        "ordering_role": "Diagnostic only",
        "evidence_type": "POSet interpretability diagnostic",
        "main_caveat": "Numeric scores are not a final Economic Resilience Index.",
    },
])

save_table(
    validation_method_comparison,
    "validation_method_comparison.csv",
    "Validation method comparison",
    "Compares all validation and robustness layers used in the final interpretation.",
)

display(validation_method_comparison)

Saved table: validation_method_comparison.csv

,validation_layer,input_output,purpose,ordering_role,evidence_type,main_caveat
0,GDP recovery validation,Recovery_2007 and Recovery_2019,Checks whether structurally stronger profiles ...,Not used in ordering,descriptive outcome validation,GDP recovery does not capture all dimensions o...
1,Multi-indicator macro validation,"GDP growth, unemployment, inflation, debt, pro...",Checks whether frontier profiles outperform no...,Not used in ordering,descriptive multi-outcome validation,Indicators differ in coverage and reflect both...
2,Epsilon-tolerance sensitivity,Country-level tolerance dominance relation,Tests whether dominance structure changes when...,Diagnostic only,validity/sensitivity diagnostic,Higher tolerance values can create cycles or r...
3,Epsilon-margin robustness,Country-level required-margin dominance relation,Tests dominance under a stricter minimum-advan...,Robustness only,robustness diagnostic,Does not replace the main profile-level POSet.
4,Fattore-style POSet scores,"Dominance, incomparability, embedded/separatio...",Quantifies profile position for interpretation.,Diagnostic only,POSet interpretability diagnostic,Numeric scores are not a final Economic Resili...

In [7]:

# ------------------------------------------------------
# FINAL VALIDATION SYNTHESIS
# ------------------------------------------------------

validation_rows = []

# GDP recovery validation
for _, row in recovery_takeaways.iterrows():
    validation_rows.append({
        "shock_id": row.get("shock_id"),
        "evidence_layer": "GDP recovery validation",
        "evidence_summary": row.get("headline_takeaway"),
        "support_metric_1": "frontier_mean_minus_nonfrontier_mean_recovery",
        "support_value_1": row.get("frontier_mean_minus_nonfrontier_mean_recovery"),
        "support_metric_2": "layer_recovery_spearman_correlation",
        "support_value_2": row.get("layer_recovery_spearman_correlation"),
        "supports_main_structure": (
            "yes" if pd.to_numeric(row.get("frontier_mean_minus_nonfrontier_mean_recovery"), errors="coerce") < 0 else "mixed"
        ),
        "interpretation_caution": row.get("caution", "Descriptive validation only."),
    })

# Multi-indicator validation
for _, row in multi_takeaways.iterrows():
    validation_rows.append({
        "shock_id": row.get("shock_id"),
        "evidence_layer": "Multi-indicator macro validation",
        "evidence_summary": row.get("headline"),
        "support_metric_1": "frontier_better_metrics",
        "support_value_1": row.get("frontier_better_metrics"),
        "support_metric_2": "frontier_better_share",
        "support_value_2": row.get("frontier_better_share"),
        "supports_main_structure": (
            "yes" if pd.to_numeric(row.get("frontier_better_share"), errors="coerce") >= 0.5 else "mixed"
        ),
        "interpretation_caution": row.get("interpretation_caution", "Descriptive validation only."),
    })

# Epsilon margin
if len(report_table_epsilon_margin):
    for shock_id, group in report_table_epsilon_margin.groupby("shock_id"):
        valid_count = int(pd.Series(group["is_valid_partial_order"]).astype(bool).sum())
        total_count = len(group)

        validation_rows.append({
            "shock_id": shock_id,
            "evidence_layer": "Epsilon-margin robustness",
            "evidence_summary": f"{valid_count}/{total_count} tested epsilon-margin values remain valid partial orders.",
            "support_metric_1": "valid_epsilon_margin_values",
            "support_value_1": valid_count,
            "support_metric_2": "tested_epsilon_margin_values",
            "support_value_2": total_count,
            "supports_main_structure": "yes" if valid_count == total_count else "mixed",
            "interpretation_caution": "Robustness only; main result remains the profile-level POSet.",
        })

final_validation_synthesis = pd.DataFrame(validation_rows)

save_table(
    final_validation_synthesis,
    "final_validation_synthesis.csv",
    "Final validation synthesis",
    "Shock-level synthesis across GDP recovery, multi-indicator validation, and epsilon-margin robustness.",
)

display(final_validation_synthesis)

Saved table: final_validation_synthesis.csv

,shock_id,evidence_layer,evidence_summary,support_metric_1,support_value_1,support_metric_2,support_value_2,supports_main_structure,interpretation_caution
0,2007,GDP recovery validation,Frontier countries recovered faster on average.,frontier_mean_minus_nonfrontier_mean_recovery,-0.8235,layer_recovery_spearman_correlation,0.0698,yes,Validation is descriptive and does not establi...
1,2019,GDP recovery validation,Frontier countries recovered faster on average.,frontier_mean_minus_nonfrontier_mean_recovery,-0.2632,layer_recovery_spearman_correlation,0.3095,yes,Validation is descriptive and does not establi...
2,2007,Multi-indicator macro validation,Frontier countries outperform non-frontier cou...,frontier_better_metrics,5.0000,frontier_better_share,0.8333,yes,Descriptive validation only; no causal claim.
3,2019,Multi-indicator macro validation,Frontier countries outperform non-frontier cou...,frontier_better_metrics,5.0000,frontier_better_share,0.8333,yes,Descriptive validation only; no causal claim.
4,2007,Epsilon-margin robustness,5/5 tested epsilon-margin values remain valid ...,valid_epsilon_margin_values,5.0000,tested_epsilon_margin_values,5.0000,yes,Robustness only; main result remains the profi...
5,2019,Epsilon-margin robustness,5/5 tested epsilon-margin values remain valid ...,valid_epsilon_margin_values,5.0000,tested_epsilon_margin_values,5.0000,yes,Robustness only; main result remains the profi...

In [8]:

# ------------------------------------------------------
# FINAL MISMATCH CASE SUMMARY
# ------------------------------------------------------

mismatch_summary_rows = []

if len(recovery_mismatch_cases):
    for shock_id, group in recovery_mismatch_cases.groupby("shock_id"):
        mismatch_summary_rows.append({
            "shock_id": shock_id,
            "mismatch_source": "GDP recovery validation",
            "mismatch_cases": len(group),
            "case_type_summary": ", ".join(sorted(group["case_type"].dropna().astype(str).unique())),
            "interpretation": "GDP recovery mismatches identify cases where structural POSet position and recovery time diverge.",
        })

if len(multi_mismatch_cases):
    for shock_id, group in multi_mismatch_cases.groupby("shock_id"):
        mismatch_summary_rows.append({
            "shock_id": shock_id,
            "mismatch_source": "Multi-indicator validation",
            "mismatch_cases": len(group),
            "case_type_summary": ", ".join(sorted(group["case_type"].dropna().astype(str).unique())),
            "interpretation": "Multi-indicator mismatches show metric-specific divergences; these are expected in a multidimensional framework.",
        })

final_mismatch_case_summary = pd.DataFrame(mismatch_summary_rows)

if final_mismatch_case_summary.empty:
    final_mismatch_case_summary = pd.DataFrame(columns=[
        "shock_id", "mismatch_source", "mismatch_cases", "case_type_summary", "interpretation",
    ])

save_table(
    final_mismatch_case_summary,
    "final_mismatch_case_summary.csv",
    "Final mismatch case summary",
    "Aggregated mismatch case counts and interpretation by validation layer.",
)

display(final_mismatch_case_summary)

Saved table: final_mismatch_case_summary.csv

,shock_id,mismatch_source,mismatch_cases,case_type_summary,interpretation
0,2007,GDP recovery validation,4,frontier_but_slow_recovery,GDP recovery mismatches identify cases where s...
1,2019,GDP recovery validation,2,frontier_but_slow_recovery,GDP recovery mismatches identify cases where s...
2,2007,Multi-indicator validation,22,"deep_layer_but_stronger_validation_outcome, fr...",Multi-indicator mismatches show metric-specifi...
3,2019,Multi-indicator validation,41,"deep_layer_but_stronger_validation_outcome, fr...",Multi-indicator mismatches show metric-specifi...

In [9]:

# ------------------------------------------------------
# FINAL INTERPRETATION TAKEAWAYS
# ------------------------------------------------------

takeaway_rows = []

# Main structural takeaways.
for _, row in final_poset_structure_summary.iterrows():
    takeaway_rows.append({
        "takeaway_area": "Main POSet structure",
        "shock_id": row.get("shock_id"),
        "takeaway": (
            f"The {row.get('shock_id')} POSet contains {int(row.get('countries'))} countries, "
            f"{int(row.get('unique_profiles'))} unique profiles, and an incomparability ratio of "
            f"{fmt_number(row.get('incomparability_ratio'))}."
        ),
        "report_section": "Results",
        "claim_strength": "strong_descriptive",
    })

# Validation takeaways.
for _, row in multi_takeaways.iterrows():
    takeaway_rows.append({
        "takeaway_area": "Multi-indicator validation",
        "shock_id": row.get("shock_id"),
        "takeaway": (
            f"Frontier countries outperform non-frontier countries on "
            f"{int(row.get('frontier_better_metrics'))}/{int(row.get('available_metrics'))} available macro validation metrics."
        ),
        "report_section": "Validation",
        "claim_strength": "descriptive_validation",
    })

for _, row in recovery_takeaways.iterrows():
    diff = row.get("frontier_mean_minus_nonfrontier_mean_recovery")
    takeaway_rows.append({
        "takeaway_area": "GDP recovery validation",
        "shock_id": row.get("shock_id"),
        "takeaway": (
            f"Frontier countries recover faster on average by approximately {abs(float(diff)):.2f} years "
            f"relative to non-frontier countries."
            if pd.notna(diff) and diff < 0
            else "GDP recovery evidence is mixed or unavailable."
        ),
        "report_section": "Validation",
        "claim_strength": "descriptive_validation",
    })

# Methodological takeaways.
takeaway_rows.extend([
    {
        "takeaway_area": "Methodological guardrail",
        "shock_id": "all",
        "takeaway": "The project should not be presented as a single universal Economic Resilience Index.",
        "report_section": "Methodology / conclusion",
        "claim_strength": "methodological_decision",
    },
    {
        "takeaway_area": "Temporal design",
        "shock_id": "all",
        "takeaway": "The POSet uses two shock-specific pre-shock cross-sections rather than a 22-year average profile.",
        "report_section": "Methodology",
        "claim_strength": "methodological_decision",
    },
    {
        "takeaway_area": "Validation interpretation",
        "shock_id": "all",
        "takeaway": "Validation results are descriptive and should not be interpreted as causal evidence.",
        "report_section": "Limitations / discussion",
        "claim_strength": "interpretation_caution",
    },
])

final_interpretation_takeaways = pd.DataFrame(takeaway_rows)

save_table(
    final_interpretation_takeaways,
    "final_interpretation_takeaways.csv",
    "Final interpretation takeaways",
    "Report-ready final takeaways with section placement and claim strength.",
)

display(final_interpretation_takeaways)

Saved table: final_interpretation_takeaways.csv

,takeaway_area,shock_id,takeaway,report_section,claim_strength
0,Main POSet structure,2007,"The 2007 POSet contains 25 countries, 25 uniqu...",Results,strong_descriptive
1,Main POSet structure,2019,"The 2019 POSet contains 35 countries, 34 uniqu...",Results,strong_descriptive
2,Multi-indicator validation,2007,Frontier countries outperform non-frontier cou...,Validation,descriptive_validation
3,Multi-indicator validation,2019,Frontier countries outperform non-frontier cou...,Validation,descriptive_validation
4,GDP recovery validation,2007,Frontier countries recover faster on average b...,Validation,descriptive_validation
5,GDP recovery validation,2019,Frontier countries recover faster on average b...,Validation,descriptive_validation
6,Methodological guardrail,all,The project should not be presented as a singl...,Methodology / conclusion,methodological_decision
7,Temporal design,all,The POSet uses two shock-specific pre-shock cr...,Methodology,methodological_decision
8,Validation interpretation,all,Validation results are descriptive and should ...,Limitations / discussion,interpretation_caution

In [10]:

# ------------------------------------------------------
# FINAL TABLES FOR REPORT
# ------------------------------------------------------

# Compact table combining POSet + validation.
final_validation_table_rows = []

for shock_id in sorted(final_poset_structure_summary["shock_id"].dropna().astype(str).unique()):
    poset_row = final_poset_structure_summary[
        final_poset_structure_summary["shock_id"].astype(str).eq(shock_id)
    ].iloc[0]

    recovery_row = recovery_takeaways[
        recovery_takeaways["shock_id"].astype(str).eq(shock_id)
    ]

    multi_row = multi_takeaways[
        multi_takeaways["shock_id"].astype(str).eq(shock_id)
    ]

    final_validation_table_rows.append({
        "shock_id": shock_id,
        "countries": poset_row.get("countries"),
        "unique_profiles": poset_row.get("unique_profiles"),
        "frontier_countries": poset_row.get("frontier_countries"),
        "layers": poset_row.get("layers"),
        "incomparability_ratio": poset_row.get("incomparability_ratio"),
        "gdp_recovery_frontier_advantage_years": (
            -float(recovery_row["frontier_mean_minus_nonfrontier_mean_recovery"].iloc[0])
            if len(recovery_row) and pd.notna(recovery_row["frontier_mean_minus_nonfrontier_mean_recovery"].iloc[0])
            else np.nan
        ),
        "multi_indicator_frontier_better_metrics": (
            int(multi_row["frontier_better_metrics"].iloc[0]) if len(multi_row) else np.nan
        ),
        "multi_indicator_available_metrics": (
            int(multi_row["available_metrics"].iloc[0]) if len(multi_row) else np.nan
        ),
        "frontier_better_share": (
            multi_row["frontier_better_share"].iloc[0] if len(multi_row) else np.nan
        ),
        "interpretation": "Frontier countries show generally stronger post-shock validation outcomes, with some mismatch cases.",
    })

final_validation_table_updated = pd.DataFrame(final_validation_table_rows)

final_methodological_decisions_updated = pd.DataFrame([
    {
        "decision": "Use five final ordering variables",
        "final_choice": "debt capacity, employment strength, R&D intensity, tertiary human capital, energy security",
        "reason": "Balances coverage, conceptual breadth, and redundancy control.",
        "report_location": "Data / Methodology",
    },
    {
        "decision": "Use five ordinal levels",
        "final_choice": "5-level profile construction",
        "reason": "Preserves profile differentiation while remaining interpretable.",
        "report_location": "Methodology / Sensitivity",
    },
    {
        "decision": "Use two single pre-shock cross-sections",
        "final_choice": "2007 and 2019",
        "reason": "Keeps ordering variables temporally prior to shock outcomes and avoids averaging across structurally different periods.",
        "report_location": "Methodology",
    },
    {
        "decision": "Keep recovery and macro indicators as validation only",
        "final_choice": "post-shock validation outcomes",
        "reason": "Avoids outcome leakage into POSet construction.",
        "report_location": "Validation / Limitations",
    },
    {
        "decision": "Do not create a final scalar index",
        "final_choice": "POSet framework with frontier/layer/incomparability interpretation",
        "reason": "Avoids arbitrary compensation/trade-offs across dimensions.",
        "report_location": "Introduction / Conclusion",
    },
    {
        "decision": "Use Fattore-style scores diagnostically",
        "final_choice": "dominance, incomparability, separation-style scores",
        "reason": "Adds interpretability without replacing POSet structure.",
        "report_location": "Results / Appendix",
    },
])

save_table(
    final_validation_table_updated,
    "final_validation_table_updated.csv",
    "Final validation table updated",
    "Compact report table combining POSet structure and validation evidence.",
)

save_table(
    final_methodological_decisions_updated,
    "final_methodological_decisions_updated.csv",
    "Final methodological decisions updated",
    "Final decision-log table for report methodology.",
)

display(final_validation_table_updated)
display(final_methodological_decisions_updated)

Saved table: final_validation_table_updated.csv
Saved table: final_methodological_decisions_updated.csv

,shock_id,countries,unique_profiles,frontier_countries,layers,incomparability_ratio,gdp_recovery_frontier_advantage_years,multi_indicator_frontier_better_metrics,multi_indicator_available_metrics,frontier_better_share,interpretation
0,2007,25,25,8,5,0.6800,0.8235,5,6,0.8333,Frontier countries show generally stronger pos...
1,2019,35,34,13,4,0.7701,0.2632,5,6,0.8333,Frontier countries show generally stronger pos...

,decision,final_choice,reason,report_location
0,Use five final ordering variables,"debt capacity, employment strength, R&D intens...","Balances coverage, conceptual breadth, and red...",Data / Methodology
1,Use five ordinal levels,5-level profile construction,Preserves profile differentiation while remain...,Methodology / Sensitivity
2,Use two single pre-shock cross-sections,2007 and 2019,Keeps ordering variables temporally prior to s...,Methodology
3,Keep recovery and macro indicators as validati...,post-shock validation outcomes,Avoids outcome leakage into POSet construction.,Validation / Limitations
4,Do not create a final scalar index,POSet framework with frontier/layer/incomparab...,Avoids arbitrary compensation/trade-offs acros...,Introduction / Conclusion
5,Use Fattore-style scores diagnostically,"dominance, incomparability, separation-style s...",Adds interpretability without replacing POSet ...,Results / Appendix

In [11]:

# ------------------------------------------------------
# REPORT-READY FINAL INTERPRETATION PARAGRAPHS
# ------------------------------------------------------

paragraph_rows = []

paragraph_rows.append({
    "section": "Final interpretation",
    "paragraph_id": "final_interpretation_main_result",
    "report_text": (
        "The final analysis should be interpreted as a multidimensional structural comparison of economic resilience "
        "capacity across OECD countries. The POSet framework identifies undominated frontier profiles, deeper structural "
        "layers, and extensive incomparability between countries. This is preferable to forcing a single scalar ranking, "
        "because many countries combine strengths and weaknesses across different resilience dimensions."
    ),
})

for _, row in final_validation_table_updated.iterrows():
    paragraph_rows.append({
        "section": "Final interpretation",
        "paragraph_id": f"shock_{row['shock_id']}_summary",
        "report_text": (
            f"For the {row['shock_id']} shock, the main POSet includes {int(row['countries'])} countries and "
            f"{int(row['unique_profiles'])} observed profiles. The frontier contains {int(row['frontier_countries'])} "
            f"countries, while the incomparability ratio is {fmt_number(row['incomparability_ratio'])}. "
            f"Frontier countries recover faster in GDP terms by about {fmt_number(row['gdp_recovery_frontier_advantage_years'])} "
            f"years on average and outperform non-frontier countries on "
            f"{int(row['multi_indicator_frontier_better_metrics'])}/{int(row['multi_indicator_available_metrics'])} "
            f"available macro validation indicators."
        ),
    })

paragraph_rows.extend([
    {
        "section": "Validation",
        "paragraph_id": "validation_caution",
        "report_text": (
            "The validation evidence supports the interpretability of the structural framework, but it is not causal. "
            "Post-shock outcomes depend not only on pre-shock structural capacity, but also on shock exposure, policy response, "
            "sectoral composition, global conditions, and measurement choices."
        ),
    },
    {
        "section": "Sensitivity",
        "paragraph_id": "epsilon_and_sensitivity",
        "report_text": (
            "Sensitivity checks show that the main profile POSet is robustly interpretable. Epsilon-tolerance is useful as a "
            "diagnostic but can violate partial-order validity at higher thresholds. Epsilon-margin is a cleaner robustness "
            "check because it preserves componentwise dominance while requiring a minimum advantage."
        ),
    },
    {
        "section": "Conclusion",
        "paragraph_id": "no_scalar_index_conclusion",
        "report_text": (
            "The final output is therefore not a universal Economic Resilience Index. It is a structural POSet framework that "
            "shows which countries are undominated, which countries are comparable or incomparable, and how these structural "
            "positions relate descriptively to later macroeconomic outcomes."
        ),
    },
])

report_ready_final_interpretation_paragraphs = pd.DataFrame(paragraph_rows)

# Backward-compatible naming for report validation paragraphs.
validation_paragraph_rows = []
if len(recovery_report_paragraphs):
    temp = recovery_report_paragraphs.copy()
    temp["source"] = "GDP recovery validation"
    validation_paragraph_rows.append(temp)

if len(multi_report_paragraphs):
    temp = multi_report_paragraphs.copy()
    temp["source"] = "Multi-indicator validation"
    validation_paragraph_rows.append(temp)

if validation_paragraph_rows:
    report_ready_validation_paragraphs_updated = pd.concat(validation_paragraph_rows, ignore_index=True)
else:
    report_ready_validation_paragraphs_updated = pd.DataFrame(columns=["topic", "report_text", "source"])

save_table(
    report_ready_final_interpretation_paragraphs,
    "report_ready_final_interpretation_paragraphs.csv",
    "Report-ready final interpretation paragraphs",
    "Report-ready final interpretation text for results, validation, sensitivity, and conclusion.",
)

save_table(
    report_ready_validation_paragraphs_updated,
    "report_ready_validation_paragraphs_updated.csv",
    "Report-ready validation paragraphs updated",
    "Combined GDP and multi-indicator validation paragraphs for report writing.",
)

display(report_ready_final_interpretation_paragraphs)
display(report_ready_validation_paragraphs_updated)

Saved table: report_ready_final_interpretation_paragraphs.csv
Saved table: report_ready_validation_paragraphs_updated.csv

,section,paragraph_id,report_text
0,Final interpretation,final_interpretation_main_result,The final analysis should be interpreted as a ...
1,Final interpretation,shock_2007_summary,"For the 2007 shock, the main POSet includes 25..."
2,Final interpretation,shock_2019_summary,"For the 2019 shock, the main POSet includes 35..."
3,Validation,validation_caution,The validation evidence supports the interpret...
4,Sensitivity,epsilon_and_sensitivity,Sensitivity checks show that the main profile ...
5,Conclusion,no_scalar_index_conclusion,The final output is therefore not a universal ...

,topic,report_text,source
0,Recovery validation summary 2007,"For the 2007 shock, the recovery validation co...",GDP recovery validation
1,Recovery validation summary 2019,"For the 2019 shock, the recovery validation co...",GDP recovery validation
2,Recovery validation role,GDP recovery is used only after the POSet has ...,GDP recovery validation
3,Validation interpretation,The validation step asks whether structurally ...,GDP recovery validation
4,No causal claim,The analysis should be interpreted as structur...,GDP recovery validation
5,Multi-indicator validation 2007,"For the 2007 shock, multi-indicator validation...",Multi-indicator validation
6,Multi-indicator validation 2019,"For the 2019 shock, multi-indicator validation...",Multi-indicator validation
7,Validation design,The multi-indicator validation step evaluates ...,Multi-indicator validation
8,Validation variables,"The validation indicators include GDP growth, ...",Multi-indicator validation
9,Interpretation of mismatch cases,Mismatch cases are expected in a multidimensio...,Multi-indicator validation

In [12]:

# ------------------------------------------------------
# FINAL SYNTHESIS FIGURES
# ------------------------------------------------------

# Figure 1: frontier better share by shock.
if len(multi_takeaways):
    fig, ax = plt.subplots(figsize=(8, 5))
    plot_df = multi_takeaways.sort_values("shock_id").copy()

    ax.bar(plot_df["shock_id"].astype(str), plot_df["frontier_better_share"])
    ax.set_ylim(0, 1.05)
    ax.set_title("Validation evidence: share of metrics favouring frontier countries")
    ax.set_xlabel("Shock")
    ax.set_ylabel("Frontier-better share")
    ax.grid(True, axis="y", alpha=0.25)

    save_figure(
        fig,
        "17_validation_frontier_better_share.png",
        "Validation frontier-better share",
        "Share of available macro validation metrics where frontier countries outperform non-frontier countries.",
    )

# Figure 2: final structure + validation dashboard.
dashboard_plot = final_validation_table_updated.copy()

if len(dashboard_plot):
    fig, ax = plt.subplots(figsize=(9, 5))

    x = np.arange(len(dashboard_plot))
    width = 0.35

    ax.bar(
        x - width/2,
        dashboard_plot["incomparability_ratio"],
        width=width,
        label="Incomparability ratio",
    )

    ax.bar(
        x + width/2,
        dashboard_plot["frontier_better_share"],
        width=width,
        label="Frontier-better validation share",
    )

    ax.set_xticks(x)
    ax.set_xticklabels(dashboard_plot["shock_id"].astype(str))
    ax.set_ylim(0, 1.05)
    ax.set_title("POSet structure and validation evidence")
    ax.set_xlabel("Shock")
    ax.set_ylabel("Ratio / share")
    ax.legend()
    ax.grid(True, axis="y", alpha=0.25)

    save_figure(
        fig,
        "17_poset_structure_validation_dashboard.png",
        "POSet structure validation dashboard",
        "Compares incomparability ratio with frontier-better validation share by shock.",
    )

# Figure 3: evidence matrix.
if len(multi_evidence_matrix):
    evidence_counts = (
        multi_evidence_matrix
        .groupby(["shock_id", "evidence_label"])
        .size()
        .reset_index(name="count")
    )

    pivot = evidence_counts.pivot(index="shock_id", columns="evidence_label", values="count").fillna(0)

    fig, ax = plt.subplots(figsize=(9, 5))
    bottom = np.zeros(len(pivot))

    for col in pivot.columns:
        ax.bar(pivot.index.astype(str), pivot[col], bottom=bottom, label=col)
        bottom += pivot[col].values

    ax.set_title("Validation evidence matrix summary")
    ax.set_xlabel("Shock")
    ax.set_ylabel("Metric count")
    ax.legend(fontsize=8)
    ax.grid(True, axis="y", alpha=0.25)

    save_figure(
        fig,
        "17_validation_evidence_matrix_summary.png",
        "Validation evidence matrix summary",
        "Counts of validation metrics supporting or contradicting the structural frontier.",
    )

Saved figure: 17_validation_frontier_better_share.png
Saved figure: 17_poset_structure_validation_dashboard.png
Saved figure: 17_validation_evidence_matrix_summary.png

In [13]:

# ------------------------------------------------------
# INVENTORIES AND AUDIT WORKBOOK
# ------------------------------------------------------

table_inventory_df = pd.DataFrame(table_inventory)
figure_inventory_df = pd.DataFrame(figure_inventory)

for table, file_name in [
    (table_inventory_df, "validation_synthesis_table_inventory.csv"),
    (figure_inventory_df, "validation_synthesis_figure_inventory.csv"),
]:
    table.to_csv(PROCESSED_DIR / file_name, index=False)
    table.to_csv(DIAGNOSTICS_DIR / file_name, index=False)
    table.to_csv(TABLES_DIR / file_name, index=False)

run_summary = pd.DataFrame([{
    "run_id": RUN_ID,
    "created_at": RUN_TIMESTAMP,
    "main_variable_set": MAIN_VARIABLE_SET,
    "main_levels": MAIN_LEVELS,
    "main_variable_count": MAIN_VARIABLE_COUNT,
    "poset_temporal_design": POSET_TEMPORAL_DESIGN,
    "validation_rows": len(final_validation_synthesis),
    "final_takeaways": len(final_interpretation_takeaways),
    "tables_created": len(table_inventory_df),
    "figures_created": len(figure_inventory_df),
    "note": "Final synthesis is interpretive/descriptive and does not create a scalar index.",
}])

run_summary.to_csv(PROCESSED_DIR / "validation_synthesis_run_summary.csv", index=False)
run_summary.to_csv(DIAGNOSTICS_DIR / "validation_synthesis_run_summary.csv", index=False)
run_summary.to_csv(TABLES_DIR / "validation_synthesis_run_summary.csv", index=False)

audit_xlsx = AUDIT_DIR / "17_Validation_Synthesis_and_Final_Interpretation_Audit.xlsx"

with pd.ExcelWriter(audit_xlsx, engine="xlsxwriter") as writer:
    run_summary.to_excel(writer, sheet_name="run_summary", index=False)
    final_poset_structure_summary.to_excel(writer, sheet_name="poset_structure", index=False)
    validation_method_comparison.to_excel(writer, sheet_name="method_comparison", index=False)
    final_validation_synthesis.to_excel(writer, sheet_name="validation_synthesis", index=False)
    final_mismatch_case_summary.to_excel(writer, sheet_name="mismatch_summary", index=False)
    final_interpretation_takeaways.to_excel(writer, sheet_name="takeaways", index=False)
    final_validation_table_updated.to_excel(writer, sheet_name="final_validation_table", index=False)
    final_methodological_decisions_updated.to_excel(writer, sheet_name="method_decisions", index=False)
    report_ready_final_interpretation_paragraphs.to_excel(writer, sheet_name="final_paragraphs", index=False)
    report_ready_validation_paragraphs_updated.to_excel(writer, sheet_name="validation_paragraphs", index=False)
    table_inventory_df.to_excel(writer, sheet_name="table_inventory", index=False)
    figure_inventory_df.to_excel(writer, sheet_name="figure_inventory", index=False)

print("Audit workbook:", audit_xlsx.resolve())
display(run_summary)
display(table_inventory_df)
display(figure_inventory_df)

Audit workbook: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Run_24\Data\Audit\17_Validation_Synthesis_and_Final_Interpretation_Audit.xlsx

,run_id,created_at,main_variable_set,main_levels,main_variable_count,poset_temporal_design,validation_rows,final_takeaways,tables_created,figures_created,note
0,20260624_221342,2026-06-24 22:13:42,baseline_5_variables,5,5,2007 and 2019 single pre-shock cross-sections,6,9,9,3,Final synthesis is interpretive/descriptive an...

,file_name,title,description,rows,columns,processed_path,diagnostics_path,table_path,created_at
0,final_poset_structure_summary.csv,Final POSet structure summary,Main profile POSet structure by shock.,2,11,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
1,validation_method_comparison.csv,Validation method comparison,Compares all validation and robustness layers ...,5,6,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
2,final_validation_synthesis.csv,Final validation synthesis,"Shock-level synthesis across GDP recovery, mul...",6,9,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
3,final_mismatch_case_summary.csv,Final mismatch case summary,Aggregated mismatch case counts and interpreta...,4,5,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
4,final_interpretation_takeaways.csv,Final interpretation takeaways,Report-ready final takeaways with section plac...,9,5,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
5,final_validation_table_updated.csv,Final validation table updated,Compact report table combining POSet structure...,2,11,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
6,final_methodological_decisions_updated.csv,Final methodological decisions updated,Final decision-log table for report methodology.,6,4,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
7,report_ready_final_interpretation_paragraphs.csv,Report-ready final interpretation paragraphs,Report-ready final interpretation text for res...,6,3,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
8,report_ready_validation_paragraphs_updated.csv,Report-ready validation paragraphs updated,Combined GDP and multi-indicator validation pa...,10,3,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42

,file_name,title,description,path,created_at
0,17_validation_frontier_better_share.png,Validation frontier-better share,Share of available macro validation metrics wh...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
1,17_poset_structure_validation_dashboard.png,POSet structure validation dashboard,Compares incomparability ratio with frontier-b...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42
2,17_validation_evidence_matrix_summary.png,Validation evidence matrix summary,Counts of validation metrics supporting or con...,D:\Milano Bicocca\Course Materials\1st Year\02...,2026-06-24 22:13:42

In [14]:

# ------------------------------------------------------
# FINAL COMPLETION CHECK
# ------------------------------------------------------

expected_outputs = [
    "final_poset_structure_summary.csv",
    "validation_method_comparison.csv",
    "final_validation_synthesis.csv",
    "final_mismatch_case_summary.csv",
    "final_interpretation_takeaways.csv",
    "final_validation_table_updated.csv",
    "final_methodological_decisions_updated.csv",
    "report_ready_final_interpretation_paragraphs.csv",
    "report_ready_validation_paragraphs_updated.csv",
    "validation_synthesis_run_summary.csv",
]

output_check = pd.DataFrame([
    {
        "file_name": f,
        "processed_exists": (PROCESSED_DIR / f).exists(),
        "diagnostics_exists": (DIAGNOSTICS_DIR / f).exists(),
        "tables_exists": (TABLES_DIR / f).exists(),
    }
    for f in expected_outputs
])

output_check.to_csv(DIAGNOSTICS_DIR / "output_check.csv", index=False)

print("17 VALIDATION SYNTHESIS AND FINAL INTERPRETATION COMPLETE")
print("=" * 90)

display(output_check)

print("\nImportant final framing:")
print("1. Main output = multidimensional structural POSet framework.")
print("2. Not a universal scalar Economic Resilience Index.")
print("3. Validation evidence is descriptive, not causal.")
print("4. Incomparability is a key result, not a weakness.")

print("\nKey outputs to inspect/send:")
print("- 17_Validation_Synthesis_and_Final_Interpretation_Audit.xlsx")
print("- final_validation_synthesis.csv")
print("- final_interpretation_takeaways.csv")
print("- final_validation_table_updated.csv")
print("- report_ready_final_interpretation_paragraphs.csv")

print("\nNext notebook:")
print("18_Final_Visuals_Update_With_Multi_Indicator_Validation_2002_5Var.ipynb")

17 VALIDATION SYNTHESIS AND FINAL INTERPRETATION COMPLETE
==========================================================================================

,file_name,processed_exists,diagnostics_exists,tables_exists
0,final_poset_structure_summary.csv,True,True,True
1,validation_method_comparison.csv,True,True,True
2,final_validation_synthesis.csv,True,True,True
3,final_mismatch_case_summary.csv,True,True,True
4,final_interpretation_takeaways.csv,True,True,True
5,final_validation_table_updated.csv,True,True,True
6,final_methodological_decisions_updated.csv,True,True,True
7,report_ready_final_interpretation_paragraphs.csv,True,True,True
8,report_ready_validation_paragraphs_updated.csv,True,True,True
9,validation_synthesis_run_summary.csv,True,True,True

Important final framing:
1. Main output = multidimensional structural POSet framework.
2. Not a universal scalar Economic Resilience Index.
3. Validation evidence is descriptive, not causal.
4. Incomparability is a key result, not a weakness.

Key outputs to inspect/send:
- 17_Validation_Synthesis_and_Final_Interpretation_Audit.xlsx
- final_validation_synthesis.csv
- final_interpretation_takeaways.csv
- final_validation_table_updated.csv
- report_ready_final_interpretation_paragraphs.csv

Next notebook:
18_Final_Visuals_Update_With_Multi_Indicator_Validation_2002_5Var.ipynb