In [16]:
import pandas as pd

In [3]:
import sys
!{sys.executable} -m pip install pandas

Requirement already satisfied: pandas in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\21626\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\21626\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [128]:
df = pd.read_csv("OECD_RD_GDP_2000_2025.csv")
df2 = pd.read_csv("OECD_Public_Debt_GDP_2000_2025.csv")
df3 = pd.read_csv("OECD_Productivity_Variation_2000_2025.csv")
df4 = pd.read_csv("OECD_Tertiary_Education_2000_2025.csv")
df5 = pd.read_csv("OECD_Unemployment_Rate_2000_2025.csv")
df6 = pd.read_csv("OECD_Inflation_CPI_2000_2025.csv")
dft = pd.read_csv("OECD_Trust_Institutions_2000_2025.csv")
dfe = pd.read_csv("Eurostat_Energy_Import_Dependency_2000_2025.csv")
dfg = pd.read_csv("OECD_GDP_Growth_2000_2025.csv")
df_ge = pd.read_csv("Global_Energy_Dependency_0_100.csv")
df_eur = pd.read_csv("Eurostat_Public_Debt_GDP_2000_2025.csv")
df_gd = pd.read_csv("Global_Public_Debt_GDP_2000_2025.csv")

In [101]:
dfe

    Country  Year   Value
0        AL  2000  45.781
1        AL  2001  52.210
2        AL  2002  53.360
3        AL  2003  50.757
4        AL  2004  47.764
..      ...   ...     ...
942      XK  2018  29.274
943      XK  2019  30.534
944      XK  2020  29.537
945      XK  2021  32.614
946      XK  2022  32.238

[947 rows x 3 columns]

In [73]:
pip install pycountry

Requirement already satisfied: pycountry in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (26.2.16)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [140]:
import pycountry

def convert_iso2_to_iso3(code):
    try:
        return pycountry.countries.get(alpha_2=code).alpha_3
    except:
        return None

In [141]:
dfe["Country"] = dfe["Country"].apply(convert_iso2_to_iso3)

In [131]:
dfe.head(30)

   Country  Year   Value
0      ALB  2000  45.781
1      ALB  2001  52.210
2      ALB  2002  53.360
3      ALB  2003  50.757
4      ALB  2004  47.764
5      ALB  2005  49.710
6      ALB  2006  40.387
7      ALB  2007  49.179
8      ALB  2008  49.780
9      ALB  2009  46.388
10     ALB  2010  28.897
11     ALB  2011  35.658
12     ALB  2012  15.626
13     ALB  2013  25.300
14     ALB  2014  28.716
15     ALB  2015  12.593
16     ALB  2016  20.128
17     ALB  2017  38.126
18     ALB  2018  20.967
19     ALB  2019  31.546
20     ALB  2020  35.822
21     ALB  2021  23.765
22     ALB  2022  31.467
23     ALB  2023  21.845
24     ALB  2024  27.138
25     AUT  2000  65.543
26     AUT  2001  65.044
27     AUT  2002  68.022
28     AUT  2003  70.993
29     AUT  2004  71.451

In [20]:
#Check inconsistent text
df["Country"] = df["Country"].str.lower().str.strip()

In [77]:
dfe

    Country  Year   Value
0       ALB  2000  45.781
1       ALB  2001  52.210
2       ALB  2002  53.360
3       ALB  2003  50.757
4       ALB  2004  47.764
..      ...   ...     ...
942     NaN  2018  29.274
943     NaN  2019  30.534
944     NaN  2020  29.537
945     NaN  2021  32.614
946     NaN  2022  32.238

[947 rows x 3 columns]

In [146]:
import pandas as pd
import pycountry

files = [
    "OECD_RD_GDP_2000_2025.csv",
    "OECD_Productivity_Variation_2000_2025.csv",
    "OECD_Tertiary_Education_2000_2025.csv",
    "OECD_Unemployment_Rate_2000_2025.csv",
    "OECD_Inflation_CPI_2000_2025.csv",
    "OECD_Trust_Institutions_2000_2025.csv",
    "OECD_GDP_Growth_2000_2025.csv",
    "Global_Energy_Dependency_0_100.csv",
    "Eurostat_Public_Debt_GDP_2000_2025.csv",
    "Global_Public_Debt_GDP_2000_2025.csv"
]


# =========================
# COUNTRY CODE FIX
# =========================
def iso2_to_iso3(code):
    try:
        return pycountry.countries.get(alpha_2=code).alpha_3
    except:
        return None


# =========================
# CLEANING FUNCTION
# =========================
def clean_dataset(df, fix_iso2=False):

    df.columns = df.columns.str.lower().str.strip()

    df = df[["country", "year", "value"]]

    df["year"] = pd.to_numeric(df["year"], errors="coerce").astype(int)
    df["value"] = pd.to_numeric(df["value"], errors="coerce")

    df = df.drop_duplicates()
    df = df.sort_values(["country", "year"])

    # 🔥 FIX ISO2 → ISO3 ONLY IF NEEDED
    if fix_iso2:
        df["country"] = df["country"].apply(iso2_to_iso3)

    df["value"] = df.groupby("country")["value"].transform(
        lambda x: x.interpolate().ffill().bfill()
    )

    return df


# =========================
# LOAD + CLEAN
# =========================
datasets = {}

for file in files:
    df = pd.read_csv(file)

    name = file.replace(".csv", "")

    # 🔥 detect Eurostat dataset
    if "Eurostat" in file:
        datasets[name] = clean_dataset(df, fix_iso2=True)
    else:
        datasets[name] = clean_dataset(df, fix_iso2=False)


# =========================
# PIVOT (SAFE VERSION)
# =========================
pivot_datasets = {}

for name, df in datasets.items():
    pivot_datasets[name] = df.pivot_table(
        index="year",
        columns="country",
        values="value",
        aggfunc="mean"
    ).sort_index()

In [147]:
df_ge

     country  Year      Value
0        AGO  2000   0.000000
1        AGO  2001   0.000000
2        AGO  2002   0.000000
3        AGO  2003   0.000000
4        AGO  2004   0.000000
...      ...   ...        ...
3146     ZWE  2018  23.868661
3147     ZWE  2019  21.200162
3148     ZWE  2020  17.352023
3149     ZWE  2021   9.322581
3150     ZWE  2022  16.975713

[3151 rows x 3 columns]

In [148]:
#merging the datasets based on the year
# STEP 1: Convert each pivot dataset to LONG format
dfs_long = []

for name, df in pivot_datasets.items():
    
    temp = df.reset_index().melt(
        id_vars="year",
        var_name="country",
        value_name="value"
    )
    
    temp["indicator"] = name  # keep track of dataset source
    
    dfs_long.append(temp)


# STEP 2: Concatenate everything into one dataset
df_all = pd.concat(dfs_long, ignore_index=True)


# STEP 3: Pivot to final clean panel format
final_df = df_all.pivot_table(
    index=["year", "country"],
    columns="indicator",
    values="value"
).reset_index()




#Fill intelligently, NaN does NOT mean bad data, it means “data not available for that country-year-indicator”
final_clean = final_df.copy()

numeric_cols = final_clean.select_dtypes(include="number").columns

# 1. interpolate (time structure)
final_clean[numeric_cols] = final_clean.groupby("country")[numeric_cols].transform(
    lambda x: x.interpolate(limit_direction="both")
)

# 2. country mean
final_clean[numeric_cols] = final_clean.groupby("country")[numeric_cols].transform(
    lambda x: x.fillna(x.mean())
)




final_clean

indicator,year,country,Eurostat_Public_Debt_GDP_2000_2025,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,ARG,NaN,0.000000,NaN,-0.788999,34.277230,NaN,0.392499,16.711861,NaN,7.561
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3684,2025,SWE,35.1,27.752405,46.363,1.543167,0.679869,332.353013,3.559558,51.826313,42.4,8.398
3685,2025,TUR,NaN,71.992860,28.557,3.604625,34.881160,91.185172,1.461902,26.944220,NaN,8.712
3686,2025,USA,NaN,0.000000,123.186,2.106338,2.949525,90.335094,3.444858,50.705994,NaN,4.022
3687,2025,USMCA,NaN,NaN,NaN,1.931042,NaN,NaN,NaN,NaN,NaN,NaN
3688,2025,ZAF,NaN,0.000000,74.543,1.114626,4.361153,NaN,0.616860,8.985447,NaN,32.274

In [152]:

final_clean

indicator,year,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025
0,2000,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,ALB,46.518154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,ARE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,ARG,0.000000,NaN,-0.788999,34.277230,NaN,0.392499,16.711861,NaN,7.561
4,2000,ARM,71.191142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3684,2025,SWE,27.752405,46.363,1.543167,0.679869,332.353013,3.559558,51.826313,42.4,8.398
3685,2025,TUR,71.992860,28.557,3.604625,34.881160,91.185172,1.461902,26.944220,NaN,8.712
3686,2025,USA,0.000000,123.186,2.106338,2.949525,90.335094,3.444858,50.705994,NaN,4.022
3687,2025,USMCA,NaN,NaN,1.931042,NaN,NaN,NaN,NaN,NaN,NaN
3688,2025,ZAF,0.000000,74.543,1.114626,4.361153,NaN,0.616860,8.985447,NaN,32.274

In [164]:
missing_by_country = final_clean.groupby("country").apply(
    lambda x: x.isnull().sum()
).drop(columns=["year"]).reset_index()
missing_by_country

indicator,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025
0,AGO,0,23,23,23,23,23,23,23,23
1,ALB,0,24,24,24,24,24,24,24,24
2,ARE,0,23,23,23,23,23,23,23,23
3,ARG,0,26,0,0,26,0,0,26,0
4,ARM,0,23,23,23,23,23,23,23,23
...,...,...,...,...,...,...,...,...,...,...
156,VNM,0,23,23,23,23,23,23,23,23
157,YEM,0,23,23,23,23,23,23,23,23
158,ZAF,0,0,0,0,26,0,0,26,0
159,ZMB,0,23,23,23,23,23,23,23,23
160,ZWE,0,23,23,23,23,23,23,23,23

In [165]:
missing_by_country.to_csv("missing_by_country_4.csv", index=False)

In [166]:
!pip install pycountry

Requirement already satisfied: pycountry in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (26.2.16)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [167]:
#Create conversion function
import pycountry

def country_to_iso3(country_name):
    try:
        return pycountry.countries.lookup(country_name).alpha_3
    except:
        return None

In [168]:
df7 = pd.read_csv("TrustGov_2000_2020.csv")
df7.head()

     country  year  Approval_Not_Smoothed
0  Argentina  1983              67.252609
1  Argentina  1984              61.002979
2  Argentina  1985              58.382301
3  Argentina  1986              54.313831
4  Argentina  1987              48.490929

In [170]:
df7["country"] = df7["country"].apply(country_to_iso3)

In [171]:
df7 = df7[df7["year"] >= 2000]
df7

     country  year  Approval_Not_Smoothed
17       ARG  2000              46.135551
18       ARG  2001              31.172791
19       ARG  2002              30.174061
20       ARG  2003              59.634048
21       ARG  2004              59.264530
...      ...   ...                    ...
2215     VEN  2015              33.350620
2216     VEN  2016              29.990950
2217     VEN  2017              31.979071
2218     VEN  2018              30.125401
2219     VEN  2019              27.662970

[1267 rows x 3 columns]

In [172]:
df7[df7["country"].isnull()]["country"].unique()

<StringArray>
[nan]
Length: 1, dtype: str

In [173]:
#some rows have no country name by the way
df7[df7["country"].isnull()]

     country  year  Approval_Not_Smoothed
1257     NaN  2007              52.485630
1258     NaN  2008              57.206451
1259     NaN  2009              48.144211
1260     NaN  2010              39.845322
1261     NaN  2011              34.870399
...      ...   ...                    ...
1941     NaN  2014              -0.521792
1942     NaN  2015              -1.468777
1943     NaN  2016               0.895465
1944     NaN  2017               0.838192
1945     NaN  2018               0.256912

[161 rows x 3 columns]

In [174]:
#Clening workflow
df7 = df7.dropna(subset=["country"])
df7["country_code"] = df7["country"].apply(country_to_iso3)

In [175]:
df7 = df7.rename(columns={"Approval_Not_Smoothed": "gov_trust"})

In [176]:
#merging
merged = pd.merge(
    final_clean,
    df7,
    on=["country", "year"],
    how="outer"
)

In [177]:
merged

,year,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025,gov_trust,country_code
0,2000,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3970,2018,ZWE,23.868661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3971,2019,ZWE,21.200162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3972,2020,ZWE,17.352023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3973,2021,ZWE,9.322581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3974,2022,ZWE,16.975713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [178]:
merged = merged.drop("country_code", axis=1)

In [179]:
merged

,year,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025,gov_trust
0,2000,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2002,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3970,2018,ZWE,23.868661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3971,2019,ZWE,21.200162,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3972,2020,ZWE,17.352023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3973,2021,ZWE,9.322581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3974,2022,ZWE,16.975713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\21626\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [180]:
dfx = pd.read_excel("Worldwide Governance Indicators.xlsx")

In [181]:
dfx.to_csv("your_file.csv", index=False)

In [182]:
dfx = dfx[dfx["Year"] >= 2000]
dfx

,ID variable (economy code/ gov. dimension/ year),Economy (name),Economy (code),Region,Income classification,Year,Governance dimension,Number of sources,Governance estimate (approx. -2.5 to +2.5),Standard error (estimate),...,OBI mean,PIA mean,PRS mean,RSF mean,VAB mean,VDM mean,WBS mean,WCY mean,WJP mean,WMO mean
403,ADOva2000,Andorra,ADO,NaN,NaN,2000,va,3,1.541361,0.301021,...,..,..,..,..,..,..,..,..,..,1
404,AFGva2000,Afghanistan,AFG,South Asia,Low income,2000,va,4,-2.297846,0.245080,...,..,..,..,..,..,0.245567,..,..,..,0.0625
405,AGOva2000,Angola,AGO,Sub-Saharan Africa,Lower middle income,2000,va,7,-1.678503,0.185910,...,..,..,0.333333,..,..,0.320267,..,..,..,0.125
406,ALBva2000,Albania,ALB,Europe & Central Asia,Upper middle income,2000,va,6,-0.524937,0.204243,...,..,..,0.75,..,..,0.460222,..,..,..,0.375
407,AREva2000,United Arab Emirates,ARE,Middle East & North Africa,High income,2000,va,6,-0.843748,0.193985,...,..,..,0.583333,..,..,0.335233,..,..,..,0.6875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,XKXva2024,Kosovo,XKX,Europe & Central Asia,Upper middle income,2024,va,9,0.159588,0.156446,...,..,0.5,..,0.5273,..,0.607289,..,..,0.578919,..
5440,YEMva2024,"Yemen, Rep.",YEM,Middle East & North Africa,Low income,2024,va,9,-1.697182,0.178875,...,0,0.1,0.416667,0.3145,..,0.3571,..,..,..,..
5441,ZAFva2024,South Africa,ZAF,Sub-Saharan Africa,Upper middle income,2024,va,13,0.607280,0.147152,...,0.82713,..,0.833333,0.7571,..,0.650411,..,0.314754,0.619057,..
5442,ZMBva2024,Zambia,ZMB,Sub-Saharan Africa,Lower middle income,2024,va,14,-0.407569,0.142237,...,0.339358,0.3,0.791667,0.5733,..,0.5176,..,..,0.421383,..
5443,ZWEva2024,Zimbabwe,ZWE,Sub-Saharan Africa,Lower middle income,2024,va,15,-1.259565,0.138858,...,0.629908,0.3,0.333333,0.5201,..,0.393556,..,..,0.333644,..

In [183]:
dfx["Economy (name)"] = dfx["Economy (name)"].apply(country_to_iso3)

In [184]:
dfx

,ID variable (economy code/ gov. dimension/ year),Economy (name),Economy (code),Region,Income classification,Year,Governance dimension,Number of sources,Governance estimate (approx. -2.5 to +2.5),Standard error (estimate),...,OBI mean,PIA mean,PRS mean,RSF mean,VAB mean,VDM mean,WBS mean,WCY mean,WJP mean,WMO mean
403,ADOva2000,AND,ADO,NaN,NaN,2000,va,3,1.541361,0.301021,...,..,..,..,..,..,..,..,..,..,1
404,AFGva2000,AFG,AFG,South Asia,Low income,2000,va,4,-2.297846,0.245080,...,..,..,..,..,..,0.245567,..,..,..,0.0625
405,AGOva2000,AGO,AGO,Sub-Saharan Africa,Lower middle income,2000,va,7,-1.678503,0.185910,...,..,..,0.333333,..,..,0.320267,..,..,..,0.125
406,ALBva2000,ALB,ALB,Europe & Central Asia,Upper middle income,2000,va,6,-0.524937,0.204243,...,..,..,0.75,..,..,0.460222,..,..,..,0.375
407,AREva2000,ARE,ARE,Middle East & North Africa,High income,2000,va,6,-0.843748,0.193985,...,..,..,0.583333,..,..,0.335233,..,..,..,0.6875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,XKXva2024,NaN,XKX,Europe & Central Asia,Upper middle income,2024,va,9,0.159588,0.156446,...,..,0.5,..,0.5273,..,0.607289,..,..,0.578919,..
5440,YEMva2024,NaN,YEM,Middle East & North Africa,Low income,2024,va,9,-1.697182,0.178875,...,0,0.1,0.416667,0.3145,..,0.3571,..,..,..,..
5441,ZAFva2024,ZAF,ZAF,Sub-Saharan Africa,Upper middle income,2024,va,13,0.607280,0.147152,...,0.82713,..,0.833333,0.7571,..,0.650411,..,0.314754,0.619057,..
5442,ZMBva2024,ZMB,ZMB,Sub-Saharan Africa,Lower middle income,2024,va,14,-0.407569,0.142237,...,0.339358,0.3,0.791667,0.5733,..,0.5176,..,..,0.421383,..
5443,ZWEva2024,ZWE,ZWE,Sub-Saharan Africa,Lower middle income,2024,va,15,-1.259565,0.138858,...,0.629908,0.3,0.333333,0.5201,..,0.393556,..,..,0.333644,..

In [185]:
dfx.columns

Index(['ID variable (economy code/ gov. dimension/ year)', 'Economy (name)',
       'Economy (code)', 'Region', 'Income classification', 'Year',
       'Governance dimension', 'Number of sources',
       'Governance estimate (approx. -2.5 to +2.5)',
       'Standard error (estimate)',
       'Lower threshold (90% conf. int. estimate)',
       'Upper threshold (90% conf. int. estimate)', 'Governance score (0-100)',
       'Standard error (gov. score)', 'Lower threshold (90% conf. int. score)',
       'Upper threshold (90% conf. int. score)', 'ADB mean', 'AFR mean',
       'ARB mean', 'ASB mean', 'ASD mean', 'BPS mean', 'BTI mean', 'CCR mean',
       'EBR mean', 'EIU mean', 'EQI mean', 'EUB mean', 'FRH mean', 'GCB mean',
       'GCS mean', 'GII mean', 'GWP mean', 'HER mean', 'HRM mean', 'HUM mean',
       'IFD mean', 'IJT mean', 'IRP mean', 'LBO mean', 'MSI mean', 'OBI mean',
       'PIA mean', 'PRS mean', 'RSF mean', 'VAB mean', 'VDM mean', 'WBS mean',
       'WCY mean', 'WJP mean', 'WMO mean'],
      dtype='str')

In [186]:
dfx = dfx.drop(['ID variable (economy code/ gov. dimension/ year)',
       'Economy (code)', 'Region', 'Income classification',
       'Governance dimension', 'Number of sources',
       'Governance estimate (approx. -2.5 to +2.5)',
       'Standard error (estimate)',
       'Lower threshold (90% conf. int. estimate)',
       'Upper threshold (90% conf. int. estimate)',
       'Standard error (gov. score)', 'Lower threshold (90% conf. int. score)',
       'Upper threshold (90% conf. int. score)', 'ADB mean', 'AFR mean',
       'ARB mean', 'ASB mean', 'ASD mean', 'BPS mean', 'BTI mean', 'CCR mean',
       'EBR mean', 'EIU mean', 'EQI mean', 'EUB mean', 'FRH mean', 'GCB mean',
       'GCS mean', 'GII mean', 'GWP mean', 'HER mean', 'HRM mean', 'HUM mean',
       'IFD mean', 'IJT mean', 'IRP mean', 'LBO mean', 'MSI mean', 'OBI mean',
       'PIA mean', 'PRS mean', 'RSF mean', 'VAB mean', 'VDM mean', 'WBS mean',
       'WCY mean', 'WJP mean', 'WMO mean'], axis=1)

In [187]:
dfx

     Economy (name)  Year  Governance score (0-100)
403             AND  2000                 83.826902
404             AFG  2000                 16.631208
405             AGO  2000                 27.471257
406             ALB  2000                 47.661534
407             ARE  2000                 42.081555
...             ...   ...                       ...
5439            NaN  2024                 59.642428
5440            NaN  2024                 27.144335
5441            ZAF  2024                 67.478144
5442            ZMB  2024                 49.715769
5443            ZWE  2024                 34.803724

[5041 rows x 3 columns]

In [188]:
dfx.rename(columns={"Economy (name)": "country"}, inplace=True)
dfx.rename(columns={"Year": "year"}, inplace=True)

In [250]:
#merging
final_merged = pd.merge(
    final_clean,
    dfx,
    on=["country", "year"],
    how="inner"
)

In [251]:
final_merged

,year,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025,Governance score (0-100)
0,2000,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.471257
1,2000,ALB,46.518154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.661534
2,2000,ARE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.081555
3,2000,ARG,0.000000,NaN,-0.788999,34.277230,NaN,0.392499,16.711861,NaN,7.561,64.590212
4,2000,ARM,71.191142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.781340
...,...,...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,48.902182,69.318,1.731397,1.965627,48.513447,2.162628,34.637478,57.9,3.697,75.351985
2857,2024,SWE,27.752405,46.363,1.017797,2.835817,332.353013,3.559558,51.826313,42.4,8.398,87.089942
2858,2024,TUR,71.992860,28.557,3.327623,58.506450,91.185172,1.461902,26.944220,NaN,8.712,37.689790
2859,2024,USA,0.000000,123.186,2.793187,2.949525,90.335094,3.444858,50.705994,NaN,4.022,72.373172
2860,2024,ZAF,0.000000,74.543,0.534844,4.361153,NaN,0.616860,8.985447,NaN,32.274,67.478144

In [242]:
missing_rows = final_clean[final_clean.isnull().any(axis=1)]
missing_rows.head(30)

indicator,year,country,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Trust_Institutions_2000_2025,OECD_Unemployment_Rate_2000_2025
0,2000,AGO,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000,ALB,46.518154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,ARE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,ARG,0.000000,NaN,-0.788999,34.277230,NaN,0.392499,16.711861,NaN,7.561000
4,2000,ARM,71.191142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2000,AZE,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2000,BEN,28.097710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2000,BGD,17.650915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2000,BGR,46.864953,48.474,NaN,10.316260,11.549349,0.495167,27.498056,NaN,16.919000
12,2000,BHR,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2000,BIH,29.020877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2000,BLR,85.491586,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2000,BOL,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2000,BRA,23.641203,87.124,4.387949,7.044141,NaN,NaN,9.623828,NaN,9.358000
17,2000,BRN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2000,CHN,2.458075,NaN,8.600000,0.400000,NaN,0.884096,9.681174,NaN,3.576000
22,2000,CIV,14.600340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2000,CMR,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2000,COD,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2000,COG,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2000,CRI,61.418134,NaN,3.802072,10.961550,1659.605512,0.556213,16.448679,42.9,5.082000
28,2000,CUW,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2000,CYP,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.967000
33,2000,DZA,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2000,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.450139
35,2000,EA20,NaN,NaN,NaN,2.188880,41.793380,NaN,NaN,NaN,NaN
36,2000,ECU,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2000,EGY,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2000,EU,NaN,NaN,3.897463,NaN,NaN,NaN,NaN,NaN,NaN
41,2000,EU19OECD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.034000

In [252]:
final_merged = final_merged.rename(columns={"OECD_GDP_Growth_2000_2025": "R&D expenditure (%GDP)"})
final_merged = final_merged.rename(columns={"OECD_Trust_Institutions_2000_2025": "trust_in_institutions"})
final_merged = final_merged.rename(columns={"Global_Public_Debt_GDP_2000_2025": "Public_Debt (%GDP)"})
final_merged = final_merged.rename(columns={"Global_Energy_Dependency_0_100": "Energy_Import_Dependency"})
final_merged = final_merged.rename(columns={"OECD_Tertiary_Education_2000_2025": "Tertiary_education_attainment"})

In [253]:
final_df1 = final_merged[
    [
        "year",
        "country",
        "R&D expenditure (%GDP)",
        "trust_in_institutions",
        "Public_Debt (%GDP)",
        "Energy_Import_Dependency",
        "Tertiary_education_attainment"
     
    ]
]

In [254]:
final_merged = final_merged.rename(columns={"OECD_Inflation_CPI_2000_2025": "Inflation_Rate"})
final_merged = final_merged.rename(columns={"OECD_Unemployment_Rate_2000_2025": "Unemployment_Variation"})
final_merged = final_merged.rename(columns={"Governance score (0-100)": "Gov_score"})
final_merged = final_merged.rename(columns={"OECD_Productivity_Variation_2000_2025": "Productivity_Variation"})
final_merged = final_merged.rename(columns={"R&D expenditure (%GDP)": "GDP_Growth"})
final_df2 = final_merged[
    [
        "year",
        "country",
        "Inflation_Rate",
        "Unemployment_Variation",
        "Gov_score",
        "Productivity_Variation",
        "GDP_Growth"
        
    ]
]

In [255]:
final_df1

,year,country,R&D expenditure (%GDP),trust_in_institutions,Public_Debt (%GDP),Energy_Import_Dependency,Tertiary_education_attainment
0,2000,AGO,NaN,NaN,NaN,0.000000,NaN
1,2000,ALB,NaN,NaN,NaN,46.518154,NaN
2,2000,ARE,NaN,NaN,NaN,0.000000,NaN
3,2000,ARG,-0.788999,NaN,NaN,0.000000,16.711861
4,2000,ARM,NaN,NaN,NaN,71.191142,NaN
...,...,...,...,...,...,...,...
2856,2024,SVN,1.731397,57.9,69.318,48.902182,34.637478
2857,2024,SWE,1.017797,42.4,46.363,27.752405,51.826313
2858,2024,TUR,3.327623,NaN,28.557,71.992860,26.944220
2859,2024,USA,2.793187,NaN,123.186,0.000000,50.705994
2860,2024,ZAF,0.534844,NaN,74.543,0.000000,8.985447

In [256]:
final_df2

,year,country,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth
0,2000,AGO,NaN,NaN,27.471257,NaN,NaN
1,2000,ALB,NaN,NaN,47.661534,NaN,NaN
2,2000,ARE,NaN,NaN,42.081555,NaN,NaN
3,2000,ARG,34.277230,7.561,64.590212,NaN,-0.788999
4,2000,ARM,NaN,NaN,46.781340,NaN,NaN
...,...,...,...,...,...,...,...
2856,2024,SVN,1.965627,3.697,75.351985,48.513447,1.731397
2857,2024,SWE,2.835817,8.398,87.089942,332.353013,1.017797
2858,2024,TUR,58.506450,8.712,37.689790,91.185172,3.327623
2859,2024,USA,2.949525,4.022,72.373172,90.335094,2.793187
2860,2024,ZAF,4.361153,32.274,67.478144,NaN,0.534844

In [269]:
final_df3 = final_merged[
    [
        "year",
        "country",
        "Public_Debt (%GDP)",
        "Energy_Import_Dependency",
        "Tertiary_education_attainment",
        "Inflation_Rate",
        "Unemployment_Variation",
        "Gov_score",
        "Productivity_Variation",
        "GDP_Growth"
        
    ]
]

In [246]:
numeric_cols = final_df3.select_dtypes(include="number").columns

missing_by_country = final_df3.groupby("country")[numeric_cols].apply(
    lambda x: x.isnull().sum().sum()
).reset_index(name="missing_count")

final_df3 = final_df3.merge(missing_by_country, on="country", how="left")
final_df3

,year,country,Public_Debt (%GDP),Energy_Import_Dependency,Tertiary_education_attainment,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth,missing_count
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,27.471257,NaN,NaN,132
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,47.661534,NaN,NaN,138
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,42.081555,NaN,NaN,132
3,2000,ARG,NaN,0.000000,16.711861,34.277230,7.561,64.590212,NaN,-0.788999,48
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,46.781340,NaN,NaN,132
...,...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,69.318,48.902182,34.637478,1.965627,3.697,75.351985,48.513447,1.731397,0
2857,2024,SWE,46.363,27.752405,51.826313,2.835817,8.398,87.089942,332.353013,1.017797,0
2858,2024,TUR,28.557,71.992860,26.944220,58.506450,8.712,37.689790,91.185172,3.327623,0
2859,2024,USA,123.186,0.000000,50.705994,2.949525,4.022,72.373172,90.335094,2.793187,0
2860,2024,ZAF,74.543,0.000000,8.985447,4.361153,32.274,67.478144,NaN,0.534844,24

In [270]:
final_df3

,year,country,Public_Debt (%GDP),Energy_Import_Dependency,Tertiary_education_attainment,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,27.471257,NaN,NaN
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,47.661534,NaN,NaN
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,42.081555,NaN,NaN
3,2000,ARG,NaN,0.000000,16.711861,34.277230,7.561,64.590212,NaN,-0.788999
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,46.781340,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,69.318,48.902182,34.637478,1.965627,3.697,75.351985,48.513447,1.731397
2857,2024,SWE,46.363,27.752405,51.826313,2.835817,8.398,87.089942,332.353013,1.017797
2858,2024,TUR,28.557,71.992860,26.944220,58.506450,8.712,37.689790,91.185172,3.327623
2859,2024,USA,123.186,0.000000,50.705994,2.949525,4.022,72.373172,90.335094,2.793187
2860,2024,ZAF,74.543,0.000000,8.985447,4.361153,32.274,67.478144,NaN,0.534844

In [259]:
final_df3

,year,country,Public_Debt (%GDP),Energy_Import_Dependency,Tertiary_education_attainment,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,27.471257,NaN,NaN
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,47.661534,NaN,NaN
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,42.081555,NaN,NaN
3,2000,ARG,NaN,0.000000,16.711861,34.277230,7.561,64.590212,NaN,-0.788999
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,46.781340,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,69.318,48.902182,34.637478,1.965627,3.697,75.351985,48.513447,1.731397
2857,2024,SWE,46.363,27.752405,51.826313,2.835817,8.398,87.089942,332.353013,1.017797
2858,2024,TUR,28.557,71.992860,26.944220,58.506450,8.712,37.689790,91.185172,3.327623
2859,2024,USA,123.186,0.000000,50.705994,2.949525,4.022,72.373172,90.335094,2.793187
2860,2024,ZAF,74.543,0.000000,8.985447,4.361153,32.274,67.478144,NaN,0.534844

In [271]:
final_df3 = final_df3[final_df3.isnull().sum(axis=1) <= 6]

In [272]:
final_df3

,year,country,Public_Debt (%GDP),Energy_Import_Dependency,Tertiary_education_attainment,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,27.471257,NaN,NaN
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,47.661534,NaN,NaN
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,42.081555,NaN,NaN
3,2000,ARG,NaN,0.000000,16.711861,34.277230,7.561,64.590212,NaN,-0.788999
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,46.781340,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,69.318,48.902182,34.637478,1.965627,3.697,75.351985,48.513447,1.731397
2857,2024,SWE,46.363,27.752405,51.826313,2.835817,8.398,87.089942,332.353013,1.017797
2858,2024,TUR,28.557,71.992860,26.944220,58.506450,8.712,37.689790,91.185172,3.327623
2859,2024,USA,123.186,0.000000,50.705994,2.949525,4.022,72.373172,90.335094,2.793187
2860,2024,ZAF,74.543,0.000000,8.985447,4.361153,32.274,67.478144,NaN,0.534844

In [268]:
final_df3.to_csv("the_fulldataset_fixed", index=False)

In [214]:
final_df1.to_csv("first_separated2", index=False)
final_df2.to_csv("second_separated2", index=False)

In [109]:
col = "Energy_Import_Dependency"
missing_countries = final_df3.loc[
    final_df3[col].isnull(),
    ["country", col]
].drop_duplicates()

In [114]:
missing_countries

     country  Energy_Import_Dependency
24       ARG                       NaN
48       AUS                       NaN
191      BOL                       NaN
209      BRA                       NaN
233      CAN                       NaN
257      CHE                       NaN
281      CHL                       NaN
305      CHN                       NaN
329      COL                       NaN
353      CRI                       NaN
527      DOM                       NaN
546      ECU                       NaN
698      GBR                       NaN
734      GRC                       NaN
758      GTM                       NaN
777      HND                       NaN
844      IDN                       NaN
868      IND                       NaN
940      ISR                       NaN
988      JPN                       NaN
1099     MEX                       NaN
1182     MNE                       NaN
1203     NIC                       NaN
1269     NZL                       NaN
1293     PAN                       NaN
1312     PER                       NaN
1336     PHL                       NaN
1494     PRY                       NaN
1536     RUS                       NaN
1558     SAU                       NaN
1582     SGP                       NaN
1605     SLV                       NaN
1793     URY                       NaN
1811     USA                       NaN
1835     ZAF                       NaN

In [115]:
missing_countries.to_csv("countries_with _missingvalues_ENERGYDATASET.csv", index=False)

In [116]:
col = "Public_Debt (%GDP)"
missing_countries2 = final_df3.loc[
    final_df3[col].isnull(),
    ["country", col]
].drop_duplicates()
missing_countries2

     country  Public_Debt (%GDP)
0        ALB                 NaN
24       ARG                 NaN
180      BIH                 NaN
191      BOL                 NaN
305      CHN                 NaN
353      CRI                 NaN
377      CYP                 NaN
527      DOM                 NaN
546      ECU                 NaN
722      GEO                 NaN
758      GTM                 NaN
777      HND                 NaN
868      IND                 NaN
1084     MDA                 NaN
1123     MKD                 NaN
1158     MLT                 NaN
1182     MNE                 NaN
1203     NIC                 NaN
1293     PAN                 NaN
1312     PER                 NaN
1336     PHL                 NaN
1494     PRY                 NaN
1536     RUS                 NaN
1558     SAU                 NaN
1582     SGP                 NaN
1605     SLV                 NaN
1624     SRB                 NaN
1744     UKR                 NaN
1793     URY                 NaN

In [117]:
missing_countries2.to_csv("countries_with _missingvalues_PublicDebtGDP.csv", index=False)

In [93]:
final_df3.to_csv("completedataset2.csv", index=False)

In [314]:
#to find where saved
import os
os.getcwd()

'C:\\Users\\21626\\Desktop\\ds_lab'

In [51]:
import numpy as np

# function to calculate recovery time
def calculate_recovery_time(df, shock_year, gdp_col):

    recovery_times = []

    for country in df["country"].unique():

        country_df = df[df["country"] == country].sort_values("year")

        # get GDP value before shock
        try:
            baseline = country_df.loc[
                country_df["year"] == shock_year,
                gdp_col
            ].values[0]
        except:
            continue

        recovery_year = np.nan

        # search future years
        future_data = country_df[country_df["year"] > shock_year]

        for _, row in future_data.iterrows():

            if row[gdp_col] >= baseline:
                recovery_year = row["year"] - shock_year
                break

        # assign result to all rows of that country
        country_df = country_df.copy()
        country_df[f"recovery_{shock_year}"] = recovery_year

        recovery_times.append(country_df)

    return pd.concat(recovery_times)


# =========================
# APPLY FOR 2007
# =========================
final_df2 = calculate_recovery_time(
    final_df2,
    shock_year=2007,
    gdp_col="GDP_Growth"
)

# =========================
# APPLY FOR 2019
# =========================
final_df2 = calculate_recovery_time(
    final_df2,
    shock_year=2019,
    gdp_col="GDP_Growth"
)

In [56]:
final_df2.head(100)

,year,country,Inflation_Rate,Unemployment_Variation,Gov_score,Productivity_Variation,GDP_Growth
0,2000,ALB,NaN,NaN,47.661534,NaN,NaN
1,2002,ALB,NaN,NaN,53.080731,NaN,NaN
2,2003,ALB,NaN,NaN,54.631023,NaN,NaN
3,2004,ALB,NaN,NaN,56.665036,NaN,NaN
4,2005,ALB,NaN,NaN,58.610539,NaN,NaN
...,...,...,...,...,...,...,...
95,2018,AUT,1.998382,4.848,82.479855,67.608703,2.484221
96,2019,AUT,1.530895,4.487,82.317535,68.750874,1.754976
97,2020,AUT,1.381909,5.363,83.628517,68.190766,-6.318255
98,2021,AUT,2.766667,6.181,82.945515,72.742376,4.923092
99,2022,AUT,8.546870,4.741,82.672952,77.057265,5.330973

In [56]:
final_df1.to_csv("finalfinalfinal_dataset_one.csv", index=False)

final_df2.to_csv("finalfinalfinal_dataset_two.csv", index=False)

In [298]:
df12 = pd.read_csv("final_dataset_all_12_columns.csv")

In [299]:
df12

,year,country,Eurostat_Public_Debt_GDP_2000_2025,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Unemployment_Rate_2000_2025,Worldwide_Governance_Indicators
0,2000,AGO,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.471257
1,2000,ALB,NaN,46.518154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.661534
2,2000,ARE,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42.081555
3,2000,ARG,NaN,0.000000,NaN,-0.788999,34.277230,NaN,0.392499,16.711861,7.561,64.590212
4,2000,ARM,NaN,71.191142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.781340
...,...,...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,66.4,48.902182,69.318,1.731397,1.965627,48.513447,2.162628,34.637478,3.697,75.351985
2857,2024,SWE,34.2,27.752405,46.363,1.017797,2.835817,332.353013,3.559558,51.826313,8.398,87.089942
2858,2024,TUR,NaN,71.992860,28.557,3.327623,58.506450,91.185172,1.461902,26.944220,8.712,37.689790
2859,2024,USA,NaN,0.000000,123.186,2.793187,2.949525,90.335094,3.444858,50.705994,4.022,72.373172
2860,2024,ZAF,NaN,0.000000,74.543,0.534844,4.361153,NaN,0.616860,8.985447,32.274,67.478144

In [316]:
# ==============================
# WORKING DATASET
# ==============================
df = df12.copy()

# ==============================
# STEP 1: Identify numeric columns
# ==============================
numeric_cols = df.select_dtypes(include="number").columns

# ==============================
# STEP 2: Compute missing ratio per country
# ==============================
missing_ratio = df.groupby("country")[numeric_cols].apply(
    lambda x: x.isnull().mean().mean()
)

# ==============================
# STEP 3: Keep countries with acceptable missingness
# ==============================
good_countries = missing_ratio[missing_ratio < 0.30].index
df_clean = df[df["country"].isin(good_countries)].copy()

# ==============================
# STEP 4: COUNTRY-LEVEL MEAN IMPUTATION
# (fill NaNs using mean of same country)
# ==============================
df_clean[numeric_cols] = df_clean.groupby("country")[numeric_cols].transform(
    lambda x: x.fillna(x.mean())
)

# ==============================
# STEP 5: GLOBAL MEAN IMPUTATION (rounded to 2 decimals)
# ==============================
global_means = df_clean[numeric_cols].mean().round(2)

df_clean[numeric_cols] = df_clean[numeric_cols].fillna(global_means)

# ==============================
# STEP 6: CHECK RESULT
# ==============================
df_clean.head(50)

,year,country,Eurostat_Public_Debt_GDP_2000_2025,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Unemployment_Rate_2000_2025,Worldwide_Governance_Indicators
3,2000,ARG,56.44,0.000000,68.830,-0.788999,34.277230,739.790000,0.392499,16.711861,7.561000,64.590212
5,2000,AUS,56.44,0.000000,12.765,3.359670,4.457435,52.464076,1.469756,27.475746,6.288000,82.051731
6,2000,AUT,66.60,66.900318,70.344,3.189522,2.344868,47.091146,1.896676,24.783438,3.502000,81.175534
8,2000,BEL,109.70,87.219960,94.929,3.716706,2.544518,53.979823,1.936195,27.084993,7.009000,82.118608
11,2000,BGR,70.70,46.864953,48.474,2.610000,10.316260,11.549349,0.495167,27.498056,16.919000,62.642856
16,2000,BRA,56.44,23.641203,87.124,4.387949,7.044141,739.790000,1.640000,9.623828,9.358000,61.899754
18,2000,CAN,56.44,0.000000,71.325,5.138539,2.719440,45.872960,1.858470,40.105782,6.821000,85.196202
19,2000,CHE,56.44,56.694553,45.939,3.633217,1.558529,61.589523,2.238910,24.177282,2.657000,84.156770
20,2000,CHL,56.44,70.494045,11.376,4.971621,3.843273,3061.758841,0.311431,17.120726,10.481000,75.183648
21,2000,CHN,56.44,2.458075,68.830,8.600000,0.400000,739.790000,0.884096,9.681174,3.576000,28.962658
23,2000,COL,56.44,0.000000,49.574,6.716869,9.225347,5211.454994,0.140081,16.965132,15.040000,46.483791
24,2000,CRI,56.44,61.418134,68.830,3.802072,10.961550,1659.605512,0.556213,16.448679,5.082000,75.855560
26,2000,CZE,16.90,22.779863,30.775,4.010670,3.775388,176.261856,1.103771,10.963162,8.764000,69.478801
27,2000,DEU,59.20,61.103958,66.353,2.879663,1.440268,47.861445,2.386541,23.498837,7.748000,84.748357
28,2000,DNK,53.60,0.000000,37.457,3.724008,2.903277,225.937333,2.323393,25.777601,4.429000,86.077768
31,2000,ESP,57.80,82.140732,42.274,5.200754,3.433517,33.984209,0.883147,22.704889,13.863000,79.118326
32,2000,EST,5.10,34.749310,7.301,10.087637,4.018489,14.177796,0.600007,28.669167,14.535000,75.510451
33,2000,FIN,45.10,57.116594,41.088,5.753635,3.042096,45.813832,3.242713,32.614372,9.732000,86.308926
34,2000,FRA,59.70,52.659718,77.260,4.141053,1.675960,49.285206,2.100661,21.584810,8.557000,78.302325
36,2000,GBR,56.44,0.000000,50.333,4.524381,1.200000,41.347367,1.603789,25.683083,5.383000,81.137895
40,2000,GRC,56.44,80.223884,114.683,4.137827,3.151178,24.371194,0.577528,17.672335,11.350000,78.341429
43,2000,HRV,35.40,48.890391,45.014,2.610000,4.616667,16.979702,0.940881,22.781458,14.708000,61.254924
44,2000,HUN,55.60,55.477055,71.895,4.409376,9.803608,1426.767801,0.789995,14.041859,6.401000,76.883763
45,2000,IDN,56.44,0.000000,30.713,4.920041,3.688618,739.790000,1.640000,8.129610,6.078000,44.580786
47,2000,IRL,36.40,89.258813,27.475,9.403525,5.577633,42.564093,1.083826,21.613003,4.885000,81.137363
49,2000,ISL,56.44,20.488914,72.434,4.905182,5.136475,2475.991570,2.539789,27.861868,2.310000,82.625867
50,2000,ISR,56.44,99.636880,78.682,8.688871,1.032636,76.350601,3.816024,42.090389,11.042000,65.266349
51,2000,ITA,108.70,88.867904,109.755,3.882092,2.537687,44.143599,1.001033,9.377047,10.518000,73.247510
54,2000,JPN,56.44,82.815836,153.206,2.978306,-0.700000,2167.016812,2.858408,33.615494,4.774000,75.168167
61,2000,LTU,23.50,59.115736,19.388,3.418620,0.981615,12.791926,0.584218,41.801403,16.404000,70.558580
62,2000,LUX,7.50,100.000000,17.207,6.938091,3.150768,78.540984,1.583134,18.284153,2.345000,82.927531
63,2000,LVA,12.40,61.533715,14.003,5.841013,2.654253,10.698109,0.445898,18.218046,14.259000,67.138258
66,2000,MEX,56.44,0.000000,41.202,5.029284,9.491560,84.043851,0.292046,14.635047,2.564000,59.725782
76,2000,NLD,52.20,46.482049,50.366,4.227832,2.360522,50.486096,1.789067,23.375116,3.047000,86.391131
77,2000,NOR,56.44,0.000000,55.846,3.443431,3.085506,339.430177,1.560195,32.692787,3.331000,85.662654
79,2000,NZL,56.44,19.547953,25.729,4.212489,2.615233,40.388922,1.100286,35.628941,6.131000,83.745846
85,2000,POL,36.20,10.781624,51.475,4.656228,10.091670,28.171458,0.638060,11.362040,16.370000,78.082683
86,2000,PRT,54.20,89.690746,80.161,3.816177,2.853030,24.155270,0.721562,8.842939,3.928000,80.954206
89,2000,ROU,22.50,21.699959,16.691,2.610000,4.490000,13.235794,0.366258,17.160242,7.157000,59.488051
99,2000,SVK,50.60,65.004711,36.467,0.789224,12.035780,16.015311,0.638651,10.373340,18.777000,71.372113
100,2000,SVN,26.10,51.783342,30.907,3.497917,8.911745,23.077898,1.368615,15.726464,6.729000,75.601005
101,2000,SWE,50.40,40.501877,48.015,4.631145,0.899144,252.929399,3.872174,30.122953,5.799000,86.069732
110,2000,TUR,56.44,66.411898,48.901,6.985287,54.915380,25.984351,0.464808,8.346184,6.495000,47.643146
114,2000,USA,56.44,26.679145,64.674,4.077586,3.376857,49.731667,2.619835,36.494774,3.992000,79.244052
117,2000,ZAF,56.44,0.000000,38.354,4.200000,5.338953,739.790000,0.642237,6.860743,25.370734,65.822956
123,2002,ARG,56.44,0.000000,68.830,-10.894485,34.277230,739.790000,0.347796,16.711861,7.561000,62.677686
125,2002,AUS,56.44,0.000000,12.765,3.998847,2.981575,55.999973,1.642327,30.759785,6.375000,82.253383
126,2002,AUT,67.40,69.180972,70.344,1.484368,1.810359,49.186918,2.081104,24.783438,3.985000,81.592225
128,2002,BEL,105.60,88.576900,94.929,1.706867,1.645214,55.587515,1.903248,28.134819,7.514000,83.281771
131,2002,BGR,51.00,47.421179,48.474,2.610000,5.810143,12.982414,0.464728,27.498056,18.178000,64.080993

In [317]:
df_clean.to_csv("final_dataset_all_12_columns_fixed_missing_values.csv", index=False)

In [318]:
df_clean

,year,country,Eurostat_Public_Debt_GDP_2000_2025,Global_Energy_Dependency_0_100,Global_Public_Debt_GDP_2000_2025,OECD_GDP_Growth_2000_2025,OECD_Inflation_CPI_2000_2025,OECD_Productivity_Variation_2000_2025,OECD_RD_GDP_2000_2025,OECD_Tertiary_Education_2000_2025,OECD_Unemployment_Rate_2000_2025,Worldwide_Governance_Indicators
3,2000,ARG,56.44,0.000000,68.830,-0.788999,34.277230,739.790000,0.392499,16.711861,7.561,64.590212
5,2000,AUS,56.44,0.000000,12.765,3.359670,4.457435,52.464076,1.469756,27.475746,6.288,82.051731
6,2000,AUT,66.60,66.900318,70.344,3.189522,2.344868,47.091146,1.896676,24.783438,3.502,81.175534
8,2000,BEL,109.70,87.219960,94.929,3.716706,2.544518,53.979823,1.936195,27.084993,7.009,82.118608
11,2000,BGR,70.70,46.864953,48.474,2.610000,10.316260,11.549349,0.495167,27.498056,16.919,62.642856
...,...,...,...,...,...,...,...,...,...,...,...,...
2856,2024,SVN,66.40,48.902182,69.318,1.731397,1.965627,48.513447,2.162628,34.637478,3.697,75.351985
2857,2024,SWE,34.20,27.752405,46.363,1.017797,2.835817,332.353013,3.559558,51.826313,8.398,87.089942
2858,2024,TUR,56.44,71.992860,28.557,3.327623,58.506450,91.185172,1.461902,26.944220,8.712,37.689790
2859,2024,USA,56.44,0.000000,123.186,2.793187,2.949525,90.335094,3.444858,50.705994,4.022,72.373172
2860,2024,ZAF,56.44,0.000000,74.543,0.534844,4.361153,739.790000,0.616860,8.985447,32.274,67.478144