# 02 — GDP Recovery Dynamic Baseline

This notebook comes after:

`01_Raw_Files_Coverage_Diagnostics.ipynb`

Purpose:

Construct observed GDP recovery outcome variables using the standardized `gdp_growth` series.

This notebook creates:

- `Recovery_2007`
- `Recovery_2019`

Core logic:

For the 2007 shock window:

- check 2008 and 2009;
- if the first negative GDP growth year is 2008, baseline year = 2007;
- if the first negative GDP growth year is 2009, baseline year = 2008.

For the 2019 shock window:

- check 2020 and 2021;
- if the first negative GDP growth year is 2020, baseline year = 2019;
- if the first negative GDP growth year is 2021, baseline year = 2020.

Special values:

- no negative growth in shock window → recovery value = `0`;
- not recovered by available data → recovery value = `20`;
- no shock-window data → recovery value is missing and flagged.

Important:

- This notebook uses GDP growth only.
- It does not use structural POSet variables.
- It does not impute missing GDP growth.
- It does not choose the final POSet country sample.
- Recovery outcomes are for validation / interpretation later, not for constructing the POSet order.

In [1]:
# ------------------------------------------------------
# IMPORTS AND PATHS
# ------------------------------------------------------

from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np
import re
import shutil
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 200)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", "{:.4f}".format)

PROJECT_ROOT = Path.cwd()

INPUT_FILE = (
    PROJECT_ROOT
    / "Data"
    / "Processed"
    / "00_Comparable_Raw_Files"
    / "Combined_Long"
    / "all_comparable_sources_long.csv"
)

PROCESSED_DIR = PROJECT_ROOT / "Data" / "Processed" / "Recovery"
DIAGNOSTICS_DIR = PROJECT_ROOT / "Data" / "Diagnostics" / "02_GDP_Recovery_Dynamic_Baseline"
AUDIT_DIR = PROJECT_ROOT / "Data" / "Audit"

RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
RUN_TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

CLEAR_PREVIOUS_OUTPUTS = True

if CLEAR_PREVIOUS_OUTPUTS:
    for folder in [PROCESSED_DIR, DIAGNOSTICS_DIR]:
        if folder.exists():
            shutil.rmtree(folder)

for folder in [PROCESSED_DIR, DIAGNOSTICS_DIR, AUDIT_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

print("Run ID:", RUN_ID)
print("Input file:", INPUT_FILE.resolve())
print("Processed folder:", PROCESSED_DIR.resolve())
print("Diagnostics folder:", DIAGNOSTICS_DIR.resolve())
print("Audit folder:", AUDIT_DIR.resolve())

Run ID: 20260622_030128
Input file: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\00_Comparable_Raw_Files\Combined_Long\all_comparable_sources_long.csv
Processed folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Recovery
Diagnostics folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Diagnostics\02_GDP_Recovery_Dynamic_Baseline
Audit folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Audit

In [2]:
# ------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------

GDP_GROWTH_VARIABLE = "gdp_growth"

NOT_RECOVERED_VALUE = 20

# Final Recovery_2007 / Recovery_2019 value definition:
#
# If recovered:
#     recovery_year - first_negative_growth_year
#
# Example:
#     if first negative year = 2020 and index returns to baseline in 2021,
#     the recovery value is 1.
#
# For transparency, the notebook also exports:
#     years_from_baseline_to_recovery
#     years_after_first_negative_to_recovery

FINAL_RECOVERY_TIME_DEFINITION = "years_after_first_negative_growth_year"

SHOCK_CONFIGS = [
    {
        "shock_id": "2007",
        "recovery_column": "Recovery_2007",
        "shock_window_years": [2008, 2009],
        "not_recovered_value": NOT_RECOVERED_VALUE,
    },
    {
        "shock_id": "2019",
        "recovery_column": "Recovery_2019",
        "shock_window_years": [2020, 2021],
        "not_recovered_value": NOT_RECOVERED_VALUE,
    },
]

print("GDP growth variable:", GDP_GROWTH_VARIABLE)
print("Final recovery time definition:", FINAL_RECOVERY_TIME_DEFINITION)
pd.DataFrame(SHOCK_CONFIGS)

GDP growth variable: gdp_growth
Final recovery time definition: years_after_first_negative_growth_year

  shock_id recovery_column shock_window_years  not_recovered_value
0     2007   Recovery_2007       [2008, 2009]                   20
1     2019   Recovery_2019       [2020, 2021]                   20

In [3]:
# ------------------------------------------------------
# LOAD STANDARDIZED GDP GROWTH DATA
# ------------------------------------------------------

if not INPUT_FILE.exists():
    raise FileNotFoundError(f"Input file not found: {INPUT_FILE}")

source = pd.read_csv(INPUT_FILE)

required_columns = {"Country", "Year", "variable", "Value"}

missing_columns = required_columns - set(source.columns)

if missing_columns:
    raise ValueError(f"Input file missing required columns: {missing_columns}")

source["Country"] = source["Country"].astype(str).str.strip().str.upper()
source["Year"] = pd.to_numeric(source["Year"], errors="coerce")
source["Value"] = pd.to_numeric(source["Value"], errors="coerce")

source = source.dropna(subset=["Country", "Year", "variable", "Value"]).copy()
source["Year"] = source["Year"].astype(int)

gdp_growth = source[source["variable"] == GDP_GROWTH_VARIABLE].copy()

if gdp_growth.empty:
    raise ValueError(f"No rows found for variable: {GDP_GROWTH_VARIABLE}")

# Keep useful metadata if present
metadata_cols = [
    col for col in [
        "Country",
        "country_name",
        "Year",
        "Value",
        "source_file",
        "source_family",
        "concept",
        "expected_unit",
    ]
    if col in gdp_growth.columns
]

gdp_growth = gdp_growth[metadata_cols].copy()

if "country_name" not in gdp_growth.columns:
    gdp_growth["country_name"] = gdp_growth["Country"]

duplicate_check = (
    gdp_growth
    .groupby(["Country", "Year"])
    .agg(
        row_count=("Value", "size"),
        unique_values=("Value", "nunique"),
        min_value=("Value", "min"),
        max_value=("Value", "max"),
    )
    .reset_index()
    .query("row_count > 1")
)

duplicate_check.to_csv(
    DIAGNOSTICS_DIR / "gdp_growth_duplicate_country_year_check.csv",
    index=False,
)

if len(duplicate_check.query("unique_values > 1")) > 0:
    display(duplicate_check)
    raise ValueError("Conflicting duplicate GDP growth Country-Year rows found.")

if len(duplicate_check) > 0:
    print("Only exact duplicate GDP growth rows found. Dropping exact duplicates.")
    gdp_growth = gdp_growth.drop_duplicates(subset=["Country", "Year", "Value"]).copy()

gdp_growth = gdp_growth.sort_values(["Country", "Year"]).reset_index(drop=True)

gdp_growth.to_csv(
    DIAGNOSTICS_DIR / "gdp_growth_input_cleaned.csv",
    index=False,
)

print("GDP growth rows:", len(gdp_growth))
print("Countries:", gdp_growth["Country"].nunique())
print("Years:", gdp_growth["Year"].min(), "-", gdp_growth["Year"].max())

display(gdp_growth.head())

GDP growth rows: 1131
Countries: 44
Years: 2000 - 2025

,Country,country_name,Year,Value,source_file,source_family,concept,expected_unit
0,AUS,Australia,2000,2.0315,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change
1,AUS,Australia,2001,3.9498,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change
2,AUS,Australia,2002,3.0913,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change
3,AUS,Australia,2003,4.2189,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change
4,AUS,Australia,2004,3.1555,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change

In [4]:
# ------------------------------------------------------
# GDP GROWTH INPUT COVERAGE
# ------------------------------------------------------

gdp_growth_coverage_summary = (
    gdp_growth
    .groupby("Country")
    .agg(
        country_name=("country_name", "first"),
        years_available=("Year", "nunique"),
        min_year=("Year", "min"),
        max_year=("Year", "max"),
        min_growth=("Value", "min"),
        median_growth=("Value", "median"),
        max_growth=("Value", "max"),
    )
    .reset_index()
    .sort_values(["years_available", "Country"], ascending=[False, True])
)

gdp_growth_coverage_summary.to_csv(
    DIAGNOSTICS_DIR / "gdp_growth_country_coverage_summary.csv",
    index=False,
)

display(gdp_growth_coverage_summary.head(80))

,Country,country_name,years_available,min_year,max_year,min_growth,median_growth,max_growth
0,AUS,Australia,26,2000,2025,-0.1335,2.6278,4.2530
1,AUT,Austria,26,2000,2025,-6.3183,1.6197,5.3310
2,BEL,Belgium,26,2000,2025,-4.7930,1.6341,6.2545
4,CAN,Canada,26,2000,2025,-5.0382,2.1879,5.9505
5,CHE,Switzerland,26,2000,2025,-2.2553,1.7142,6.1762
6,CHL,Chile,26,2000,2025,-6.1397,3.2557,11.3374
8,COL,Colombia,26,2000,2025,-7.1859,3.2352,10.8012
10,CZE,Czechia,26,2000,2025,-5.3049,2.7725,6.6232
11,DEU,Germany,26,2000,2025,-5.5446,1.1489,4.1346
12,DNK,Denmark,26,2000,2025,-4.9745,1.4878,6.5003
13,ESP,Spain,26,2000,2025,-10.9401,2.8605,6.6831
14,EST,Estonia,26,2000,2025,-14.6302,3.6859,10.0876
15,FIN,Finland,26,2000,2025,-8.0760,1.5185,5.7537
16,FRA,France,26,2000,2025,-7.4406,1.6394,6.8823
17,GBR,United Kingdom,26,2000,2025,-10.0479,2.1651,8.5431
18,GRC,Greece,26,2000,2025,-9.8768,2.0689,8.6545
19,HUN,Hungary,26,2000,2025,-6.7402,3.7969,7.2229
20,IDN,Indonesia,26,2000,2025,-2.0655,5.0410,6.3776
22,IRL,Ireland,26,2000,2025,-5.0958,5.3080,24.6240
23,ISL,Iceland,26,2000,2025,-8.3215,3.5410,8.8573
24,ISR,Israel,26,2000,2025,-1.8024,3.8857,9.3353
25,ITA,Italy,26,2000,2025,-8.8682,0.8048,8.9311
26,JPN,Japan,26,2000,2025,-5.9359,1.2624,4.1365
27,KOR,"Korea, Republic of",26,2000,2025,-0.7002,3.1954,9.2019
28,LTU,Lithuania,26,2000,2025,-14.8386,4.2149,11.0779
29,LUX,Luxembourg,26,2000,2025,-3.2390,2.5509,8.0985
30,LVA,Latvia,26,2000,2025,-16.0400,3.2176,12.8250
31,MEX,Mexico,26,2000,2025,-8.3540,2.0250,6.0485
32,NLD,Netherlands,26,2000,2025,-3.8680,2.0251,6.2768
33,NOR,Norway,26,2000,2025,-1.6133,1.4636,4.3302
34,NZL,New Zealand,26,2000,2025,-1.4608,2.9302,5.0380
35,POL,Poland,26,2000,2025,-2.0356,3.7762,6.9272
36,PRT,Portugal,26,2000,2025,-8.2046,1.7632,6.9858
38,SVK,Slovakia,26,2000,2025,-5.5053,2.7913,10.8186
39,SVN,Slovenia,26,2000,2025,-7.5906,2.9316,8.4169
40,SWE,Sweden,26,2000,2025,-4.2556,2.0607,5.7508
41,TUR,Türkiye,26,2000,2025,-5.4594,5.2747,11.8111
42,USA,United States,26,2000,2025,-2.5765,2.5240,6.1520
43,ZAF,South Africa,26,2000,2025,-6.1689,2.4408,5.6038
9,CRI,Costa Rica,25,2000,2024,-4.2734,4.2043,8.2151
3,BRA,Brazil,24,2000,2023,-3.5458,3.0108,7.5282
7,CHN,China,24,2000,2023,2.0849,8.3921,14.2308
21,IND,India,24,2000,2023,-5.7777,7.5098,10.2600
37,RUS,Russian Federation,20,2000,2019,-7.8209,4.3840,10.0457

In [5]:
# ------------------------------------------------------
# RECOVERY CONSTRUCTION FUNCTIONS
# ------------------------------------------------------

def build_country_growth_map(country_df):
    country_df = country_df.sort_values("Year").copy()
    return dict(zip(country_df["Year"].astype(int), country_df["Value"].astype(float)))


def determine_first_negative_year(growth_by_year, shock_window_years):
    available_shock_values = {
        year: growth_by_year.get(year, np.nan)
        for year in shock_window_years
        if year in growth_by_year
    }

    if len(available_shock_values) == 0:
        return None, available_shock_values, "no_shock_window_data"

    negative_years = [
        year
        for year in sorted(available_shock_values)
        if pd.notna(available_shock_values[year]) and available_shock_values[year] < 0
    ]

    if len(negative_years) == 0:
        return None, available_shock_values, "no_negative_growth_in_shock_window"

    return negative_years[0], available_shock_values, "negative_growth_found"


def compute_recovery_for_country(country, country_name, country_df, config):
    shock_id = config["shock_id"]
    recovery_column = config["recovery_column"]
    shock_window_years = config["shock_window_years"]
    not_recovered_value = config["not_recovered_value"]

    growth_by_year = build_country_growth_map(country_df)

    first_negative_year, shock_window_values, shock_detection_status = determine_first_negative_year(
        growth_by_year,
        shock_window_years,
    )

    base_summary = {
        "Country": country,
        "country_name": country_name,
        "shock_id": shock_id,
        "recovery_column": recovery_column,
        "shock_window_years": ",".join(map(str, shock_window_years)),
        "shock_window_values": "; ".join(
            f"{year}:{growth_by_year.get(year, np.nan):.6g}"
            for year in shock_window_years
            if year in growth_by_year and pd.notna(growth_by_year.get(year))
        ),
        "shock_detection_status": shock_detection_status,
        "first_negative_growth_year": first_negative_year,
        "baseline_year": np.nan,
        "baseline_available_in_growth_file": False,
        "recovery_year": np.nan,
        "recovery_status": np.nan,
        "recovery_value": np.nan,
        "years_from_baseline_to_recovery": np.nan,
        "years_after_first_negative_to_recovery": np.nan,
        "path_stopped_due_to_missing_year": np.nan,
        "last_index_year": np.nan,
        "last_index_value": np.nan,
    }

    index_path_rows = []

    if shock_detection_status == "no_shock_window_data":
        base_summary["recovery_status"] = "excluded_no_shock_window_data"
        return base_summary, index_path_rows

    if shock_detection_status == "no_negative_growth_in_shock_window":
        base_summary["recovery_status"] = "no_negative_growth_in_shock_window"
        base_summary["recovery_value"] = 0
        base_summary["years_from_baseline_to_recovery"] = 0
        base_summary["years_after_first_negative_to_recovery"] = 0
        return base_summary, index_path_rows

    baseline_year = first_negative_year - 1
    base_summary["baseline_year"] = baseline_year
    base_summary["baseline_available_in_growth_file"] = baseline_year in growth_by_year

    # Create a real-GDP index path starting at 100 in the dynamic baseline year.
    current_index = 100.0

    index_path_rows.append({
        "Country": country,
        "country_name": country_name,
        "shock_id": shock_id,
        "Year": baseline_year,
        "gdp_growth": np.nan,
        "gdp_index_dynamic_baseline_100": current_index,
        "is_baseline_year": True,
        "first_negative_growth_year": first_negative_year,
        "baseline_year": baseline_year,
    })

    recovery_year = None
    missing_year_that_stopped_path = None

    max_observed_year = int(country_df["Year"].max())

    for year in range(baseline_year + 1, max_observed_year + 1):
        if year not in growth_by_year or pd.isna(growth_by_year.get(year)):
            missing_year_that_stopped_path = year
            break

        growth = float(growth_by_year[year])
        current_index = current_index * (1 + growth / 100.0)

        index_path_rows.append({
            "Country": country,
            "country_name": country_name,
            "shock_id": shock_id,
            "Year": year,
            "gdp_growth": growth,
            "gdp_index_dynamic_baseline_100": current_index,
            "is_baseline_year": False,
            "first_negative_growth_year": first_negative_year,
            "baseline_year": baseline_year,
        })

        if year >= first_negative_year and current_index >= 100.0:
            recovery_year = year
            break

    base_summary["path_stopped_due_to_missing_year"] = missing_year_that_stopped_path

    if index_path_rows:
        base_summary["last_index_year"] = index_path_rows[-1]["Year"]
        base_summary["last_index_value"] = index_path_rows[-1]["gdp_index_dynamic_baseline_100"]

    if recovery_year is not None:
        years_from_baseline = recovery_year - baseline_year
        years_after_first_negative = recovery_year - first_negative_year

        base_summary["recovery_year"] = recovery_year
        base_summary["recovery_status"] = "recovered"
        base_summary["years_from_baseline_to_recovery"] = years_from_baseline
        base_summary["years_after_first_negative_to_recovery"] = years_after_first_negative

        if FINAL_RECOVERY_TIME_DEFINITION == "years_after_first_negative_growth_year":
            base_summary["recovery_value"] = years_after_first_negative
        elif FINAL_RECOVERY_TIME_DEFINITION == "years_from_baseline_year":
            base_summary["recovery_value"] = years_from_baseline
        else:
            raise ValueError(f"Unknown recovery time definition: {FINAL_RECOVERY_TIME_DEFINITION}")

    else:
        if missing_year_that_stopped_path is not None:
            base_summary["recovery_status"] = "insufficient_growth_path_missing_year_before_recovery"
            base_summary["recovery_value"] = np.nan
        else:
            base_summary["recovery_status"] = "not_recovered_by_available_data"
            base_summary["recovery_value"] = not_recovered_value

    return base_summary, index_path_rows

In [6]:
# ------------------------------------------------------
# RUN RECOVERY CONSTRUCTION
# ------------------------------------------------------

summary_rows = []
index_path_rows = []

for country, country_df in gdp_growth.groupby("Country"):
    country_df = country_df.sort_values("Year").copy()
    country_name = country_df["country_name"].dropna().iloc[0] if country_df["country_name"].notna().any() else country

    for config in SHOCK_CONFIGS:
        summary, path_rows = compute_recovery_for_country(
            country=country,
            country_name=country_name,
            country_df=country_df,
            config=config,
        )

        summary_rows.append(summary)
        index_path_rows.extend(path_rows)

recovery_long = pd.DataFrame(summary_rows)
recovery_index_paths = pd.DataFrame(index_path_rows)

recovery_long.to_csv(
    PROCESSED_DIR / "country_recovery_audit_dynamic_baseline_long.csv",
    index=False,
)

recovery_long.to_csv(
    DIAGNOSTICS_DIR / "country_recovery_audit_dynamic_baseline_long.csv",
    index=False,
)

recovery_index_paths.to_csv(
    PROCESSED_DIR / "country_recovery_index_paths_dynamic_baseline.csv",
    index=False,
)

recovery_index_paths.to_csv(
    DIAGNOSTICS_DIR / "country_recovery_index_paths_dynamic_baseline.csv",
    index=False,
)

print("Recovery long rows:", len(recovery_long))
print("Index path rows:", len(recovery_index_paths))

display(recovery_long.head(80))

Recovery long rows: 88
Index path rows: 355

,Country,country_name,shock_id,recovery_column,shock_window_years,shock_window_values,shock_detection_status,first_negative_growth_year,baseline_year,baseline_available_in_growth_file,recovery_year,recovery_status,recovery_value,years_from_baseline_to_recovery,years_after_first_negative_to_recovery,path_stopped_due_to_missing_year,last_index_year,last_index_value
0,AUS,Australia,2007,Recovery_2007,"2008,2009",2008:1.95485; 2009:2.21005,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
1,AUS,Australia,2019,Recovery_2019,"2020,2021",2020:2.00695; 2021:4.25305,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
2,AUT,Austria,2007,Recovery_2007,"2008,2009",2008:1.45331; 2009:-3.58626,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,101.0314
3,AUT,Austria,2019,Recovery_2019,"2020,2021",2020:-6.31826; 2021:4.92309,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,103.5338
4,BEL,Belgium,2007,Recovery_2007,"2008,2009",2008:0.446905; 2009:-1.90644,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,100.7522
5,BEL,Belgium,2019,Recovery_2019,"2020,2021",2020:-4.79298; 2021:6.25446,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,101.1617
6,BRA,Brazil,2007,Recovery_2007,"2008,2009",2008:5.0942; 2009:-0.125812,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,107.3929
7,BRA,Brazil,2019,Recovery_2019,"2020,2021",2020:-3.27676; 2021:4.7626,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,101.3298
8,CAN,Canada,2007,Recovery_2007,"2008,2009",2008:0.995406; 2009:-2.91509,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,100.0856
9,CAN,Canada,2019,Recovery_2019,"2020,2021",2020:-5.03823; 2021:5.95053,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,100.6125
10,CHE,Switzerland,2007,Recovery_2007,"2008,2009",2008:2.5316; 2009:-1.93491,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,101.2626
11,CHE,Switzerland,2019,Recovery_2019,"2020,2021",2020:-2.25526; 2021:6.17623,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.7817
12,CHL,Chile,2007,Recovery_2007,"2008,2009",2008:3.78939; 2009:-1.11804,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,104.6682
13,CHL,Chile,2019,Recovery_2019,"2020,2021",2020:-6.1397; 2021:11.3374,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,104.5016
14,CHN,China,2007,Recovery_2007,"2008,2009",2008:9.65066; 2009:9.39874,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
15,CHN,China,2019,Recovery_2019,"2020,2021",2020:2.08485; 2021:8.44852,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
16,COL,Colombia,2007,Recovery_2007,"2008,2009",2008:3.28345; 2009:1.13965,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
17,COL,Colombia,2019,Recovery_2019,"2020,2021",2020:-7.18591; 2021:10.8012,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,102.8391
18,CRI,Costa Rica,2007,Recovery_2007,"2008,2009",2008:4.73817; 2009:-0.873456,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,104.4401
19,CRI,Costa Rica,2019,Recovery_2019,"2020,2021",2020:-4.27335; 2021:7.93576,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.3233
20,CZE,Czechia,2007,Recovery_2007,"2008,2009",2008:2.61227; 2009:-4.79832,negative_growth_found,2009.0000,2008.0000,True,2014.0000,recovered,5.0000,6.0000,5.0000,NaN,2014.0000,100.9272
21,CZE,Czechia,2019,Recovery_2019,"2020,2021",2020:-5.30488; 2021:4.02902,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,101.3152
22,DEU,Germany,2007,Recovery_2007,"2008,2009",2008:0.887902; 2009:-5.54455,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,102.0572
23,DEU,Germany,2019,Recovery_2019,"2020,2021",2020:-4.13191; 2021:3.91,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,101.4188
24,DNK,Denmark,2007,Recovery_2007,"2008,2009",2008:-0.417178; 2009:-4.97448,negative_growth_found,2008.0000,2007.0000,True,2015.0000,recovered,7.0000,8.0000,7.0000,NaN,2015.0000,102.1042
25,DNK,Denmark,2019,Recovery_2019,"2020,2021",2020:-1.78011; 2021:6.50025,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,104.6044
26,ESP,Spain,2007,Recovery_2007,"2008,2009",2008:0.767166; 2009:-3.76813,negative_growth_found,2009.0000,2008.0000,True,2017.0000,recovered,8.0000,9.0000,8.0000,NaN,2017.0000,102.5157
27,ESP,Spain,2019,Recovery_2019,"2020,2021",2020:-10.9401; 2021:6.68314,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,101.0645
28,EST,Estonia,2007,Recovery_2007,"2008,2009",2008:-5.12531; 2009:-14.6302,negative_growth_found,2008.0000,2007.0000,True,2016.0000,recovered,8.0000,9.0000,8.0000,NaN,2016.0000,102.1799
29,EST,Estonia,2019,Recovery_2019,"2020,2021",2020:-2.88381; 2021:8.25488,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,105.1330
30,FIN,Finland,2007,Recovery_2007,"2008,2009",2008:0.784431; 2009:-8.07603,negative_growth_found,2009.0000,2008.0000,True,2017.0000,recovered,8.0000,9.0000,8.0000,NaN,2017.0000,100.3175
31,FIN,Finland,2019,Recovery_2019,"2020,2021",2020:-2.49104; 2021:2.67635,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,100.1186
32,FRA,France,2007,Recovery_2007,"2008,2009",2008:0.380171; 2009:-2.82455,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,101.5354
33,FRA,France,2019,Recovery_2019,"2020,2021",2020:-7.44065; 2021:6.88234,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,101.6173
34,GBR,United Kingdom,2007,Recovery_2007,"2008,2009",2008:-0.0494117; 2009:-4.58741,negative_growth_found,2008.0000,2007.0000,True,2013.0000,recovered,5.0000,6.0000,5.0000,NaN,2013.0000,101.5706
35,GBR,United Kingdom,2019,Recovery_2019,"2020,2021",2020:-10.0479; 2021:8.54311,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,102.6648
36,GRC,Greece,2007,Recovery_2007,"2008,2009",2008:0.0574739; 2009:-4.11928,negative_growth_found,2009.0000,2008.0000,True,NaN,not_recovered_by_available_data,20.0000,NaN,NaN,NaN,2025.0000,86.1397
37,GRC,Greece,2019,Recovery_2019,"2020,2021",2020:-9.19623; 2021:8.6545,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,104.1105
38,HUN,Hungary,2007,Recovery_2007,"2008,2009",2008:0.993437; 2009:-6.74017,negative_growth_found,2009.0000,2008.0000,True,2014.0000,recovered,5.0000,6.0000,5.0000,NaN,2014.0000,100.8931
39,HUN,Hungary,2019,Recovery_2019,"2020,2021",2020:-4.33873; 2021:7.22292,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,102.5708
40,IDN,Indonesia,2007,Recovery_2007,"2008,2009",2008:6.0137; 2009:4.70177,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
41,IDN,Indonesia,2019,Recovery_2019,"2020,2021",2020:-2.06551; 2021:3.70289,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,101.5609
42,IND,India,2007,Recovery_2007,"2008,2009",2008:3.89096; 2009:8.47979,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
43,IND,India,2019,Recovery_2019,"2020,2021",2020:-5.77772; 2021:9.68959,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.3520
44,IRL,Ireland,2007,Recovery_2007,"2008,2009",2008:-4.48407; 2009:-5.09578,negative_growth_found,2008.0000,2007.0000,True,2014.0000,recovered,6.0000,7.0000,6.0000,NaN,2014.0000,104.2702
45,IRL,Ireland,2019,Recovery_2019,"2020,2021",2020:7.1537; 2021:16.2582,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
46,ISL,Iceland,2007,Recovery_2007,"2008,2009",2008:1.69961; 2009:-8.32146,negative_growth_found,2009.0000,2008.0000,True,2015.0000,recovered,6.0000,7.0000,6.0000,NaN,2015.0000,100.7295
47,ISL,Iceland,2019,Recovery_2019,"2020,2021",2020:-6.64588; 2021:5.18057,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,106.8874
48,ISR,Israel,2007,Recovery_2007,"2008,2009",2008:3.21588; 2009:1.22016,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
49,ISR,Israel,2019,Recovery_2019,"2020,2021",2020:-1.80243; 2021:9.33535,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,107.3647
50,ITA,Italy,2007,Recovery_2007,"2008,2009",2008:-1.02314; 2009:-5.30515,negative_growth_found,2008.0000,2007.0000,True,2023.0000,recovered,15.0000,16.0000,15.0000,NaN,2023.0000,100.5696
51,ITA,Italy,2019,Recovery_2019,"2020,2021",2020:-8.86822; 2021:8.93106,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,104.0568
52,JPN,Japan,2007,Recovery_2007,"2008,2009",2008:-1.16662; 2009:-5.93594,negative_growth_found,2008.0000,2007.0000,True,2013.0000,recovered,5.0000,6.0000,5.0000,NaN,2013.0000,100.1730
53,JPN,Japan,2019,Recovery_2019,"2020,2021",2020:-4.28328; 2021:3.5642,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,100.4483
54,KOR,"Korea, Republic of",2007,Recovery_2007,"2008,2009",2008:3.0044; 2009:0.819862,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
55,KOR,"Korea, Republic of",2019,Recovery_2019,"2020,2021",2020:-0.700242; 2021:4.61297,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.8804
56,LTU,Lithuania,2007,Recovery_2007,"2008,2009",2008:2.59946; 2009:-14.8386,negative_growth_found,2009.0000,2008.0000,True,2014.0000,recovered,5.0000,6.0000,5.0000,NaN,2014.0000,102.4861
57,LTU,Lithuania,2019,Recovery_2019,"2020,2021",2020:0.042815; 2021:6.39482,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
58,LUX,Luxembourg,2007,Recovery_2007,"2008,2009",2008:-0.302274; 2009:-3.23895,negative_growth_found,2008.0000,2007.0000,True,2010.0000,recovered,2.0000,3.0000,2.0000,NaN,2010.0000,100.0962
59,LUX,Luxembourg,2019,Recovery_2019,"2020,2021",2020:-0.510052; 2021:6.92973,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,106.3843
60,LVA,Latvia,2007,Recovery_2007,"2008,2009",2008:-3.38872; 2009:-16.04,negative_growth_found,2008.0000,2007.0000,True,2018.0000,recovered,10.0000,11.0000,10.0000,NaN,2018.0000,103.3802
61,LVA,Latvia,2019,Recovery_2019,"2020,2021",2020:-3.46923; 2021:6.94254,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.2325
62,MEX,Mexico,2007,Recovery_2007,"2008,2009",2008:0.943332; 2009:-6.29525,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,101.7508
63,MEX,Mexico,2019,Recovery_2019,"2020,2021",2020:-8.35403; 2021:6.04848,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,100.7946
64,NLD,Netherlands,2007,Recovery_2007,"2008,2009",2008:2.11675; 2009:-3.66528,negative_growth_found,2009.0000,2008.0000,True,2015.0000,recovered,6.0000,7.0000,6.0000,NaN,2015.0000,102.0402
65,NLD,Netherlands,2019,Recovery_2019,"2020,2021",2020:-3.868; 2021:6.27684,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,102.1661
66,NOR,Norway,2007,Recovery_2007,"2008,2009",2008:0.822806; 2009:-1.61327,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,100.7518
67,NOR,Norway,2019,Recovery_2019,"2020,2021",2020:-1.36056; 2021:4.14315,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,102.7262
68,NZL,New Zealand,2007,Recovery_2007,"2008,2009",2008:-1.46081; 2009:2.07592,negative_growth_found,2008.0000,2007.0000,True,2009.0000,recovered,1.0000,2.0000,1.0000,NaN,2009.0000,100.5848
69,NZL,New Zealand,2019,Recovery_2019,"2020,2021",2020:0.20137; 2021:4.38121,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
70,POL,Poland,2007,Recovery_2007,"2008,2009",2008:4.38377; 2009:2.61513,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,no_negative_growth_in_shock_window,0.0000,0.0000,0.0000,NaN,NaN,NaN
71,POL,Poland,2019,Recovery_2019,"2020,2021",2020:-2.03557; 2021:6.92718,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,104.7506
72,PRT,Portugal,2007,Recovery_2007,"2008,2009",2008:0.319247; 2009:-3.12208,negative_growth_found,2009.0000,2008.0000,True,2018.0000,recovered,9.0000,10.0000,9.0000,NaN,2018.0000,102.1868
73,PRT,Portugal,2019,Recovery_2019,"2020,2021",2020:-8.20463; 2021:5.55876,negative_growth_found,2020.0000,2019.0000,True,2022.0000,recovered,2.0000,3.0000,2.0000,NaN,2022.0000,103.6672
74,RUS,Russian Federation,2007,Recovery_2007,"2008,2009",2008:5.24795; 2009:-7.82088,negative_growth_found,2009.0000,2008.0000,True,2011.0000,recovered,2.0000,3.0000,2.0000,NaN,2011.0000,100.4383
75,RUS,Russian Federation,2019,Recovery_2019,"2020,2021",,no_shock_window_data,NaN,NaN,False,NaN,excluded_no_shock_window_data,NaN,NaN,NaN,NaN,NaN,NaN
76,SVK,Slovakia,2007,Recovery_2007,"2008,2009",2008:5.36338; 2009:-5.50534,negative_growth_found,2009.0000,2008.0000,True,2010.0000,recovered,1.0000,2.0000,1.0000,NaN,2010.0000,100.9114
77,SVK,Slovakia,2019,Recovery_2019,"2020,2021",2020:-2.58551; 2021:5.65586,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,102.9241
78,SVN,Slovenia,2007,Recovery_2007,"2008,2009",2008:3.37224; 2009:-7.59059,negative_growth_found,2009.0000,2008.0000,True,2017.0000,recovered,8.0000,9.0000,8.0000,NaN,2017.0000,103.2557
79,SVN,Slovenia,2019,Recovery_2019,"2020,2021",2020:-4.085; 2021:8.41686,negative_growth_found,2020.0000,2019.0000,True,2021.0000,recovered,1.0000,2.0000,1.0000,NaN,2021.0000,103.9880

In [7]:
# ------------------------------------------------------
# CREATE WIDE COUNTRY RECOVERY SUMMARY
# ------------------------------------------------------

summary_base = (
    recovery_long
    .pivot_table(
        index=["Country", "country_name"],
        columns="recovery_column",
        values="recovery_value",
        aggfunc="first",
    )
    .reset_index()
)

# Add status and audit fields for each shock.
audit_fields = [
    "recovery_status",
    "shock_detection_status",
    "first_negative_growth_year",
    "baseline_year",
    "baseline_available_in_growth_file",
    "recovery_year",
    "years_from_baseline_to_recovery",
    "years_after_first_negative_to_recovery",
    "path_stopped_due_to_missing_year",
    "last_index_year",
    "last_index_value",
]

wide = summary_base.copy()

for config in SHOCK_CONFIGS:
    recovery_col = config["recovery_column"]
    shock_subset = recovery_long[recovery_long["recovery_column"] == recovery_col].copy()

    for field in audit_fields:
        temp = (
            shock_subset
            .pivot_table(
                index=["Country", "country_name"],
                values=field,
                aggfunc="first",
            )
            .reset_index()
            .rename(columns={field: f"{recovery_col}_{field}"})
        )

        wide = wide.merge(temp, on=["Country", "country_name"], how="left")

# Ensure expected recovery columns exist even if pivot omitted them.
for config in SHOCK_CONFIGS:
    recovery_col = config["recovery_column"]
    if recovery_col not in wide.columns:
        wide[recovery_col] = np.nan

# Put main recovery columns near the front.
front_cols = ["Country", "country_name"] + [config["recovery_column"] for config in SHOCK_CONFIGS]
other_cols = [col for col in wide.columns if col not in front_cols]

country_recovery_summary = wide[front_cols + other_cols].copy()

country_recovery_summary = country_recovery_summary.sort_values("Country").reset_index(drop=True)

country_recovery_summary.to_csv(
    PROCESSED_DIR / "country_recovery_summary_dynamic_baseline_2007_2019.csv",
    index=False,
)

country_recovery_summary.to_csv(
    DIAGNOSTICS_DIR / "country_recovery_summary_dynamic_baseline_2007_2019.csv",
    index=False,
)

display(country_recovery_summary.head(80))

,Country,country_name,Recovery_2007,Recovery_2019,Recovery_2007_recovery_status,Recovery_2007_shock_detection_status,Recovery_2007_first_negative_growth_year,Recovery_2007_baseline_year,Recovery_2007_baseline_available_in_growth_file,Recovery_2007_recovery_year,Recovery_2007_years_from_baseline_to_recovery,Recovery_2007_years_after_first_negative_to_recovery,Recovery_2007_last_index_year,Recovery_2007_last_index_value,Recovery_2019_recovery_status,Recovery_2019_shock_detection_status,Recovery_2019_first_negative_growth_year,Recovery_2019_baseline_year,Recovery_2019_baseline_available_in_growth_file,Recovery_2019_recovery_year,Recovery_2019_years_from_baseline_to_recovery,Recovery_2019_years_after_first_negative_to_recovery,Recovery_2019_last_index_year,Recovery_2019_last_index_value
0,AUS,Australia,0.0000,0.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
1,AUT,Austria,2.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,101.0314,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,103.5338
2,BEL,Belgium,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.7522,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,101.1617
3,BRA,Brazil,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,107.3929,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,101.3298
4,CAN,Canada,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.0856,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,100.6125
5,CHE,Switzerland,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,101.2626,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.7817
6,CHL,Chile,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,104.6682,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,104.5016
7,CHN,China,0.0000,0.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
8,COL,Colombia,0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,102.8391
9,CRI,Costa Rica,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,104.4401,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.3233
10,CZE,Czechia,5.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2014.0000,6.0000,5.0000,2014.0000,100.9272,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,101.3152
11,DEU,Germany,2.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,102.0572,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,101.4188
12,DNK,Denmark,7.0000,1.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2015.0000,8.0000,7.0000,2015.0000,102.1042,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,104.6044
13,ESP,Spain,8.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2017.0000,9.0000,8.0000,2017.0000,102.5157,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,101.0645
14,EST,Estonia,8.0000,1.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2016.0000,9.0000,8.0000,2016.0000,102.1799,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,105.1330
15,FIN,Finland,8.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2017.0000,9.0000,8.0000,2017.0000,100.3175,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,100.1186
16,FRA,France,2.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,101.5354,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,101.6173
17,GBR,United Kingdom,5.0000,2.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2013.0000,6.0000,5.0000,2013.0000,101.5706,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,102.6648
18,GRC,Greece,20.0000,2.0000,not_recovered_by_available_data,negative_growth_found,2009.0000,2008.0000,True,NaN,NaN,NaN,2025.0000,86.1397,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,104.1105
19,HUN,Hungary,5.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2014.0000,6.0000,5.0000,2014.0000,100.8931,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,102.5708
20,IDN,Indonesia,0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,101.5609
21,IND,India,0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.3520
22,IRL,Ireland,6.0000,0.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2014.0000,7.0000,6.0000,2014.0000,104.2702,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
23,ISL,Iceland,6.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2015.0000,7.0000,6.0000,2015.0000,100.7295,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,106.8874
24,ISR,Israel,0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,107.3647
25,ITA,Italy,15.0000,2.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2023.0000,16.0000,15.0000,2023.0000,100.5696,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,104.0568
26,JPN,Japan,5.0000,2.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2013.0000,6.0000,5.0000,2013.0000,100.1730,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,100.4483
27,KOR,"Korea, Republic of",0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.8804
28,LTU,Lithuania,5.0000,0.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2014.0000,6.0000,5.0000,2014.0000,102.4861,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
29,LUX,Luxembourg,2.0000,1.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2010.0000,3.0000,2.0000,2010.0000,100.0962,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,106.3843
30,LVA,Latvia,10.0000,1.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2018.0000,11.0000,10.0000,2018.0000,103.3802,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.2325
31,MEX,Mexico,2.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,101.7508,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,100.7946
32,NLD,Netherlands,6.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2015.0000,7.0000,6.0000,2015.0000,102.0402,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,102.1661
33,NOR,Norway,2.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,100.7518,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,102.7262
34,NZL,New Zealand,1.0000,0.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2009.0000,2.0000,1.0000,2009.0000,100.5848,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
35,POL,Poland,0.0000,1.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,104.7506
36,PRT,Portugal,9.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2018.0000,10.0000,9.0000,2018.0000,102.1868,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,103.6672
37,RUS,Russian Federation,2.0000,NaN,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,100.4383,excluded_no_shock_window_data,no_shock_window_data,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
38,SVK,Slovakia,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.9114,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,102.9241
39,SVN,Slovenia,8.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2017.0000,9.0000,8.0000,2017.0000,103.2557,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.9880
40,SWE,Sweden,2.0000,1.0000,recovered,negative_growth_found,2008.0000,2007.0000,True,2010.0000,3.0000,2.0000,2010.0000,100.3158,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.1910
41,TUR,Türkiye,1.0000,0.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,103.2424,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
42,USA,United States,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.0493,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,103.9426
43,ZAF,South Africa,1.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,101.4549,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,100.4150

In [8]:
# ------------------------------------------------------
# STATUS SUMMARIES
# ------------------------------------------------------

country_recovery_status_summary = (
    recovery_long
    .groupby(["shock_id", "recovery_column", "recovery_status"])
    .agg(
        countries=("Country", "nunique"),
        min_recovery_value=("recovery_value", "min"),
        median_recovery_value=("recovery_value", "median"),
        max_recovery_value=("recovery_value", "max"),
    )
    .reset_index()
    .sort_values(["shock_id", "countries"], ascending=[True, False])
)

country_recovery_status_summary.to_csv(
    PROCESSED_DIR / "country_recovery_status_summary_dynamic_baseline.csv",
    index=False,
)

country_recovery_status_summary.to_csv(
    DIAGNOSTICS_DIR / "country_recovery_status_summary_dynamic_baseline.csv",
    index=False,
)

shock_detection_summary = (
    recovery_long
    .groupby(["shock_id", "shock_detection_status"])
    .agg(countries=("Country", "nunique"))
    .reset_index()
    .sort_values(["shock_id", "countries"], ascending=[True, False])
)

shock_detection_summary.to_csv(
    DIAGNOSTICS_DIR / "shock_detection_status_summary.csv",
    index=False,
)

display(country_recovery_status_summary)
display(shock_detection_summary)

,shock_id,recovery_column,recovery_status,countries,min_recovery_value,median_recovery_value,max_recovery_value
2,2007,Recovery_2007,recovered,35,1.0000,2.0000,15.0000
0,2007,Recovery_2007,no_negative_growth_in_shock_window,8,0.0000,0.0000,0.0000
1,2007,Recovery_2007,not_recovered_by_available_data,1,20.0000,20.0000,20.0000
5,2019,Recovery_2019,recovered,37,1.0000,1.0000,2.0000
4,2019,Recovery_2019,no_negative_growth_in_shock_window,6,0.0000,0.0000,0.0000
3,2019,Recovery_2019,excluded_no_shock_window_data,1,NaN,NaN,NaN

  shock_id              shock_detection_status  countries
0     2007               negative_growth_found         36
1     2007  no_negative_growth_in_shock_window          8
2     2019               negative_growth_found         37
3     2019  no_negative_growth_in_shock_window          6
4     2019                no_shock_window_data          1

In [9]:
# ------------------------------------------------------
# EXCLUDED / PROBLEM CASES
# ------------------------------------------------------

problem_statuses = {
    "excluded_no_shock_window_data",
    "insufficient_growth_path_missing_year_before_recovery",
}

recovery_problem_cases = recovery_long[
    recovery_long["recovery_status"].isin(problem_statuses)
].copy()

recovery_problem_cases.to_csv(
    DIAGNOSTICS_DIR / "recovery_problem_cases.csv",
    index=False,
)

not_recovered_cases = recovery_long[
    recovery_long["recovery_status"] == "not_recovered_by_available_data"
].copy()

not_recovered_cases.to_csv(
    DIAGNOSTICS_DIR / "not_recovered_by_available_data_cases.csv",
    index=False,
)

display(recovery_problem_cases)
display(not_recovered_cases.head(50))

,Country,country_name,shock_id,recovery_column,shock_window_years,shock_window_values,shock_detection_status,first_negative_growth_year,baseline_year,baseline_available_in_growth_file,recovery_year,recovery_status,recovery_value,years_from_baseline_to_recovery,years_after_first_negative_to_recovery,path_stopped_due_to_missing_year,last_index_year,last_index_value
75,RUS,Russian Federation,2019,Recovery_2019,"2020,2021",,no_shock_window_data,NaN,NaN,False,NaN,excluded_no_shock_window_data,NaN,NaN,NaN,NaN,NaN,NaN

,Country,country_name,shock_id,recovery_column,shock_window_years,shock_window_values,shock_detection_status,first_negative_growth_year,baseline_year,baseline_available_in_growth_file,recovery_year,recovery_status,recovery_value,years_from_baseline_to_recovery,years_after_first_negative_to_recovery,path_stopped_due_to_missing_year,last_index_year,last_index_value
36,GRC,Greece,2007,Recovery_2007,"2008,2009",2008:0.0574739; 2009:-4.11928,negative_growth_found,2009.0000,2008.0000,True,NaN,not_recovered_by_available_data,20.0000,NaN,NaN,NaN,2025.0000,86.1397

In [10]:
# ------------------------------------------------------
# ARGENTINA MANUAL VALIDATION SNAPSHOT
# ------------------------------------------------------
# ARG was mentioned as a useful manual validation case.

argentina_growth = gdp_growth[gdp_growth["Country"] == "ARG"].copy()
argentina_recovery_audit = recovery_long[recovery_long["Country"] == "ARG"].copy()
argentina_index_path = recovery_index_paths[recovery_index_paths["Country"] == "ARG"].copy()

argentina_growth.to_csv(
    DIAGNOSTICS_DIR / "argentina_gdp_growth_input.csv",
    index=False,
)

argentina_recovery_audit.to_csv(
    DIAGNOSTICS_DIR / "argentina_recovery_audit.csv",
    index=False,
)

argentina_index_path.to_csv(
    DIAGNOSTICS_DIR / "argentina_recovery_index_path.csv",
    index=False,
)

print("Argentina GDP growth input:")
display(argentina_growth)

print("Argentina recovery audit:")
display(argentina_recovery_audit)

print("Argentina index path:")
display(argentina_index_path)

Argentina GDP growth input:

Empty DataFrame
Columns: [Country, country_name, Year, Value, source_file, source_family, concept, expected_unit]
Index: []

Argentina recovery audit:

Empty DataFrame
Columns: [Country, country_name, shock_id, recovery_column, shock_window_years, shock_window_values, shock_detection_status, first_negative_growth_year, baseline_year, baseline_available_in_growth_file, recovery_year, recovery_status, recovery_value, years_from_baseline_to_recovery, years_after_first_negative_to_recovery, path_stopped_due_to_missing_year, last_index_year, last_index_value]
Index: []

Argentina index path:

Empty DataFrame
Columns: [Country, country_name, shock_id, Year, gdp_growth, gdp_index_dynamic_baseline_100, is_baseline_year, first_negative_growth_year, baseline_year]
Index: []

In [11]:
# ------------------------------------------------------
# OUTPUT DATA DICTIONARY
# ------------------------------------------------------

data_dictionary = pd.DataFrame([
    {
        "file": "country_recovery_summary_dynamic_baseline_2007_2019.csv",
        "column": "Recovery_2007",
        "description": "Final recovery value for the 2007 shock window. 0 = no negative growth in shock window; 20 = not recovered by available data; otherwise years after first negative GDP growth year until the GDP index returns to dynamic baseline 100.",
    },
    {
        "file": "country_recovery_summary_dynamic_baseline_2007_2019.csv",
        "column": "Recovery_2019",
        "description": "Final recovery value for the 2019 shock window. 0 = no negative growth in shock window; 20 = not recovered by available data; otherwise years after first negative GDP growth year until the GDP index returns to dynamic baseline 100.",
    },
    {
        "file": "country_recovery_audit_dynamic_baseline_long.csv",
        "column": "first_negative_growth_year",
        "description": "First year with negative real GDP growth inside the configured shock window.",
    },
    {
        "file": "country_recovery_audit_dynamic_baseline_long.csv",
        "column": "baseline_year",
        "description": "Dynamic pre-shock baseline year, defined as first_negative_growth_year - 1.",
    },
    {
        "file": "country_recovery_index_paths_dynamic_baseline.csv",
        "column": "gdp_index_dynamic_baseline_100",
        "description": "Reconstructed GDP index from annual growth rates, set to 100 in the dynamic baseline year.",
    },
    {
        "file": "country_recovery_audit_dynamic_baseline_long.csv",
        "column": "years_from_baseline_to_recovery",
        "description": "Recovery year minus baseline year. Exported for transparency; not the default final Recovery_* value.",
    },
    {
        "file": "country_recovery_audit_dynamic_baseline_long.csv",
        "column": "years_after_first_negative_to_recovery",
        "description": "Recovery year minus first negative growth year. This is the default final Recovery_* value when a country recovers.",
    },
])

data_dictionary.to_csv(
    PROCESSED_DIR / "country_recovery_data_dictionary.csv",
    index=False,
)

data_dictionary.to_csv(
    DIAGNOSTICS_DIR / "country_recovery_data_dictionary.csv",
    index=False,
)

display(data_dictionary)

,file,column,description
0,country_recovery_summary_dynamic_baseline_2007...,Recovery_2007,Final recovery value for the 2007 shock window...
1,country_recovery_summary_dynamic_baseline_2007...,Recovery_2019,Final recovery value for the 2019 shock window...
2,country_recovery_audit_dynamic_baseline_long.csv,first_negative_growth_year,First year with negative real GDP growth insid...
3,country_recovery_audit_dynamic_baseline_long.csv,baseline_year,"Dynamic pre-shock baseline year, defined as fi..."
4,country_recovery_index_paths_dynamic_baseline.csv,gdp_index_dynamic_baseline_100,Reconstructed GDP index from annual growth rat...
5,country_recovery_audit_dynamic_baseline_long.csv,years_from_baseline_to_recovery,Recovery year minus baseline year. Exported fo...
6,country_recovery_audit_dynamic_baseline_long.csv,years_after_first_negative_to_recovery,Recovery year minus first negative growth year...

In [12]:
# ------------------------------------------------------
# CREATE RECOVERY AUDIT WORKBOOK
# ------------------------------------------------------

RECOVERY_AUDIT_XLSX = AUDIT_DIR / "02_GDP_Recovery_Dynamic_Baseline_Audit.xlsx"

audit_sources = [
    {
        "sheet_name": "01_recovery_summary",
        "description": "Final country-level wide recovery summary.",
        "path": PROCESSED_DIR / "country_recovery_summary_dynamic_baseline_2007_2019.csv",
    },
    {
        "sheet_name": "02_recovery_audit",
        "description": "Long-format recovery audit by country and shock.",
        "path": PROCESSED_DIR / "country_recovery_audit_dynamic_baseline_long.csv",
    },
    {
        "sheet_name": "03_status_summary",
        "description": "Recovery status summary by shock.",
        "path": PROCESSED_DIR / "country_recovery_status_summary_dynamic_baseline.csv",
    },
    {
        "sheet_name": "04_shock_detection",
        "description": "Shock detection status summary.",
        "path": DIAGNOSTICS_DIR / "shock_detection_status_summary.csv",
    },
    {
        "sheet_name": "05_problem_cases",
        "description": "Cases with no shock-window data or insufficient growth paths.",
        "path": DIAGNOSTICS_DIR / "recovery_problem_cases.csv",
    },
    {
        "sheet_name": "06_not_recovered",
        "description": "Countries not recovered by available data.",
        "path": DIAGNOSTICS_DIR / "not_recovered_by_available_data_cases.csv",
    },
    {
        "sheet_name": "07_gdp_coverage",
        "description": "GDP growth input coverage by country.",
        "path": DIAGNOSTICS_DIR / "gdp_growth_country_coverage_summary.csv",
    },
    {
        "sheet_name": "08_duplicates",
        "description": "GDP growth duplicate Country-Year check.",
        "path": DIAGNOSTICS_DIR / "gdp_growth_duplicate_country_year_check.csv",
    },
    {
        "sheet_name": "09_argentina_audit",
        "description": "Argentina manual validation recovery audit.",
        "path": DIAGNOSTICS_DIR / "argentina_recovery_audit.csv",
    },
    {
        "sheet_name": "10_data_dictionary",
        "description": "Recovery output data dictionary.",
        "path": PROCESSED_DIR / "country_recovery_data_dictionary.csv",
    },
]


def safe_sheet_name(name, used):
    cleaned = re.sub(r"[/\\*\[\]:?]", "_", str(name))[:31]
    base = cleaned
    i = 1

    while cleaned in used:
        suffix = f"_{i}"
        cleaned = base[:31 - len(suffix)] + suffix
        i += 1

    used.add(cleaned)
    return cleaned


def estimate_width(series, col_name, min_width=10, max_width=60):
    values = [str(col_name)] + series.dropna().astype(str).head(200).tolist()

    if not values:
        return min_width

    return max(min_width, min(max(len(v) for v in values) + 2, max_width))


used_sheets = set()

with pd.ExcelWriter(RECOVERY_AUDIT_XLSX, engine="xlsxwriter") as writer:
    workbook = writer.book

    title_fmt = workbook.add_format({
        "bold": True,
        "font_size": 15,
        "font_color": "white",
        "bg_color": "#1F4E78",
        "align": "left",
        "valign": "vcenter",
    })

    desc_fmt = workbook.add_format({
        "text_wrap": True,
        "font_size": 10,
        "font_color": "#333333",
        "valign": "top",
    })

    header_fmt = workbook.add_format({
        "bold": True,
        "font_color": "white",
        "bg_color": "#5B9BD5",
        "border": 1,
        "align": "center",
        "valign": "vcenter",
        "text_wrap": True,
    })

    index_rows = []

    for item in audit_sources:
        path = Path(item["path"])

        if path.exists():
            try:
                df_temp = pd.read_csv(path)
                rows = len(df_temp)
                cols = len(df_temp.columns)
            except Exception:
                rows = np.nan
                cols = np.nan
        else:
            rows = 0
            cols = 0

        index_rows.append({
            "Sheet": item["sheet_name"],
            "Rows": rows,
            "Columns": cols,
            "Description": item["description"],
            "Path": str(path),
        })

    index_df = pd.DataFrame(index_rows)
    index_df.to_excel(writer, sheet_name="00_INDEX", index=False, startrow=5)

    ws = writer.sheets["00_INDEX"]
    ws.merge_range(0, 0, 0, max(4, len(index_df.columns) - 1), "02 GDP Recovery Dynamic Baseline Audit", title_fmt)
    ws.merge_range(1, 0, 3, max(4, len(index_df.columns) - 1), "Audit workbook for GDP recovery outcome construction.", desc_fmt)

    for col_idx, col_name in enumerate(index_df.columns):
        ws.write(5, col_idx, col_name, header_fmt)
        ws.set_column(col_idx, col_idx, estimate_width(index_df[col_name], col_name))

    ws.autofilter(5, 0, 5 + len(index_df), len(index_df.columns) - 1)
    ws.freeze_panes(6, 0)

    for item in audit_sources:
        path = Path(item["path"])

        if path.exists():
            try:
                df_sheet = pd.read_csv(path)
            except Exception as e:
                df_sheet = pd.DataFrame({"message": [f"Could not read file: {e}"]})
        else:
            df_sheet = pd.DataFrame({"message": ["File not found."]})

        if df_sheet.empty:
            df_sheet = pd.DataFrame({"message": ["No rows in this table."]})

        sheet_name = safe_sheet_name(item["sheet_name"], used_sheets)

        df_sheet.to_excel(writer, sheet_name=sheet_name, index=False, startrow=4)

        ws = writer.sheets[sheet_name]
        max_col = max(4, len(df_sheet.columns) - 1)

        ws.merge_range(0, 0, 0, max_col, item["sheet_name"], title_fmt)
        ws.merge_range(1, 0, 3, max_col, item["description"], desc_fmt)

        for col_idx, col_name in enumerate(df_sheet.columns):
            ws.write(4, col_idx, col_name, header_fmt)
            ws.set_column(col_idx, col_idx, estimate_width(df_sheet[col_name], col_name))

        ws.autofilter(4, 0, 4 + len(df_sheet), len(df_sheet.columns) - 1)
        ws.freeze_panes(5, 0)

print("Recovery audit workbook created:")
print(RECOVERY_AUDIT_XLSX.resolve())

Recovery audit workbook created:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Audit\02_GDP_Recovery_Dynamic_Baseline_Audit.xlsx

In [13]:
# ------------------------------------------------------
# FINAL COMPLETION CHECK
# ------------------------------------------------------

print("02 GDP RECOVERY DYNAMIC BASELINE COMPLETE")
print("=" * 80)

print("\nInput file:")
print(INPUT_FILE.resolve())

print("\nProcessed folder:")
print(PROCESSED_DIR.resolve())

print("\nDiagnostics folder:")
print(DIAGNOSTICS_DIR.resolve())

print("\nAudit workbook:")
print(RECOVERY_AUDIT_XLSX.resolve())

print("\nMain outputs:")
main_outputs = [
    "country_recovery_summary_dynamic_baseline_2007_2019.csv",
    "country_recovery_audit_dynamic_baseline_long.csv",
    "country_recovery_index_paths_dynamic_baseline.csv",
    "country_recovery_status_summary_dynamic_baseline.csv",
    "country_recovery_data_dictionary.csv",
]

for file_name in main_outputs:
    path = PROCESSED_DIR / file_name
    status = "FOUND" if path.exists() else "MISSING"
    print(f"- {status}: {file_name}")

print("\nRecovery status summary:")
display(country_recovery_status_summary)

print("\nImportant notes:")
print("1. Recovery outcomes use GDP growth only.")
print("2. Dynamic baseline is selected from the first negative growth year in each shock window.")
print("3. No negative growth in the shock window is encoded as 0.")
print("4. Not recovered by available data is encoded as 20.")
print("5. The default recovered-country value is years after first negative GDP growth year.")
print("6. Recovery outputs are for validation/interpretation later, not POSet ordering.")

print("\nNext notebook:")
print("03_WGI_Governance_Compilation.ipynb")

02 GDP RECOVERY DYNAMIC BASELINE COMPLETE
================================================================================

Input file:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\00_Comparable_Raw_Files\Combined_Long\all_comparable_sources_long.csv

Processed folder:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Recovery

Diagnostics folder:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Diagnostics\02_GDP_Recovery_Dynamic_Baseline

Audit workbook:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Audit\02_GDP_Recovery_Dynamic_Baseline_Audit.xlsx

Main outputs:
- FOUND: country_recovery_summary_dynamic_baseline_2007_2019.csv
- FOUND: country_recovery_audit_dynamic_baseline_long.csv
- FOUND: country_recovery_index_paths_dynamic_baseline.csv
- FOUND: country_recovery_status_summary_dynamic_baseline.csv
- FOUND: country_recovery_data_dictionary.csv

Recovery status summary:

,shock_id,recovery_column,recovery_status,countries,min_recovery_value,median_recovery_value,max_recovery_value
2,2007,Recovery_2007,recovered,35,1.0000,2.0000,15.0000
0,2007,Recovery_2007,no_negative_growth_in_shock_window,8,0.0000,0.0000,0.0000
1,2007,Recovery_2007,not_recovered_by_available_data,1,20.0000,20.0000,20.0000
5,2019,Recovery_2019,recovered,37,1.0000,1.0000,2.0000
4,2019,Recovery_2019,no_negative_growth_in_shock_window,6,0.0000,0.0000,0.0000
3,2019,Recovery_2019,excluded_no_shock_window_data,1,NaN,NaN,NaN

Important notes:
1. Recovery outcomes use GDP growth only.
2. Dynamic baseline is selected from the first negative growth year in each shock window.
3. No negative growth in the shock window is encoded as 0.
4. Not recovered by available data is encoded as 20.
5. The default recovered-country value is years after first negative GDP growth year.
6. Recovery outputs are for validation/interpretation later, not POSet ordering.

Next notebook:
03_WGI_Governance_Compilation.ipynb