# 04 — Volatility Features

This notebook comes after:

`03_WGI_Governance_Compilation.ipynb`

Purpose:

Create pre-shock volatility and stability features from standardized macroeconomic variables.

Main idea:

A country with more stable pre-shock macroeconomic conditions may have stronger structural resilience capacity.

This notebook creates candidate features for two analysis windows:

- 2007 shock structural window: `2000–2007`
- 2019 shock structural window: `2012–2019`

Candidate volatility variables:

- GDP growth volatility
- Inflation volatility
- Unemployment volatility
- Productivity growth / level volatility, if available and meaningful

Preferred first feature for the project:

`gdp_growth_stability`

Important:

- This notebook uses only **pre-shock years**.
- It does **not** use post-shock years.
- It does **not** use the recovery outcome.
- It does **not** decide final POSet variables.
- It does **not** impute missing values.
- It creates both volatility measures and direction-aligned stability measures where higher = better.

In [1]:
# ------------------------------------------------------
# IMPORTS AND PATHS
# ------------------------------------------------------

from pathlib import Path
from datetime import datetime
import pandas as pd
import numpy as np
import re
import shutil
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", 250)
pd.set_option("display.max_rows", 200)
pd.set_option("display.float_format", "{:.4f}".format)

PROJECT_ROOT = Path.cwd()

INPUT_FILE = (
    PROJECT_ROOT
    / "Data"
    / "Processed"
    / "00_Comparable_Raw_Files"
    / "Combined_Long"
    / "all_comparable_sources_long.csv"
)

RECOVERY_FILE = (
    PROJECT_ROOT
    / "Data"
    / "Processed"
    / "Recovery"
    / "country_recovery_summary_dynamic_baseline_2007_2019.csv"
)

PROCESSED_DIR = PROJECT_ROOT / "Data" / "Processed" / "Volatility_Features"
DIAGNOSTICS_DIR = PROJECT_ROOT / "Data" / "Diagnostics" / "04_Volatility_Features"
AUDIT_DIR = PROJECT_ROOT / "Data" / "Audit"

RUN_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
RUN_TIMESTAMP = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

CLEAR_PREVIOUS_OUTPUTS = True

if CLEAR_PREVIOUS_OUTPUTS:
    for folder in [PROCESSED_DIR, DIAGNOSTICS_DIR]:
        if folder.exists():
            shutil.rmtree(folder)

for folder in [PROCESSED_DIR, DIAGNOSTICS_DIR, AUDIT_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

print("Run ID:", RUN_ID)
print("Input file:", INPUT_FILE.resolve())
print("Recovery file:", RECOVERY_FILE.resolve())
print("Processed folder:", PROCESSED_DIR.resolve())
print("Diagnostics folder:", DIAGNOSTICS_DIR.resolve())

Run ID: 20260622_033916
Input file: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\00_Comparable_Raw_Files\Combined_Long\all_comparable_sources_long.csv
Recovery file: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Recovery\country_recovery_summary_dynamic_baseline_2007_2019.csv
Processed folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Volatility_Features
Diagnostics folder: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Diagnostics\04_Volatility_Features

In [2]:
# ------------------------------------------------------
# CONFIGURATION
# ------------------------------------------------------

PRE_SHOCK_WINDOWS = [
    {
        "shock_id": "2007",
        "shock_label": "shock_2007",
        "window_start": 2000,
        "window_end": 2007,
        "recovery_column": "Recovery_2007",
    },
    {
        "shock_id": "2019",
        "shock_label": "shock_2019",
        "window_start": 2012,
        "window_end": 2019,
        "recovery_column": "Recovery_2019",
    },
]

# Candidate variables for volatility/stability construction.
# The notebook will automatically skip missing variables.
VOLATILITY_VARIABLES = [
    {
        "variable": "gdp_growth",
        "feature_slug": "gdp_growth",
        "concept": "GDP growth volatility",
        "expected_unit": "percentage points",
        "preferred_feature": True,
        "interpretation": "Lower volatility is usually more stable; stability version is higher = better.",
    },
    {
        "variable": "inflation_cpi",
        "feature_slug": "inflation",
        "concept": "Inflation volatility",
        "expected_unit": "percentage points",
        "preferred_feature": False,
        "interpretation": "Lower volatility is usually more stable; stability version is higher = better.",
    },
    {
        "variable": "unemployment_rate",
        "feature_slug": "unemployment",
        "concept": "Unemployment volatility",
        "expected_unit": "percentage points",
        "preferred_feature": False,
        "interpretation": "Lower volatility is usually more stable; stability version is higher = better.",
    },
    {
        "variable": "productivity_gdp_per_hour",
        "feature_slug": "productivity_level",
        "concept": "Productivity level volatility",
        "expected_unit": "USD PPP per hour",
        "preferred_feature": False,
        "interpretation": "Interpret carefully; volatility of productivity level may reflect trend growth as well as instability.",
    },
]

MIN_YEARS_FOR_VOLATILITY = 4

print("Pre-shock windows:")
display(pd.DataFrame(PRE_SHOCK_WINDOWS))

print("Volatility variables:")
display(pd.DataFrame(VOLATILITY_VARIABLES))

Pre-shock windows:

  shock_id shock_label  window_start  window_end recovery_column
0     2007  shock_2007          2000        2007   Recovery_2007
1     2019  shock_2019          2012        2019   Recovery_2019

Volatility variables:

,variable,feature_slug,concept,expected_unit,preferred_feature,interpretation
0,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,Lower volatility is usually more stable; stabi...
1,inflation_cpi,inflation,Inflation volatility,percentage points,False,Lower volatility is usually more stable; stabi...
2,unemployment_rate,unemployment,Unemployment volatility,percentage points,False,Lower volatility is usually more stable; stabi...
3,productivity_gdp_per_hour,productivity_level,Productivity level volatility,USD PPP per hour,False,Interpret carefully; volatility of productivit...

In [3]:
# ------------------------------------------------------
# LOAD STANDARDIZED COMPARABLE LONG DATA
# ------------------------------------------------------

if not INPUT_FILE.exists():
    raise FileNotFoundError(f"Input file not found: {INPUT_FILE}")

df = pd.read_csv(INPUT_FILE)

required_columns = {
    "Country",
    "Year",
    "variable",
    "Value",
}

missing_columns = required_columns - set(df.columns)

if missing_columns:
    raise ValueError(f"Input dataset is missing required columns: {missing_columns}")

df["Country"] = df["Country"].astype(str).str.strip().str.upper()
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
df["Value"] = pd.to_numeric(df["Value"], errors="coerce")

df = df.dropna(subset=["Country", "Year", "variable", "Value"]).copy()
df["Year"] = df["Year"].astype(int)

if "country_name" not in df.columns:
    df["country_name"] = df["Country"]

df = df.sort_values(["variable", "Country", "Year"]).reset_index(drop=True)

available_variables = sorted(df["variable"].unique())

configured_variables = [item["variable"] for item in VOLATILITY_VARIABLES]
missing_configured_variables = sorted(set(configured_variables) - set(available_variables))

if missing_configured_variables:
    print("WARNING: These configured volatility variables are missing and will be skipped:")
    print(missing_configured_variables)

active_volatility_variables = [
    item
    for item in VOLATILITY_VARIABLES
    if item["variable"] in available_variables
]

if not active_volatility_variables:
    raise ValueError("None of the configured volatility variables are available in the input dataset.")

df_volatility_input = df[
    df["variable"].isin([item["variable"] for item in active_volatility_variables])
].copy()

df_volatility_input.to_csv(
    DIAGNOSTICS_DIR / "volatility_input_snapshot.csv",
    index=False,
)

print("Input rows:", len(df))
print("Volatility input rows:", len(df_volatility_input))
print("Countries:", df_volatility_input["Country"].nunique())
print("Variables used:", sorted(df_volatility_input["variable"].unique()))

display(df_volatility_input.head())

Input rows: 13446
Volatility input rows: 4629
Countries: 54
Variables used: ['gdp_growth', 'inflation_cpi', 'productivity_gdp_per_hour', 'unemployment_rate']

,Country,Country_Raw,country_name,Year,variable,Value,source_file,source_family,concept,expected_unit,raw_direction,is_derived,variable_notes,standardization_status,is_aggregate_region,Source_Used
3151,AUS,AUS,Australia,2000,gdp_growth,2.0315,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change,context_dependent,False,Used for recovery outcome and pre-shock GDP gr...,already_iso3,False,NaN
3152,AUS,AUS,Australia,2001,gdp_growth,3.9498,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change,context_dependent,False,Used for recovery outcome and pre-shock GDP gr...,already_iso3,False,NaN
3153,AUS,AUS,Australia,2002,gdp_growth,3.0913,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change,context_dependent,False,Used for recovery outcome and pre-shock GDP gr...,already_iso3,False,NaN
3154,AUS,AUS,Australia,2003,gdp_growth,4.2189,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change,context_dependent,False,Used for recovery outcome and pre-shock GDP gr...,already_iso3,False,NaN
3155,AUS,AUS,Australia,2004,gdp_growth,3.1555,OECD_GDP_Growth_2000_2025.csv,OECD_DBnomics,Real GDP growth,annual_percent_change,context_dependent,False,Used for recovery outcome and pre-shock GDP gr...,already_iso3,False,NaN

In [4]:
# ------------------------------------------------------
# LOAD RECOVERY OUTCOMES FOR DIAGNOSTIC ASSOCIATION ONLY
# ------------------------------------------------------
# Recovery is not used to construct volatility/stability features.
# It is only used later in this notebook for a diagnostic correlation table.

if RECOVERY_FILE.exists():
    recovery = pd.read_csv(RECOVERY_FILE)
    recovery["Country"] = recovery["Country"].astype(str).str.strip().str.upper()
    print("Recovery file loaded:", RECOVERY_FILE)
    print("Recovery rows:", len(recovery))
else:
    recovery = pd.DataFrame()
    print("Recovery file not found. Recovery diagnostic association will be skipped.")

display(recovery.head() if not recovery.empty else recovery)

Recovery file loaded: D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Recovery\country_recovery_summary_dynamic_baseline_2007_2019.csv
Recovery rows: 44

,Country,country_name,Recovery_2007,Recovery_2019,Recovery_2007_recovery_status,Recovery_2007_shock_detection_status,Recovery_2007_first_negative_growth_year,Recovery_2007_baseline_year,Recovery_2007_baseline_available_in_growth_file,Recovery_2007_recovery_year,Recovery_2007_years_from_baseline_to_recovery,Recovery_2007_years_after_first_negative_to_recovery,Recovery_2007_last_index_year,Recovery_2007_last_index_value,Recovery_2019_recovery_status,Recovery_2019_shock_detection_status,Recovery_2019_first_negative_growth_year,Recovery_2019_baseline_year,Recovery_2019_baseline_available_in_growth_file,Recovery_2019_recovery_year,Recovery_2019_years_from_baseline_to_recovery,Recovery_2019_years_after_first_negative_to_recovery,Recovery_2019_last_index_year,Recovery_2019_last_index_value
0,AUS,Australia,0.0000,0.0000,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN,no_negative_growth_in_shock_window,no_negative_growth_in_shock_window,NaN,NaN,False,NaN,0.0000,0.0000,NaN,NaN
1,AUT,Austria,2.0000,2.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2011.0000,3.0000,2.0000,2011.0000,101.0314,recovered,negative_growth_found,2020.0000,2019.0000,True,2022.0000,3.0000,2.0000,2022.0000,103.5338
2,BEL,Belgium,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.7522,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,101.1617
3,BRA,Brazil,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,107.3929,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,101.3298
4,CAN,Canada,1.0000,1.0000,recovered,negative_growth_found,2009.0000,2008.0000,True,2010.0000,2.0000,1.0000,2010.0000,100.0856,recovered,negative_growth_found,2020.0000,2019.0000,True,2021.0000,2.0000,1.0000,2021.0000,100.6125

In [5]:
# ------------------------------------------------------
# RAW COVERAGE BY VARIABLE AND WINDOW
# ------------------------------------------------------

coverage_rows = []

for window in PRE_SHOCK_WINDOWS:
    shock_id = window["shock_id"]
    shock_label = window["shock_label"]
    start = window["window_start"]
    end = window["window_end"]
    expected_years = list(range(start, end + 1))

    for item in active_volatility_variables:
        variable = item["variable"]
        feature_slug = item["feature_slug"]

        subset = df_volatility_input[
            (df_volatility_input["variable"] == variable)
            & (df_volatility_input["Year"] >= start)
            & (df_volatility_input["Year"] <= end)
        ].copy()

        country_summary = (
            subset
            .groupby("Country")
            .agg(
                years_available=("Year", "nunique"),
                min_year=("Year", "min"),
                max_year=("Year", "max"),
                min_value=("Value", "min"),
                median_value=("Value", "median"),
                max_value=("Value", "max"),
            )
            .reset_index()
        )

        coverage_rows.append({
            "shock_id": shock_id,
            "shock_label": shock_label,
            "window_start": start,
            "window_end": end,
            "variable": variable,
            "feature_slug": feature_slug,
            "expected_year_count": len(expected_years),
            "countries_with_any_data": subset["Country"].nunique(),
            "countries_with_min_years": int((country_summary["years_available"] >= MIN_YEARS_FOR_VOLATILITY).sum()),
            "median_years_available": country_summary["years_available"].median() if not country_summary.empty else np.nan,
            "max_years_available": country_summary["years_available"].max() if not country_summary.empty else np.nan,
        })

volatility_window_coverage_summary = pd.DataFrame(coverage_rows)

volatility_window_coverage_summary.to_csv(
    DIAGNOSTICS_DIR / "volatility_window_coverage_summary.csv",
    index=False,
)

display(volatility_window_coverage_summary)

,shock_id,shock_label,window_start,window_end,variable,feature_slug,expected_year_count,countries_with_any_data,countries_with_min_years,median_years_available,max_years_available
0,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,8,44,44,8.0000,8
1,2007,shock_2007,2000,2007,inflation_cpi,inflation,8,47,47,8.0000,8
2,2007,shock_2007,2000,2007,unemployment_rate,unemployment,8,51,48,8.0000,8
3,2007,shock_2007,2000,2007,productivity_gdp_per_hour,productivity_level,8,40,40,8.0000,8
4,2019,shock_2019,2012,2019,gdp_growth,gdp_growth,8,44,44,8.0000,8
5,2019,shock_2019,2012,2019,inflation_cpi,inflation,8,48,47,8.0000,8
6,2019,shock_2019,2012,2019,unemployment_rate,unemployment,8,52,51,8.0000,8
7,2019,shock_2019,2012,2019,productivity_gdp_per_hour,productivity_level,8,41,41,8.0000,8

In [6]:
# ------------------------------------------------------
# VOLATILITY FEATURE CONSTRUCTION HELPERS
# ------------------------------------------------------

def min_max_scale_higher_better_from_lower_better(series):
    values = pd.to_numeric(series, errors="coerce")
    min_value = values.min(skipna=True)
    max_value = values.max(skipna=True)

    if pd.isna(min_value) or pd.isna(max_value):
        return pd.Series(np.nan, index=series.index)

    if np.isclose(max_value, min_value):
        return pd.Series(100.0, index=series.index)

    return 100.0 * (max_value - values) / (max_value - min_value)


def min_max_scale_higher_better(series):
    values = pd.to_numeric(series, errors="coerce")
    min_value = values.min(skipna=True)
    max_value = values.max(skipna=True)

    if pd.isna(min_value) or pd.isna(max_value):
        return pd.Series(np.nan, index=series.index)

    if np.isclose(max_value, min_value):
        return pd.Series(100.0, index=series.index)

    return 100.0 * (values - min_value) / (max_value - min_value)


def calculate_country_window_stats(subset, expected_years):
    expected_year_count = len(expected_years)

    stats = (
        subset
        .groupby(["Country", "country_name", "variable"])
        .agg(
            years_available=("Year", "nunique"),
            min_year=("Year", "min"),
            max_year=("Year", "max"),
            mean_value=("Value", "mean"),
            median_value=("Value", "median"),
            min_value=("Value", "min"),
            max_value=("Value", "max"),
            volatility_std=("Value", lambda x: x.std(ddof=1)),
            volatility_mad=("Value", lambda x: np.mean(np.abs(x - np.mean(x))) if len(x) > 0 else np.nan),
            first_value=("Value", "first"),
            last_value=("Value", "last"),
        )
        .reset_index()
    )

    stats["expected_year_count"] = expected_year_count
    stats["coverage_rate_in_window"] = stats["years_available"] / expected_year_count
    stats["sufficient_years_for_volatility"] = stats["years_available"] >= MIN_YEARS_FOR_VOLATILITY

    stats.loc[~stats["sufficient_years_for_volatility"], "volatility_std"] = np.nan
    stats.loc[~stats["sufficient_years_for_volatility"], "volatility_mad"] = np.nan

    stats["range_value"] = stats["max_value"] - stats["min_value"]
    stats["change_first_to_last"] = stats["last_value"] - stats["first_value"]

    return stats

In [7]:
# ------------------------------------------------------
# BUILD VOLATILITY FEATURES BY COUNTRY-SHOCK-VARIABLE
# ------------------------------------------------------

feature_rows = []

for window in PRE_SHOCK_WINDOWS:
    shock_id = window["shock_id"]
    shock_label = window["shock_label"]
    start = window["window_start"]
    end = window["window_end"]
    expected_years = list(range(start, end + 1))

    for item in active_volatility_variables:
        variable = item["variable"]
        feature_slug = item["feature_slug"]

        subset = df_volatility_input[
            (df_volatility_input["variable"] == variable)
            & (df_volatility_input["Year"] >= start)
            & (df_volatility_input["Year"] <= end)
        ].copy()

        subset = subset.sort_values(["Country", "Year"]).copy()

        if subset.empty:
            continue

        stats = calculate_country_window_stats(subset, expected_years)

        stats["shock_id"] = shock_id
        stats["shock_label"] = shock_label
        stats["window_start"] = start
        stats["window_end"] = end
        stats["feature_slug"] = feature_slug
        stats["concept"] = item["concept"]
        stats["expected_unit"] = item["expected_unit"]
        stats["preferred_feature"] = item["preferred_feature"]
        stats["interpretation"] = item["interpretation"]

        feature_rows.append(stats)

volatility_features_long = pd.concat(feature_rows, ignore_index=True)

# Direction-aligned stability measures.
# Lower volatility -> higher stability.
volatility_features_long["stability_negative_std"] = -volatility_features_long["volatility_std"]
volatility_features_long["stability_negative_mad"] = -volatility_features_long["volatility_mad"]

# 0-100 stability scores are scaled within each shock_id + variable.
# These are useful for diagnostics/visuals, not raw source measures.
volatility_features_long["stability_std_0_100"] = np.nan
volatility_features_long["stability_mad_0_100"] = np.nan

for (shock_id, variable), idx in volatility_features_long.groupby(["shock_id", "variable"]).groups.items():
    idx = list(idx)

    volatility_features_long.loc[idx, "stability_std_0_100"] = (
        min_max_scale_higher_better_from_lower_better(
            volatility_features_long.loc[idx, "volatility_std"]
        )
    )

    volatility_features_long.loc[idx, "stability_mad_0_100"] = (
        min_max_scale_higher_better_from_lower_better(
            volatility_features_long.loc[idx, "volatility_mad"]
        )
    )

volatility_features_long = volatility_features_long[
    [
        "Country",
        "country_name",
        "shock_id",
        "shock_label",
        "window_start",
        "window_end",
        "variable",
        "feature_slug",
        "concept",
        "expected_unit",
        "preferred_feature",
        "years_available",
        "expected_year_count",
        "coverage_rate_in_window",
        "sufficient_years_for_volatility",
        "mean_value",
        "median_value",
        "min_value",
        "max_value",
        "range_value",
        "first_value",
        "last_value",
        "change_first_to_last",
        "volatility_std",
        "volatility_mad",
        "stability_negative_std",
        "stability_negative_mad",
        "stability_std_0_100",
        "stability_mad_0_100",
        "interpretation",
    ]
].sort_values(["shock_id", "variable", "Country"]).reset_index(drop=True)

volatility_features_long.to_csv(
    PROCESSED_DIR / "volatility_features_country_shock_variable_long.csv",
    index=False,
)

volatility_features_long.to_csv(
    DIAGNOSTICS_DIR / "volatility_features_country_shock_variable_long.csv",
    index=False,
)

print("Volatility feature rows:", len(volatility_features_long))
display(volatility_features_long.head(80))

Volatility feature rows: 367

,Country,country_name,shock_id,shock_label,window_start,window_end,variable,feature_slug,concept,expected_unit,preferred_feature,years_available,expected_year_count,coverage_rate_in_window,sufficient_years_for_volatility,mean_value,median_value,min_value,max_value,range_value,first_value,last_value,change_first_to_last,volatility_std,volatility_mad,stability_negative_std,stability_negative_mad,stability_std_0_100,stability_mad_0_100,interpretation
0,AUS,Australia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.3289,3.3897,2.0315,4.2189,2.1875,2.0315,3.6240,1.5925,0.7130,0.5666,-0.7130,-0.5666,100.0000,100.0000,Lower volatility is usually more stable; stabi...
1,AUT,Austria,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.3828,2.4428,1.1416,3.7752,2.6337,3.1895,3.7752,0.5857,0.9926,0.8170,-0.9926,-0.8170,93.0853,89.2635,Lower volatility is usually more stable; stabi...
2,BEL,Belgium,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.4604,2.4370,1.0380,3.7167,2.6787,3.7167,3.6769,-0.0398,1.1188,0.9189,-1.1188,-0.9189,89.9631,84.8953,Lower volatility is usually more stable; stabi...
3,BRA,Brazil,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.6208,3.5821,1.1408,6.0699,4.9290,4.3879,6.0699,1.6819,1.8088,1.4242,-1.8088,-1.4242,72.9009,63.2269,Lower volatility is usually more stable; stabi...
4,CAN,Canada,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.8512,2.8186,1.8064,5.1385,3.3322,5.1385,2.0499,-3.0886,1.0805,0.7589,-1.0805,-0.7589,90.9102,91.7548,Lower volatility is usually more stable; stabi...
5,CHE,Switzerland,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.3723,2.7695,-0.2842,4.1343,4.4185,3.6332,3.9832,0.3500,1.6607,1.3571,-1.6607,-1.3571,76.5645,66.1033,Lower volatility is usually more stable; stabi...
6,CHL,Chile,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.9727,5.0699,3.1540,6.6743,3.5202,4.9716,5.1682,0.1966,1.2730,0.9597,-1.2730,-0.9597,86.1515,83.1434,Lower volatility is usually more stable; stabi...
7,CHN,China,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,10.5572,10.0758,8.3358,14.2308,5.8951,8.4900,14.2308,5.7409,2.0901,1.6687,-2.0901,-1.6687,65.9457,52.7410,Lower volatility is usually more stable; stabi...
8,COL,Colombia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.2705,4.3125,1.6779,6.7382,5.0603,2.5692,6.7382,4.1690,1.9366,1.6031,-1.9366,-1.6031,69.7407,55.5532,Lower volatility is usually more stable; stabi...
9,CRI,Costa Rica,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.8796,4.1469,3.4169,8.2151,4.7983,3.8687,8.2151,4.3464,1.8339,1.4456,-1.8339,-1.4456,72.2816,62.3067,Lower volatility is usually more stable; stabi...
10,CZE,Czechia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.3707,4.3735,1.5135,6.6232,5.1097,4.0107,5.4888,1.4782,1.7738,1.4351,-1.7738,-1.4351,73.7664,62.7567,Lower volatility is usually more stable; stabi...
11,DEU,Germany,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,1.5697,1.3991,-0.5298,3.8667,4.3965,2.8765,2.8891,0.0126,1.5586,1.2474,-1.5586,-1.2474,79.0895,70.8089,Lower volatility is usually more stable; stabi...
12,DNK,Denmark,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,1.9389,1.6734,0.4411,3.8165,3.3754,3.7240,0.9872,-2.7368,1.4099,1.2302,-1.4099,-1.2302,82.7658,71.5450,Lower volatility is usually more stable; stabi...
13,ESP,Spain,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.6321,3.5424,2.7555,5.2006,2.4452,5.2006,3.5335,-1.6671,0.7787,0.5667,-0.7787,-0.5667,98.3745,99.9979,Lower volatility is usually more stable; stabi...
14,EST,Estonia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,8.0194,7.5836,5.8807,10.0876,4.2069,10.0876,7.5709,-2.5167,1.5674,1.3288,-1.5674,-1.3288,78.8718,67.3174,Lower volatility is usually more stable; stabi...
15,FIN,Finland,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.5260,3.3913,1.6873,5.7537,4.0664,5.7537,5.3128,-0.4409,1.4951,1.2468,-1.4951,-1.2468,80.6588,70.8312,Lower volatility is usually more stable; stabi...
16,FRA,France,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.2597,2.2150,0.9678,4.1410,3.1732,4.1410,2.5305,-1.6105,1.0383,0.8038,-1.0383,-0.8038,91.9546,89.8310,Lower volatility is usually more stable; stabi...
17,GBR,United Kingdom,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.7600,2.5908,1.7090,4.5244,2.8154,4.5244,2.9309,-1.5935,0.8542,0.6061,-0.8542,-0.6061,96.5074,98.3088,Lower volatility is usually more stable; stabi...
18,GRC,Greece,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.4725,4.6668,1.1835,6.4434,5.2599,4.1378,3.5069,-0.6310,1.6211,1.1473,-1.6211,-1.1473,77.5432,75.0996,Lower volatility is usually more stable; stabi...
19,HUN,Hungary,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.8337,4.1812,0.3324,4.9631,4.6308,4.4094,0.3324,-4.0770,1.4619,0.8753,-1.4619,-0.8753,81.4791,86.7618,Lower volatility is usually more stable; stabi...
20,IDN,Indonesia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.0516,4.9755,3.6435,6.3450,2.7016,4.9200,6.3450,1.4250,0.8163,0.5959,-0.8163,-0.5959,97.4439,98.7433,Lower volatility is usually more stable; stabi...
21,IND,India,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,7.0753,7.8916,3.8040,9.8014,5.9974,3.8410,9.8014,5.9604,2.5261,2.1892,-2.5261,-2.1892,55.1636,30.4199,Lower volatility is usually more stable; stabi...
22,IRL,Ireland,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.8061,5.5250,3.0138,9.4035,6.3897,9.4035,5.3101,-4.0934,1.8080,1.1682,-1.8080,-1.1682,72.9222,74.2031,Lower volatility is usually more stable; stabi...
23,ISL,Iceland,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.0793,5.2884,0.5423,8.7413,8.1990,4.9052,8.7413,3.8361,2.7777,2.1869,-2.7777,-2.1869,48.9430,30.5208,Lower volatility is usually more stable; stabi...
24,ISR,Israel,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.8814,4.5015,-0.1528,8.5915,8.7443,8.5915,6.3130,-2.2785,3.0968,2.5229,-3.0968,-2.5229,41.0516,16.1118,Lower volatility is usually more stable; stabi...
25,ITA,Italy,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,1.4654,1.4682,0.0666,3.8821,3.8155,3.8821,1.4623,-2.4198,1.2027,0.8251,-1.2027,-0.8251,87.8902,88.9162,Lower volatility is usually more stable; stabi...
26,JPN,Japan,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,1.4955,1.6373,0.0850,2.9783,2.8933,2.9783,1.7284,-1.2499,0.9434,0.6842,-0.9434,-0.6842,94.3008,94.9588,Lower volatility is usually more stable; stabi...
27,KOR,"Korea, Republic of",2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.6719,5.2143,3.0747,9.2019,6.1271,9.2019,5.8420,-3.3599,1.9482,1.4430,-1.9482,-1.4430,69.4536,62.4193,Lower volatility is usually more stable; stabi...
28,LTU,Lithuania,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,7.4852,7.0577,3.4186,11.0779,7.6593,3.4186,11.0779,7.6593,2.4341,1.7264,-2.4341,-1.7264,57.4403,50.2656,Lower volatility is usually more stable; stabi...
29,LUX,Luxembourg,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.5857,3.7280,2.4825,8.0985,5.6160,6.9381,8.0985,1.1604,2.1538,1.8241,-2.1538,-1.8241,64.3701,46.0791,Lower volatility is usually more stable; stabi...
30,LVA,Latvia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,8.9970,8.5771,5.8410,12.8250,6.9840,5.8410,10.4145,4.5735,2.4519,1.9659,-2.4519,-1.9659,57.0000,39.9952,Lower volatility is usually more stable; stabi...
31,MEX,Mexico,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.2611,2.0956,-0.4508,5.0293,5.4801,5.0293,2.0779,-2.9514,2.0922,1.6541,-2.0922,-1.6541,65.8940,53.3679,Lower volatility is usually more stable; stabi...
32,NLD,Netherlands,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.2950,2.1788,0.0979,4.2197,4.1218,4.2197,3.8854,-0.3343,1.5561,1.1965,-1.5561,-1.1965,79.1504,72.9902,Lower volatility is usually more stable; stabi...
33,NOR,Norway,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.7160,2.9085,1.0964,4.3302,3.2338,3.4434,3.4203,-0.0231,1.0840,0.8577,-1.0840,-0.8577,90.8258,87.5187,Lower volatility is usually more stable; stabi...
34,NZL,New Zealand,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.5496,3.4999,2.3080,5.0380,2.7300,2.3080,3.7878,1.4799,0.9973,0.7908,-0.9973,-0.7908,92.9675,90.3855,Lower volatility is usually more stable; stabi...
35,POL,Poland,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.0786,4.0899,1.2337,6.7605,5.5267,4.6563,6.7605,2.1041,1.9593,1.5988,-1.9593,-1.5988,69.1810,55.7382,Lower volatility is usually more stable; stabi...
36,PRT,Portugal,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,1.5378,1.7069,-0.9305,3.8162,4.7467,3.8162,2.5066,-1.3096,1.3947,0.9978,-1.3947,-0.9978,83.1409,81.5112,Lower volatility is usually more stable; stabi...
37,RUS,Russian Federation,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,7.1771,7.2359,4.7438,10.0457,5.3019,10.0457,8.5351,-1.5106,1.7710,1.3304,-1.7710,-1.3304,73.8378,67.2496,Lower volatility is usually more stable; stabi...
38,SVK,Slovakia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.5759,5.1231,0.7892,10.8186,10.0294,0.7892,10.8186,10.0294,3.1930,2.3754,-3.1930,-2.3754,38.6733,22.4373,Lower volatility is usually more stable; stabi...
39,SVN,Slovenia,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.2815,3.6760,2.8287,7.1392,4.3105,3.4979,7.1392,3.6413,1.5105,1.1873,-1.5105,-1.1873,80.2795,73.3827,Lower volatility is usually more stable; stabi...
40,SWE,Sweden,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,3.1280,3.0090,1.3608,4.6761,3.3153,4.6311,3.2249,-1.4063,1.2697,1.0499,-1.2697,-1.0499,86.2339,79.2781,Lower volatility is usually more stable; stabi...
41,TUR,Türkiye,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,5.6217,6.7104,-5.4594,9.9254,15.3848,6.9853,5.1082,-1.8771,4.7569,2.8986,-4.7569,-2.8986,0.0000,0.0000,Lower volatility is usually more stable; stabi...
42,USA,United States,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,2.7061,2.7901,0.9555,4.0776,3.1220,4.0776,2.0039,-2.0737,1.0936,0.8646,-1.0936,-0.8646,90.5870,87.2217,Lower volatility is usually more stable; stabi...
43,ZAF,South Africa,2007,shock_2007,2000,2007,gdp_growth,gdp_growth,GDP growth volatility,percentage points,True,8,8,1.0000,True,4.2932,4.3773,2.7000,5.6038,2.9038,4.2000,5.3605,1.1605,1.1083,0.9058,-1.1083,-0.9058,90.2242,85.4557,Lower volatility is usually more stable; stabi...
44,AUS,Australia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,3.1871,2.8571,2.3276,4.4574,2.1298,4.4574,2.3276,-2.1298,0.8605,0.7146,-0.8605,-0.7146,97.0362,97.1921,Lower volatility is usually more stable; stabi...
45,AUT,Austria,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.0164,2.1149,1.3556,2.6500,1.2944,2.3449,2.1686,-0.1763,0.4510,0.3604,-0.4510,-0.3604,98.9699,99.0970,Lower volatility is usually more stable; stabi...
46,BEL,Belgium,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.0926,1.9602,1.5890,2.7814,1.1925,2.5445,1.8231,-0.7215,0.4532,0.3805,-0.4532,-0.3805,98.9596,98.9891,Lower volatility is usually more stable; stabi...
47,BGR,Bulgaria,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,6.5858,6.7044,2.3486,10.3163,7.9676,10.3163,8.4025,-1.9137,2.3729,1.7496,-2.3729,-1.7496,89.8927,91.6265,Lower volatility is usually more stable; stabi...
48,BRA,Brazil,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,7.2926,6.8549,3.6413,14.7149,11.0736,7.0441,3.6413,-3.4029,3.3882,2.1449,-3.3882,-2.1449,85.0975,89.5002,Lower volatility is usually more stable; stabi...
49,CAN,Canada,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.3091,2.2360,1.8573,2.7586,0.9013,2.7194,2.1384,-0.5811,0.3287,0.2690,-0.3287,-0.2690,99.5477,99.5889,Lower volatility is usually more stable; stabi...
50,CHE,Switzerland,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,0.9494,0.8960,0.6383,1.5585,0.9203,1.5585,0.7324,-0.8262,0.3148,0.2453,-0.3148,-0.2453,99.6134,99.7159,Lower volatility is usually more stable; stabi...
51,CHL,Chile,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,3.0774,3.2223,1.0547,4.4078,3.3531,3.8433,4.4078,0.5645,1.0146,0.7257,-1.0146,-0.7257,96.3081,97.1329,Lower volatility is usually more stable; stabi...
52,CHN,China,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,1.6875,1.3500,-0.8000,4.8000,5.6000,0.4000,4.8000,4.4000,1.8396,1.3594,-1.8396,-1.3594,92.4116,93.7249,Lower volatility is usually more stable; stabi...
53,COL,Colombia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,6.4331,6.1278,4.2934,9.2253,4.9319,9.2253,5.5444,-3.6810,1.6122,1.2553,-1.6122,-1.2553,93.4854,94.2844,Lower volatility is usually more stable; stabi...
54,CRI,Costa Rica,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,10.9717,11.1086,9.1675,13.7983,4.6308,10.9616,9.3572,-1.6043,1.6172,1.2382,-1.6172,-1.2382,93.4619,94.3766,Lower volatility is usually more stable; stabi...
55,CZE,Czechia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.5580,2.6471,0.1187,4.6627,4.5439,3.7754,2.8531,-0.9223,1.3581,0.9548,-1.3581,-0.9548,94.6859,95.9006,Lower volatility is usually more stable; stabi...
56,DEU,Germany,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,1.6209,1.5622,1.0342,2.2983,1.2641,1.4403,2.2983,0.8581,0.3811,0.2713,-0.3811,-0.2713,99.3001,99.5765,Lower volatility is usually more stable; stabi...
57,DNK,Denmark,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.0413,1.9996,1.1544,2.9033,1.7489,2.9033,1.6933,-1.2100,0.5278,0.3939,-0.5278,-0.3939,98.6072,98.9172,Lower volatility is usually more stable; stabi...
58,ESP,Spain,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,3.2298,3.2172,2.7868,3.5898,0.8030,3.4335,2.7868,-0.6467,0.2849,0.2471,-0.2849,-0.2471,99.7548,99.7063,Lower volatility is usually more stable; stabi...
59,EST,Estonia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,4.1051,4.0491,1.3350,6.6013,5.2663,4.0185,6.6013,2.5828,1.6091,1.1180,-1.6091,-1.1180,93.5002,95.0229,Lower volatility is usually more stable; stabi...
60,FIN,Finland,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,1.6197,1.5689,0.1871,3.0421,2.8550,3.0421,2.5107,-0.5314,1.0237,0.8180,-1.0237,-0.8180,96.2650,96.6361,Lower volatility is usually more stable; stabi...
61,FRA,France,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,1.7980,1.7109,1.4880,2.1421,0.6541,1.6760,1.4880,-0.1880,0.2330,0.1925,-0.2330,-0.1925,100.0000,100.0000,Lower volatility is usually more stable; stabi...
62,GBR,United Kingdom,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,1.7625,1.5500,1.2000,2.5000,1.3000,1.2000,2.4000,1.2000,0.4984,0.4281,-0.4984,-0.4281,98.7463,98.7330,Lower volatility is usually more stable; stabi...
63,GRC,Greece,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,3.2775,3.2850,2.8950,3.6294,0.7344,3.1512,2.8950,-0.2562,0.2881,0.2423,-0.2881,-0.2423,99.7394,99.7325,Lower volatility is usually more stable; stabi...
64,HRV,Croatia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,2.9094,3.0292,1.6917,4.6167,2.9250,4.6167,2.8750,-1.7417,1.0300,0.8135,-1.0300,-0.8135,96.2356,96.6603,Lower volatility is usually more stable; stabi...
65,HUN,Hungary,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,6.3802,6.0049,3.5615,9.8036,6.2421,9.8036,7.9587,-1.8449,2.3898,2.0257,-2.3898,-2.0257,89.8129,90.1418,Lower volatility is usually more stable; stabi...
66,IDN,Indonesia,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,8.7348,8.6053,3.6886,13.1087,9.4201,3.6886,6.4066,2.7179,3.4159,3.0057,-3.4159,-3.0057,84.9666,84.8713,Lower volatility is usually more stable; stabi...
67,IND,India,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,4.5093,4.1279,3.7672,6.3729,2.6056,4.0094,6.3729,2.3634,1.0051,0.7877,-1.0051,-0.7877,96.3528,96.7994,Lower volatility is usually more stable; stabi...
68,IRL,Ireland,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,4.0009,4.2820,2.1785,5.5776,3.3991,5.5776,4.8857,-0.6919,1.2164,0.9852,-1.2164,-0.9852,95.3551,95.7373,Lower volatility is usually more stable; stabi...
69,ISL,Iceland,2007,shock_2007,2000,2007,inflation_cpi,inflation,Inflation volatility,percentage points,False,8,8,1.0000,True,4.7098,5.0940,2.0557,6.6871,4.6314,5.1365,5.0516,-0.0849,1.5718,1.2321,-1.5718,-1.2321,93.6764,94.4094,Lower volatility is usually more stable; stabi...

In [8]:
# ------------------------------------------------------
# CREATE WIDE FEATURE TABLES
# ------------------------------------------------------

feature_value_columns = [
    "volatility_std",
    "volatility_mad",
    "stability_negative_std",
    "stability_negative_mad",
    "stability_std_0_100",
    "stability_mad_0_100",
    "mean_value",
    "median_value",
    "change_first_to_last",
    "years_available",
    "coverage_rate_in_window",
]

wide_frames = []

base_keys = ["Country", "country_name", "shock_id", "shock_label", "window_start", "window_end"]

for value_col in feature_value_columns:
    temp = volatility_features_long.copy()

    temp["wide_feature_name"] = (
        temp["feature_slug"]
        + "_"
        + value_col
        + "_pre_"
        + temp["shock_id"].astype(str)
    )

    wide_temp = (
        temp
        .pivot_table(
            index=base_keys,
            columns="wide_feature_name",
            values=value_col,
            aggfunc="first",
        )
        .reset_index()
    )

    wide_frames.append(wide_temp)

volatility_features_wide = wide_frames[0]

for frame in wide_frames[1:]:
    volatility_features_wide = volatility_features_wide.merge(
        frame,
        on=base_keys,
        how="outer",
    )

volatility_features_wide = volatility_features_wide.sort_values(["shock_id", "Country"]).reset_index(drop=True)

volatility_features_wide.to_csv(
    PROCESSED_DIR / "volatility_features_country_shock_wide.csv",
    index=False,
)

volatility_features_wide.to_csv(
    DIAGNOSTICS_DIR / "volatility_features_country_shock_wide.csv",
    index=False,
)

# Also create one-row-per-country wide table across both shocks.
country_level_keys = ["Country", "country_name"]

cross_shock_frames = []

for value_col in feature_value_columns:
    temp = volatility_features_long.copy()

    temp["wide_feature_name"] = (
        temp["feature_slug"]
        + "_"
        + value_col
        + "_pre_"
        + temp["shock_id"].astype(str)
    )

    cross_temp = (
        temp
        .pivot_table(
            index=country_level_keys,
            columns="wide_feature_name",
            values=value_col,
            aggfunc="first",
        )
        .reset_index()
    )

    cross_shock_frames.append(cross_temp)

volatility_features_country_wide = cross_shock_frames[0]

for frame in cross_shock_frames[1:]:
    volatility_features_country_wide = volatility_features_country_wide.merge(
        frame,
        on=country_level_keys,
        how="outer",
    )

volatility_features_country_wide = volatility_features_country_wide.sort_values("Country").reset_index(drop=True)

volatility_features_country_wide.to_csv(
    PROCESSED_DIR / "volatility_features_country_wide.csv",
    index=False,
)

print("Country-shock wide rows:", len(volatility_features_wide))
print("Country-wide rows:", len(volatility_features_country_wide))

display(volatility_features_wide.head())
display(volatility_features_country_wide.head())

Country-shock wide rows: 106
Country-wide rows: 54

wide_feature_name,Country,country_name,shock_id,shock_label,window_start,window_end,gdp_growth_volatility_std_pre_2007,gdp_growth_volatility_std_pre_2019,inflation_volatility_std_pre_2007,inflation_volatility_std_pre_2019,productivity_level_volatility_std_pre_2007,productivity_level_volatility_std_pre_2019,unemployment_volatility_std_pre_2007,unemployment_volatility_std_pre_2019,gdp_growth_volatility_mad_pre_2007,gdp_growth_volatility_mad_pre_2019,inflation_volatility_mad_pre_2007,inflation_volatility_mad_pre_2019,productivity_level_volatility_mad_pre_2007,productivity_level_volatility_mad_pre_2019,unemployment_volatility_mad_pre_2007,unemployment_volatility_mad_pre_2019,gdp_growth_stability_negative_std_pre_2007,gdp_growth_stability_negative_std_pre_2019,inflation_stability_negative_std_pre_2007,inflation_stability_negative_std_pre_2019,productivity_level_stability_negative_std_pre_2007,productivity_level_stability_negative_std_pre_2019,unemployment_stability_negative_std_pre_2007,unemployment_stability_negative_std_pre_2019,gdp_growth_stability_negative_mad_pre_2007,gdp_growth_stability_negative_mad_pre_2019,inflation_stability_negative_mad_pre_2007,inflation_stability_negative_mad_pre_2019,productivity_level_stability_negative_mad_pre_2007,productivity_level_stability_negative_mad_pre_2019,unemployment_stability_negative_mad_pre_2007,unemployment_stability_negative_mad_pre_2019,gdp_growth_stability_std_0_100_pre_2007,gdp_growth_stability_std_0_100_pre_2019,inflation_stability_std_0_100_pre_2007,inflation_stability_std_0_100_pre_2019,productivity_level_stability_std_0_100_pre_2007,productivity_level_stability_std_0_100_pre_2019,unemployment_stability_std_0_100_pre_2007,unemployment_stability_std_0_100_pre_2019,gdp_growth_stability_mad_0_100_pre_2007,gdp_growth_stability_mad_0_100_pre_2019,inflation_stability_mad_0_100_pre_2007,inflation_stability_mad_0_100_pre_2019,productivity_level_stability_mad_0_100_pre_2007,productivity_level_stability_mad_0_100_pre_2019,unemployment_stability_mad_0_100_pre_2007,unemployment_stability_mad_0_100_pre_2019,gdp_growth_mean_value_pre_2007,gdp_growth_mean_value_pre_2019,inflation_mean_value_pre_2007,inflation_mean_value_pre_2019,productivity_level_mean_value_pre_2007,productivity_level_mean_value_pre_2019,unemployment_mean_value_pre_2007,unemployment_mean_value_pre_2019,gdp_growth_median_value_pre_2007,gdp_growth_median_value_pre_2019,inflation_median_value_pre_2007,inflation_median_value_pre_2019,productivity_level_median_value_pre_2007,productivity_level_median_value_pre_2019,unemployment_median_value_pre_2007,unemployment_median_value_pre_2019,gdp_growth_change_first_to_last_pre_2007,gdp_growth_change_first_to_last_pre_2019,inflation_change_first_to_last_pre_2007,inflation_change_first_to_last_pre_2019,productivity_level_change_first_to_last_pre_2007,productivity_level_change_first_to_last_pre_2019,unemployment_change_first_to_last_pre_2007,unemployment_change_first_to_last_pre_2019,gdp_growth_years_available_pre_2007,gdp_growth_years_available_pre_2019,inflation_years_available_pre_2007,inflation_years_available_pre_2019,productivity_level_years_available_pre_2007,productivity_level_years_available_pre_2019,unemployment_years_available_pre_2007,unemployment_years_available_pre_2019,gdp_growth_coverage_rate_in_window_pre_2007,gdp_growth_coverage_rate_in_window_pre_2019,inflation_coverage_rate_in_window_pre_2007,inflation_coverage_rate_in_window_pre_2019,productivity_level_coverage_rate_in_window_pre_2007,productivity_level_coverage_rate_in_window_pre_2019,unemployment_coverage_rate_in_window_pre_2007,unemployment_coverage_rate_in_window_pre_2019
0,AUS,Australia,2007,shock_2007,2000,2007,0.7130,NaN,0.8605,NaN,1.8835,NaN,0.8455,NaN,0.5666,NaN,0.7146,NaN,1.5233,NaN,0.7175,NaN,-0.7130,NaN,-0.8605,NaN,-1.8835,NaN,-0.8455,NaN,-0.5666,NaN,-0.7146,NaN,-1.5233,NaN,-0.7175,NaN,100.0000,NaN,97.0362,NaN,69.5619,NaN,86.6022,NaN,100.0000,NaN,97.1921,NaN,70.7432,NaN,85.2081,NaN,3.3289,NaN,3.1871,NaN,57.4673,NaN,5.6178,NaN,3.3897,NaN,2.8571,NaN,58.1212,NaN,5.6655,NaN,1.5925,NaN,-2.1298,NaN,5.4976,NaN,-1.9070,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN
1,AUT,Austria,2007,shock_2007,2000,2007,0.9926,NaN,0.4510,NaN,3.2168,NaN,0.8517,NaN,0.8170,NaN,0.3604,NaN,2.5730,NaN,0.7359,NaN,-0.9926,NaN,-0.4510,NaN,-3.2168,NaN,-0.8517,NaN,-0.8170,NaN,-0.3604,NaN,-2.5730,NaN,-0.7359,NaN,93.0853,NaN,98.9699,NaN,43.8679,NaN,86.4649,NaN,89.2635,NaN,99.0970,NaN,46.8312,NaN,84.7149,NaN,2.3828,NaN,2.0164,NaN,71.5824,NaN,4.5679,NaN,2.4428,NaN,2.1149,NaN,70.9200,NaN,4.5685,NaN,0.5857,NaN,-0.1763,NaN,9.2207,NaN,1.3560,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN
2,BEL,Belgium,2007,shock_2007,2000,2007,1.1188,NaN,0.4532,NaN,2.7797,NaN,0.6867,NaN,0.9189,NaN,0.3805,NaN,2.4418,NaN,0.5826,NaN,-1.1188,NaN,-0.4532,NaN,-2.7797,NaN,-0.6867,NaN,-0.9189,NaN,-0.3805,NaN,-2.4418,NaN,-0.5826,NaN,89.9631,NaN,98.9596,NaN,52.2911,NaN,90.1086,NaN,84.8953,NaN,98.9891,NaN,49.8205,NaN,88.8285,NaN,2.4604,NaN,2.0926,NaN,80.5300,NaN,7.7304,NaN,2.4370,NaN,1.9602,NaN,80.1683,NaN,7.8440,NaN,-0.0398,NaN,-0.7215,NaN,7.1249,NaN,0.4490,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN
3,BGR,Bulgaria,2007,shock_2007,2000,2007,NaN,NaN,2.3729,NaN,1.8909,NaN,4.7546,NaN,NaN,NaN,1.7496,NaN,1.4970,NaN,3.8919,NaN,NaN,NaN,-2.3729,NaN,-1.8909,NaN,-4.7546,NaN,NaN,NaN,-1.7496,NaN,-1.4970,NaN,-3.8919,NaN,NaN,NaN,89.8927,NaN,69.4201,NaN,0.2838,NaN,NaN,NaN,91.6265,NaN,71.3424,NaN,0.0000,NaN,NaN,NaN,6.5858,NaN,21.2491,NaN,13.3799,NaN,NaN,NaN,6.7044,NaN,21.1649,NaN,12.8590,NaN,NaN,NaN,-1.9137,NaN,5.4576,NaN,-10.0410,NaN,NaN,NaN,8.0000,NaN,8.0000,NaN,8.0000,NaN,NaN,NaN,1.0000,NaN,1.0000,NaN,1.0000,NaN
4,BRA,Brazil,2007,shock_2007,2000,2007,1.8088,NaN,3.3882,NaN,NaN,NaN,0.5787,NaN,1.4242,NaN,2.1449,NaN,NaN,NaN,0.4550,NaN,-1.8088,NaN,-3.3882,NaN,NaN,NaN,-0.5787,NaN,-1.4242,NaN,-2.1449,NaN,NaN,NaN,-0.4550,NaN,72.9009,NaN,85.0975,NaN,NaN,NaN,92.4934,NaN,63.2269,NaN,89.5002,NaN,NaN,NaN,92.2537,NaN,3.6208,NaN,7.2926,NaN,NaN,NaN,8.9749,NaN,3.5821,NaN,6.8549,NaN,NaN,NaN,9.1170,NaN,1.6819,NaN,-3.4029,NaN,NaN,NaN,-1.2820,NaN,8.0000,NaN,8.0000,NaN,NaN,NaN,7.0000,NaN,1.0000,NaN,1.0000,NaN,NaN,NaN,0.8750,NaN

wide_feature_name,Country,country_name,gdp_growth_volatility_std_pre_2007,gdp_growth_volatility_std_pre_2019,inflation_volatility_std_pre_2007,inflation_volatility_std_pre_2019,productivity_level_volatility_std_pre_2007,productivity_level_volatility_std_pre_2019,unemployment_volatility_std_pre_2007,unemployment_volatility_std_pre_2019,gdp_growth_volatility_mad_pre_2007,gdp_growth_volatility_mad_pre_2019,inflation_volatility_mad_pre_2007,inflation_volatility_mad_pre_2019,productivity_level_volatility_mad_pre_2007,productivity_level_volatility_mad_pre_2019,unemployment_volatility_mad_pre_2007,unemployment_volatility_mad_pre_2019,gdp_growth_stability_negative_std_pre_2007,gdp_growth_stability_negative_std_pre_2019,inflation_stability_negative_std_pre_2007,inflation_stability_negative_std_pre_2019,productivity_level_stability_negative_std_pre_2007,productivity_level_stability_negative_std_pre_2019,unemployment_stability_negative_std_pre_2007,unemployment_stability_negative_std_pre_2019,gdp_growth_stability_negative_mad_pre_2007,gdp_growth_stability_negative_mad_pre_2019,inflation_stability_negative_mad_pre_2007,inflation_stability_negative_mad_pre_2019,productivity_level_stability_negative_mad_pre_2007,productivity_level_stability_negative_mad_pre_2019,unemployment_stability_negative_mad_pre_2007,unemployment_stability_negative_mad_pre_2019,gdp_growth_stability_std_0_100_pre_2007,gdp_growth_stability_std_0_100_pre_2019,inflation_stability_std_0_100_pre_2007,inflation_stability_std_0_100_pre_2019,productivity_level_stability_std_0_100_pre_2007,productivity_level_stability_std_0_100_pre_2019,unemployment_stability_std_0_100_pre_2007,unemployment_stability_std_0_100_pre_2019,gdp_growth_stability_mad_0_100_pre_2007,gdp_growth_stability_mad_0_100_pre_2019,inflation_stability_mad_0_100_pre_2007,inflation_stability_mad_0_100_pre_2019,productivity_level_stability_mad_0_100_pre_2007,productivity_level_stability_mad_0_100_pre_2019,unemployment_stability_mad_0_100_pre_2007,unemployment_stability_mad_0_100_pre_2019,gdp_growth_mean_value_pre_2007,gdp_growth_mean_value_pre_2019,inflation_mean_value_pre_2007,inflation_mean_value_pre_2019,productivity_level_mean_value_pre_2007,productivity_level_mean_value_pre_2019,unemployment_mean_value_pre_2007,unemployment_mean_value_pre_2019,gdp_growth_median_value_pre_2007,gdp_growth_median_value_pre_2019,inflation_median_value_pre_2007,inflation_median_value_pre_2019,productivity_level_median_value_pre_2007,productivity_level_median_value_pre_2019,unemployment_median_value_pre_2007,unemployment_median_value_pre_2019,gdp_growth_change_first_to_last_pre_2007,gdp_growth_change_first_to_last_pre_2019,inflation_change_first_to_last_pre_2007,inflation_change_first_to_last_pre_2019,productivity_level_change_first_to_last_pre_2007,productivity_level_change_first_to_last_pre_2019,unemployment_change_first_to_last_pre_2007,unemployment_change_first_to_last_pre_2019,gdp_growth_years_available_pre_2007,gdp_growth_years_available_pre_2019,inflation_years_available_pre_2007,inflation_years_available_pre_2019,productivity_level_years_available_pre_2007,productivity_level_years_available_pre_2019,unemployment_years_available_pre_2007,unemployment_years_available_pre_2019,gdp_growth_coverage_rate_in_window_pre_2007,gdp_growth_coverage_rate_in_window_pre_2019,inflation_coverage_rate_in_window_pre_2007,inflation_coverage_rate_in_window_pre_2019,productivity_level_coverage_rate_in_window_pre_2007,productivity_level_coverage_rate_in_window_pre_2019,unemployment_coverage_rate_in_window_pre_2007,unemployment_coverage_rate_in_window_pre_2019
0,ARG,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.9555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.9555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.8142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.4398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,81.6889,NaN,NaN,NaN,43.9128,NaN,NaN,NaN,8.2018,NaN,NaN,NaN,43.9128,NaN,NaN,NaN,8.2305,NaN,NaN,NaN,19.2711,NaN,NaN,NaN,1.3390,NaN,NaN,NaN,2.0000,NaN,NaN,NaN,4.0000,NaN,NaN,NaN,0.2500,NaN,NaN,NaN,0.5000
1,AUS,Australia,0.7130,0.9696,0.8605,0.4288,1.8835,1.4542,0.8455,0.3523,0.5666,0.5800,0.7146,0.3299,1.5233,1.1216,0.7175,0.2769,-0.7130,-0.9696,-0.8605,-0.4288,-1.8835,-1.4542,-0.8455,-0.3523,-0.5666,-0.5800,-0.7146,-0.3299,-1.5233,-1.1216,-0.7175,-0.2769,100.0000,92.2408,97.0362,100.0000,69.5619,90.1520,86.6022,96.0467,100.0000,94.3444,97.1921,100.0000,70.7432,91.0831,85.2081,95.9344,3.3289,2.1754,3.1871,1.8696,57.4673,66.4830,5.6178,5.6002,3.3897,2.4473,2.8571,1.8371,58.1212,66.8692,5.6655,5.6325,1.5925,-2.7880,-2.1298,-0.1520,5.4976,4.5901,-1.9070,-0.0610,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
2,AUT,Austria,0.9926,0.9501,0.4510,0.5703,3.2168,1.0604,0.8517,0.5186,0.8170,0.7740,0.3604,0.4551,2.5730,0.8723,0.7359,0.4238,-0.9926,-0.9501,-0.4510,-0.5703,-3.2168,-1.0604,-0.8517,-0.5186,-0.8170,-0.7740,-0.3604,-0.4551,-2.5730,-0.8723,-0.7359,-0.4238,93.0853,92.4992,98.9699,96.0123,43.8679,93.4016,86.4649,92.2962,89.2635,90.6084,99.0970,95.0324,46.8312,93.4481,84.7149,92.0412,2.3828,1.3832,2.0164,1.6863,71.5824,79.6333,4.5679,5.2964,2.4428,1.5292,2.1149,1.8021,70.9200,79.7011,4.5685,5.4145,0.5857,1.1267,-0.1763,-0.9548,9.2207,2.2002,1.3560,-0.3780,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
3,BEL,Belgium,1.1188,0.7633,0.4532,0.8513,2.7797,1.2124,0.6867,1.1984,0.9189,0.5791,0.3805,0.6927,2.4418,0.9592,0.5826,0.9510,-1.1188,-0.7633,-0.4532,-0.8513,-2.7797,-1.2124,-0.6867,-1.1984,-0.9189,-0.5791,-0.3805,-0.6927,-2.4418,-0.9592,-0.5826,-0.9510,89.9631,94.9757,98.9596,88.0946,52.2911,92.1475,90.1086,76.9610,84.8953,94.3622,98.9891,85.6064,49.8205,92.6239,88.8285,78.0641,2.4604,1.3437,2.0926,1.5555,80.5300,86.3898,7.7304,7.3976,2.4370,1.4743,1.9602,1.7053,80.1683,86.9395,7.8440,7.6840,-0.0398,2.2271,-0.7215,-1.4028,7.1249,3.4817,0.4490,-2.1820,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
4,BGR,Bulgaria,NaN,NaN,2.3729,1.8007,1.8909,1.5660,4.7546,3.3571,NaN,NaN,1.7496,1.5457,1.4970,1.2327,3.8919,2.8354,NaN,NaN,-2.3729,-1.8007,-1.8909,-1.5660,-4.7546,-3.3571,NaN,NaN,-1.7496,-1.5457,-1.4970,-1.2327,-3.8919,-2.8354,NaN,NaN,89.8927,61.3381,69.4201,89.2300,0.2838,28.2634,NaN,NaN,91.6265,51.7615,71.3424,90.0294,0.0000,28.1034,NaN,NaN,6.5858,1.1879,21.2491,29.5380,13.3799,8.6069,NaN,NaN,6.7044,1.4758,21.1649,29.3942,12.8590,8.3565,NaN,NaN,-1.9137,0.1492,5.4576,4.4042,-10.0410,-8.1240,NaN,NaN,8.0000,8.0000,8.0000,8.0000,8.0000,8.0000,NaN,NaN,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000

In [9]:
# ------------------------------------------------------
# PREFERRED GDP GROWTH STABILITY OUTPUT
# ------------------------------------------------------
# This compact file is likely the most useful output from this notebook.

preferred_gdp_growth_stability = volatility_features_long[
    volatility_features_long["variable"] == "gdp_growth"
].copy()

preferred_gdp_growth_stability = preferred_gdp_growth_stability[
    [
        "Country",
        "country_name",
        "shock_id",
        "shock_label",
        "window_start",
        "window_end",
        "years_available",
        "expected_year_count",
        "coverage_rate_in_window",
        "sufficient_years_for_volatility",
        "mean_value",
        "volatility_std",
        "stability_negative_std",
        "stability_std_0_100",
        "volatility_mad",
        "stability_negative_mad",
        "stability_mad_0_100",
    ]
].sort_values(["shock_id", "Country"]).reset_index(drop=True)

preferred_gdp_growth_stability.to_csv(
    PROCESSED_DIR / "gdp_growth_stability_features_country_shock.csv",
    index=False,
)

preferred_gdp_growth_stability.to_csv(
    DIAGNOSTICS_DIR / "gdp_growth_stability_features_country_shock.csv",
    index=False,
)

display(preferred_gdp_growth_stability.head(80))

,Country,country_name,shock_id,shock_label,window_start,window_end,years_available,expected_year_count,coverage_rate_in_window,sufficient_years_for_volatility,mean_value,volatility_std,stability_negative_std,stability_std_0_100,volatility_mad,stability_negative_mad,stability_mad_0_100
0,AUS,Australia,2007,shock_2007,2000,2007,8,8,1.0000,True,3.3289,0.7130,-0.7130,100.0000,0.5666,-0.5666,100.0000
1,AUT,Austria,2007,shock_2007,2000,2007,8,8,1.0000,True,2.3828,0.9926,-0.9926,93.0853,0.8170,-0.8170,89.2635
2,BEL,Belgium,2007,shock_2007,2000,2007,8,8,1.0000,True,2.4604,1.1188,-1.1188,89.9631,0.9189,-0.9189,84.8953
3,BRA,Brazil,2007,shock_2007,2000,2007,8,8,1.0000,True,3.6208,1.8088,-1.8088,72.9009,1.4242,-1.4242,63.2269
4,CAN,Canada,2007,shock_2007,2000,2007,8,8,1.0000,True,2.8512,1.0805,-1.0805,90.9102,0.7589,-0.7589,91.7548
5,CHE,Switzerland,2007,shock_2007,2000,2007,8,8,1.0000,True,2.3723,1.6607,-1.6607,76.5645,1.3571,-1.3571,66.1033
6,CHL,Chile,2007,shock_2007,2000,2007,8,8,1.0000,True,4.9727,1.2730,-1.2730,86.1515,0.9597,-0.9597,83.1434
7,CHN,China,2007,shock_2007,2000,2007,8,8,1.0000,True,10.5572,2.0901,-2.0901,65.9457,1.6687,-1.6687,52.7410
8,COL,Colombia,2007,shock_2007,2000,2007,8,8,1.0000,True,4.2705,1.9366,-1.9366,69.7407,1.6031,-1.6031,55.5532
9,CRI,Costa Rica,2007,shock_2007,2000,2007,8,8,1.0000,True,4.8796,1.8339,-1.8339,72.2816,1.4456,-1.4456,62.3067
10,CZE,Czechia,2007,shock_2007,2000,2007,8,8,1.0000,True,4.3707,1.7738,-1.7738,73.7664,1.4351,-1.4351,62.7567
11,DEU,Germany,2007,shock_2007,2000,2007,8,8,1.0000,True,1.5697,1.5586,-1.5586,79.0895,1.2474,-1.2474,70.8089
12,DNK,Denmark,2007,shock_2007,2000,2007,8,8,1.0000,True,1.9389,1.4099,-1.4099,82.7658,1.2302,-1.2302,71.5450
13,ESP,Spain,2007,shock_2007,2000,2007,8,8,1.0000,True,3.6321,0.7787,-0.7787,98.3745,0.5667,-0.5667,99.9979
14,EST,Estonia,2007,shock_2007,2000,2007,8,8,1.0000,True,8.0194,1.5674,-1.5674,78.8718,1.3288,-1.3288,67.3174
15,FIN,Finland,2007,shock_2007,2000,2007,8,8,1.0000,True,3.5260,1.4951,-1.4951,80.6588,1.2468,-1.2468,70.8312
16,FRA,France,2007,shock_2007,2000,2007,8,8,1.0000,True,2.2597,1.0383,-1.0383,91.9546,0.8038,-0.8038,89.8310
17,GBR,United Kingdom,2007,shock_2007,2000,2007,8,8,1.0000,True,2.7600,0.8542,-0.8542,96.5074,0.6061,-0.6061,98.3088
18,GRC,Greece,2007,shock_2007,2000,2007,8,8,1.0000,True,4.4725,1.6211,-1.6211,77.5432,1.1473,-1.1473,75.0996
19,HUN,Hungary,2007,shock_2007,2000,2007,8,8,1.0000,True,3.8337,1.4619,-1.4619,81.4791,0.8753,-0.8753,86.7618
20,IDN,Indonesia,2007,shock_2007,2000,2007,8,8,1.0000,True,5.0516,0.8163,-0.8163,97.4439,0.5959,-0.5959,98.7433
21,IND,India,2007,shock_2007,2000,2007,8,8,1.0000,True,7.0753,2.5261,-2.5261,55.1636,2.1892,-2.1892,30.4199
22,IRL,Ireland,2007,shock_2007,2000,2007,8,8,1.0000,True,5.8061,1.8080,-1.8080,72.9222,1.1682,-1.1682,74.2031
23,ISL,Iceland,2007,shock_2007,2000,2007,8,8,1.0000,True,5.0793,2.7777,-2.7777,48.9430,2.1869,-2.1869,30.5208
24,ISR,Israel,2007,shock_2007,2000,2007,8,8,1.0000,True,3.8814,3.0968,-3.0968,41.0516,2.5229,-2.5229,16.1118
25,ITA,Italy,2007,shock_2007,2000,2007,8,8,1.0000,True,1.4654,1.2027,-1.2027,87.8902,0.8251,-0.8251,88.9162
26,JPN,Japan,2007,shock_2007,2000,2007,8,8,1.0000,True,1.4955,0.9434,-0.9434,94.3008,0.6842,-0.6842,94.9588
27,KOR,"Korea, Republic of",2007,shock_2007,2000,2007,8,8,1.0000,True,5.6719,1.9482,-1.9482,69.4536,1.4430,-1.4430,62.4193
28,LTU,Lithuania,2007,shock_2007,2000,2007,8,8,1.0000,True,7.4852,2.4341,-2.4341,57.4403,1.7264,-1.7264,50.2656
29,LUX,Luxembourg,2007,shock_2007,2000,2007,8,8,1.0000,True,4.5857,2.1538,-2.1538,64.3701,1.8241,-1.8241,46.0791
30,LVA,Latvia,2007,shock_2007,2000,2007,8,8,1.0000,True,8.9970,2.4519,-2.4519,57.0000,1.9659,-1.9659,39.9952
31,MEX,Mexico,2007,shock_2007,2000,2007,8,8,1.0000,True,2.2611,2.0922,-2.0922,65.8940,1.6541,-1.6541,53.3679
32,NLD,Netherlands,2007,shock_2007,2000,2007,8,8,1.0000,True,2.2950,1.5561,-1.5561,79.1504,1.1965,-1.1965,72.9902
33,NOR,Norway,2007,shock_2007,2000,2007,8,8,1.0000,True,2.7160,1.0840,-1.0840,90.8258,0.8577,-0.8577,87.5187
34,NZL,New Zealand,2007,shock_2007,2000,2007,8,8,1.0000,True,3.5496,0.9973,-0.9973,92.9675,0.7908,-0.7908,90.3855
35,POL,Poland,2007,shock_2007,2000,2007,8,8,1.0000,True,4.0786,1.9593,-1.9593,69.1810,1.5988,-1.5988,55.7382
36,PRT,Portugal,2007,shock_2007,2000,2007,8,8,1.0000,True,1.5378,1.3947,-1.3947,83.1409,0.9978,-0.9978,81.5112
37,RUS,Russian Federation,2007,shock_2007,2000,2007,8,8,1.0000,True,7.1771,1.7710,-1.7710,73.8378,1.3304,-1.3304,67.2496
38,SVK,Slovakia,2007,shock_2007,2000,2007,8,8,1.0000,True,5.5759,3.1930,-3.1930,38.6733,2.3754,-2.3754,22.4373
39,SVN,Slovenia,2007,shock_2007,2000,2007,8,8,1.0000,True,4.2815,1.5105,-1.5105,80.2795,1.1873,-1.1873,73.3827
40,SWE,Sweden,2007,shock_2007,2000,2007,8,8,1.0000,True,3.1280,1.2697,-1.2697,86.2339,1.0499,-1.0499,79.2781
41,TUR,Türkiye,2007,shock_2007,2000,2007,8,8,1.0000,True,5.6217,4.7569,-4.7569,0.0000,2.8986,-2.8986,0.0000
42,USA,United States,2007,shock_2007,2000,2007,8,8,1.0000,True,2.7061,1.0936,-1.0936,90.5870,0.8646,-0.8646,87.2217
43,ZAF,South Africa,2007,shock_2007,2000,2007,8,8,1.0000,True,4.2932,1.1083,-1.1083,90.2242,0.9058,-0.9058,85.4557
44,AUS,Australia,2019,shock_2019,2012,2019,8,8,1.0000,True,2.1754,0.9696,-0.9696,92.2408,0.5800,-0.5800,94.3444
45,AUT,Austria,2019,shock_2019,2012,2019,8,8,1.0000,True,1.3832,0.9501,-0.9501,92.4992,0.7740,-0.7740,90.6084
46,BEL,Belgium,2019,shock_2019,2012,2019,8,8,1.0000,True,1.3437,0.7633,-0.7633,94.9757,0.5791,-0.5791,94.3622
47,BRA,Brazil,2019,shock_2019,2012,2019,8,8,1.0000,True,0.3711,2.4413,-2.4413,72.7353,1.8910,-1.8910,69.0927
48,CAN,Canada,2019,shock_2019,2012,2019,8,8,1.0000,True,2.0411,0.8694,-0.8694,93.5688,0.7029,-0.7029,91.9769
49,CHE,Switzerland,2019,shock_2019,2012,2019,8,8,1.0000,True,1.8416,0.7630,-0.7630,94.9802,0.5644,-0.5644,94.6452
50,CHL,Chile,2019,shock_2019,2012,2019,8,8,1.0000,True,2.6442,1.7727,-1.7727,81.5966,1.3803,-1.3803,78.9287
51,CHN,China,2019,shock_2019,2012,2019,8,8,1.0000,True,7.0941,0.5764,-0.5764,97.4535,0.4433,-0.4433,96.9773
52,COL,Colombia,2019,shock_2019,2012,2019,8,8,1.0000,True,3.2124,1.2549,-1.2549,88.4592,0.9771,-0.9771,86.6961
53,CRI,Costa Rica,2019,shock_2019,2012,2019,8,8,1.0000,True,3.4959,0.9125,-0.9125,92.9978,0.7399,-0.7399,91.2656
54,CZE,Czechia,2019,shock_2019,2012,2019,8,8,1.0000,True,2.5678,2.1257,-2.1257,76.9173,1.5676,-1.5676,75.3211
55,DEU,Germany,2019,shock_2019,2012,2019,8,8,1.0000,True,1.4797,0.8774,-0.8774,93.4637,0.7362,-0.7362,91.3366
56,DNK,Denmark,2019,shock_2019,2012,2019,8,8,1.0000,True,1.8088,1.0001,-1.0001,91.8375,0.7147,-0.7147,91.7509
57,ESP,Spain,2019,shock_2019,2012,2019,8,8,1.0000,True,1.4321,2.3637,-2.3637,73.7626,1.7892,-1.7892,71.0541
58,EST,Estonia,2019,shock_2019,2012,2019,8,8,1.0000,True,3.3429,1.2235,-1.2235,88.8758,0.8403,-0.8403,89.3305
59,FIN,Finland,2019,shock_2019,2012,2019,8,8,1.0000,True,0.7380,1.6962,-1.6962,82.6102,1.3665,-1.3665,79.1948
60,FRA,France,2019,shock_2019,2012,2019,8,8,1.0000,True,1.2059,0.6596,-0.6596,96.3498,0.5348,-0.5348,95.2151
61,GBR,United Kingdom,2019,shock_2019,2012,2019,8,8,1.0000,True,2.0731,0.7039,-0.7039,95.7623,0.5595,-0.5595,94.7398
62,GRC,Greece,2019,shock_2019,2012,2019,8,8,1.0000,True,-0.5320,3.4766,-3.4766,59.0129,2.3848,-2.3848,59.5807
63,HUN,Hungary,2019,shock_2019,2012,2019,8,8,1.0000,True,3.2416,2.2104,-2.2104,75.7946,1.6484,-1.6484,73.7655
64,IDN,Indonesia,2019,shock_2019,2012,2019,8,8,1.0000,True,5.2208,0.3842,-0.3842,100.0000,0.2864,-0.2864,100.0000
65,IND,India,2019,shock_2019,2012,2019,8,8,1.0000,True,6.5782,1.4245,-1.4245,86.2122,1.0363,-1.0363,85.5556
66,IRL,Ireland,2019,shock_2019,2012,2019,8,8,1.0000,True,7.4739,7.9289,-7.9289,0.0000,5.4780,-5.4780,0.0000
67,ISL,Iceland,2019,shock_2019,2012,2019,8,8,1.0000,True,3.2439,1.7655,-1.7655,81.6923,1.3776,-1.3776,78.9823
68,ISR,Israel,2019,shock_2019,2012,2019,8,8,1.0000,True,3.6208,0.8587,-0.8587,93.7111,0.6593,-0.6593,92.8173
69,ITA,Italy,2019,shock_2019,2012,2019,8,8,1.0000,True,0.0046,1.6399,-1.6399,83.3572,1.2396,-1.2396,81.6394
70,JPN,Japan,2019,shock_2019,2012,2019,8,8,1.0000,True,1.1508,0.7651,-0.7651,94.9513,0.6166,-0.6166,93.6391
71,KOR,"Korea, Republic of",2019,shock_2019,2012,2019,8,8,1.0000,True,3.0086,0.3892,-0.3892,99.9341,0.3110,-0.3110,99.5263
72,LTU,Lithuania,2019,shock_2019,2012,2019,8,8,1.0000,True,3.9894,0.8454,-0.8454,93.8875,0.6727,-0.6727,92.5589
73,LUX,Luxembourg,2019,shock_2019,2012,2019,8,8,1.0000,True,2.5461,1.1722,-1.1722,89.5558,0.8345,-0.8345,89.4431
74,LVA,Latvia,2019,shock_2019,2012,2019,8,8,1.0000,True,3.2769,1.9875,-1.9875,78.7497,1.4224,-1.4224,78.1186
75,MEX,Mexico,2019,shock_2019,2012,2019,8,8,1.0000,True,1.8544,1.2013,-1.2013,89.1705,0.8328,-0.8328,89.4753
76,NLD,Netherlands,2019,shock_2019,2012,2019,8,8,1.0000,True,1.5612,1.3396,-1.3396,87.3371,1.0326,-1.0326,85.6262
77,NOR,Norway,2019,shock_2019,2012,2019,8,8,1.0000,True,1.8472,0.6606,-0.6606,96.3369,0.5611,-0.5611,94.7096
78,NZL,New Zealand,2019,shock_2019,2012,2019,8,8,1.0000,True,3.3501,0.8863,-0.8863,93.3451,0.7543,-0.7543,90.9873
79,POL,Poland,2019,shock_2019,2012,2019,8,8,1.0000,True,3.6948,1.8624,-1.8624,80.4072,1.4643,-1.4643,77.3117

In [10]:
# ------------------------------------------------------
# DIAGNOSTIC ASSOCIATION WITH RECOVERY OUTCOMES
# ------------------------------------------------------
# Recovery is not used to construct volatility/stability features.
# This is only a diagnostic check for later interpretation.

if recovery.empty:
    volatility_recovery_diagnostic = pd.DataFrame({
        "message": ["Recovery file not available, diagnostic association skipped."]
    })
else:
    diagnostic_rows = []

    for window in PRE_SHOCK_WINDOWS:
        shock_id = window["shock_id"]
        recovery_column = window["recovery_column"]

        if recovery_column not in recovery.columns:
            continue

        subset = volatility_features_long[
            volatility_features_long["shock_id"] == shock_id
        ].copy()

        subset = subset.merge(
            recovery[["Country", recovery_column]],
            on="Country",
            how="left",
        )

        subset = subset.rename(columns={recovery_column: "recovery_value"})

        for variable in sorted(subset["variable"].dropna().unique()):
            var_subset = subset[
                (subset["variable"] == variable)
                & subset["volatility_std"].notna()
                & subset["stability_std_0_100"].notna()
                & subset["recovery_value"].notna()
            ].copy()

            if len(var_subset) >= 5:
                corr_volatility = var_subset["volatility_std"].corr(var_subset["recovery_value"])
                corr_stability = var_subset["stability_std_0_100"].corr(var_subset["recovery_value"])
            else:
                corr_volatility = np.nan
                corr_stability = np.nan

            diagnostic_rows.append({
                "shock_id": shock_id,
                "recovery_column": recovery_column,
                "variable": variable,
                "countries_used": len(var_subset),
                "correlation_volatility_std_with_recovery": corr_volatility,
                "correlation_stability_std_0_100_with_recovery": corr_stability,
                "note": "Diagnostic only. Recovery is not used to construct features and this is not causal evidence.",
            })

    volatility_recovery_diagnostic = pd.DataFrame(diagnostic_rows)

volatility_recovery_diagnostic.to_csv(
    DIAGNOSTICS_DIR / "volatility_recovery_diagnostic_correlations.csv",
    index=False,
)

display(volatility_recovery_diagnostic)

,shock_id,recovery_column,variable,countries_used,correlation_volatility_std_with_recovery,correlation_stability_std_0_100_with_recovery,note
0,2007,Recovery_2007,gdp_growth,44,-0.1131,0.1131,Diagnostic only. Recovery is not used to const...
1,2007,Recovery_2007,inflation_cpi,44,-0.1592,0.1592,Diagnostic only. Recovery is not used to const...
2,2007,Recovery_2007,productivity_gdp_per_hour,37,0.1045,-0.1045,Diagnostic only. Recovery is not used to const...
3,2007,Recovery_2007,unemployment_rate,42,0.0943,-0.0943,Diagnostic only. Recovery is not used to const...
4,2019,Recovery_2019,gdp_growth,43,-0.1265,0.1265,Diagnostic only. Recovery is not used to const...
5,2019,Recovery_2019,inflation_cpi,43,-0.1728,0.1728,Diagnostic only. Recovery is not used to const...
6,2019,Recovery_2019,productivity_gdp_per_hour,38,-0.4282,0.4282,Diagnostic only. Recovery is not used to const...
7,2019,Recovery_2019,unemployment_rate,41,0.0464,-0.0464,Diagnostic only. Recovery is not used to const...

In [11]:
# ------------------------------------------------------
# FEATURE COVERAGE AND QUALITY FLAGS
# ------------------------------------------------------

feature_quality_summary = (
    volatility_features_long
    .groupby(["shock_id", "variable", "feature_slug", "concept"])
    .agg(
        countries_with_any_data=("Country", "nunique"),
        countries_with_sufficient_years=("sufficient_years_for_volatility", "sum"),
        median_years_available=("years_available", "median"),
        min_years_available=("years_available", "min"),
        max_years_available=("years_available", "max"),
        median_volatility_std=("volatility_std", "median"),
        min_volatility_std=("volatility_std", "min"),
        max_volatility_std=("volatility_std", "max"),
    )
    .reset_index()
)

feature_quality_summary["sufficient_years_country_rate"] = (
    feature_quality_summary["countries_with_sufficient_years"]
    / feature_quality_summary["countries_with_any_data"]
)

def classify_feature_quality(row):
    if row["countries_with_sufficient_years"] >= 35 and row["sufficient_years_country_rate"] >= 0.80:
        return "strong_candidate"

    if row["countries_with_sufficient_years"] >= 25 and row["sufficient_years_country_rate"] >= 0.60:
        return "review_candidate"

    return "weak_coverage_review"

feature_quality_summary["feature_quality_recommendation"] = feature_quality_summary.apply(
    classify_feature_quality,
    axis=1,
)

feature_quality_summary["note"] = "Diagnostic only; final variable selection happens during Pre-POSet EDA."

feature_quality_summary.to_csv(
    DIAGNOSTICS_DIR / "volatility_feature_quality_summary.csv",
    index=False,
)

display(feature_quality_summary)

,shock_id,variable,feature_slug,concept,countries_with_any_data,countries_with_sufficient_years,median_years_available,min_years_available,max_years_available,median_volatility_std,min_volatility_std,max_volatility_std,sufficient_years_country_rate,feature_quality_recommendation,note
0,2007,gdp_growth,gdp_growth,GDP growth volatility,44,44,8.0000,8,8,1.5573,0.7130,4.7569,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
1,2007,inflation_cpi,inflation,Inflation volatility,47,47,8.0000,8,8,1.0300,0.2330,21.4053,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
2,2007,productivity_gdp_per_hour,productivity_level,Productivity level volatility,40,40,8.0000,8,8,2.7752,0.3041,5.4931,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
3,2007,unemployment_rate,unemployment,Unemployment volatility,51,48,8.0000,1,8,0.8717,0.2387,4.7675,0.9412,strong_candidate,Diagnostic only; final variable selection happ...
4,2019,gdp_growth,gdp_growth,GDP growth volatility,44,44,8.0000,8,8,1.2124,0.3842,7.9289,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
5,2019,inflation_cpi,inflation,Inflation volatility,48,47,8.0000,2,8,1.0066,0.4288,3.9773,0.9792,strong_candidate,Diagnostic only; final variable selection happ...
6,2019,productivity_gdp_per_hour,productivity_level,Productivity level volatility,41,41,8.0000,8,8,1.6623,0.2607,12.3801,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
7,2019,unemployment_rate,unemployment,Unemployment volatility,52,51,8.0000,3,8,1.1169,0.1771,4.6100,0.9808,strong_candidate,Diagnostic only; final variable selection happ...

In [12]:
# ------------------------------------------------------
# OUTPUT DATA DICTIONARY
# ------------------------------------------------------

data_dictionary = pd.DataFrame([
    {
        "file": "volatility_features_country_shock_variable_long.csv",
        "column": "volatility_std",
        "description": "Sample standard deviation of the variable in the pre-shock window. Lower generally means more stable.",
    },
    {
        "file": "volatility_features_country_shock_variable_long.csv",
        "column": "volatility_mad",
        "description": "Mean absolute deviation around the mean in the pre-shock window. Lower generally means more stable.",
    },
    {
        "file": "volatility_features_country_shock_variable_long.csv",
        "column": "stability_negative_std",
        "description": "Direction-aligned stability measure equal to negative volatility_std. Higher = better / more stable.",
    },
    {
        "file": "volatility_features_country_shock_variable_long.csv",
        "column": "stability_std_0_100",
        "description": "Within-shock-variable 0-100 stability score derived from volatility_std. Higher = better. Useful for diagnostics/visuals.",
    },
    {
        "file": "gdp_growth_stability_features_country_shock.csv",
        "column": "stability_negative_std",
        "description": "Preferred raw direction-aligned GDP growth stability candidate. Higher = better because it is negative GDP growth volatility.",
    },
    {
        "file": "gdp_growth_stability_features_country_shock.csv",
        "column": "stability_std_0_100",
        "description": "Scaled GDP growth stability score within shock window. Higher = better.",
    },
])

data_dictionary.to_csv(
    PROCESSED_DIR / "volatility_features_data_dictionary.csv",
    index=False,
)

data_dictionary.to_csv(
    DIAGNOSTICS_DIR / "volatility_features_data_dictionary.csv",
    index=False,
)

methodological_notes = pd.DataFrame([
    {
        "topic": "Pre-shock only",
        "note": "Volatility features use only pre-shock years: 2000-2007 for the 2007 shock and 2012-2019 for the 2019 shock.",
    },
    {
        "topic": "No leakage",
        "note": "Recovery outcomes are not used to construct the volatility/stability features.",
    },
    {
        "topic": "Direction alignment",
        "note": "Volatility is lower-is-better, so stability features are created as higher-is-better versions.",
    },
    {
        "topic": "Preferred feature",
        "note": "GDP growth stability is the preferred first volatility-derived candidate. Other volatility variables should be treated as candidates and checked for redundancy.",
    },
    {
        "topic": "No final selection",
        "note": "This notebook does not decide the final POSet ordering variables.",
    },
])

methodological_notes.to_csv(
    DIAGNOSTICS_DIR / "volatility_methodological_notes.csv",
    index=False,
)

display(data_dictionary)
display(methodological_notes)

,file,column,description
0,volatility_features_country_shock_variable_lon...,volatility_std,Sample standard deviation of the variable in t...
1,volatility_features_country_shock_variable_lon...,volatility_mad,Mean absolute deviation around the mean in the...
2,volatility_features_country_shock_variable_lon...,stability_negative_std,Direction-aligned stability measure equal to n...
3,volatility_features_country_shock_variable_lon...,stability_std_0_100,Within-shock-variable 0-100 stability score de...
4,gdp_growth_stability_features_country_shock.csv,stability_negative_std,Preferred raw direction-aligned GDP growth sta...
5,gdp_growth_stability_features_country_shock.csv,stability_std_0_100,Scaled GDP growth stability score within shock...

                 topic                                               note
0       Pre-shock only  Volatility features use only pre-shock years: ...
1           No leakage  Recovery outcomes are not used to construct th...
2  Direction alignment  Volatility is lower-is-better, so stability fe...
3    Preferred feature  GDP growth stability is the preferred first vo...
4   No final selection  This notebook does not decide the final POSet ...

In [13]:
# ------------------------------------------------------
# CREATE VOLATILITY AUDIT WORKBOOK
# ------------------------------------------------------

VOLATILITY_AUDIT_XLSX = AUDIT_DIR / "04_Volatility_Features_Audit.xlsx"

audit_sources = [
    {
        "sheet_name": "01_window_coverage",
        "description": "Coverage summary by volatility variable and pre-shock window.",
        "path": DIAGNOSTICS_DIR / "volatility_window_coverage_summary.csv",
    },
    {
        "sheet_name": "02_long_features",
        "description": "Long volatility/stability feature table by country, shock, and variable.",
        "path": PROCESSED_DIR / "volatility_features_country_shock_variable_long.csv",
    },
    {
        "sheet_name": "03_country_shock_wide",
        "description": "Wide volatility/stability feature table by country-shock.",
        "path": PROCESSED_DIR / "volatility_features_country_shock_wide.csv",
    },
    {
        "sheet_name": "04_country_wide",
        "description": "One-row-per-country volatility/stability feature table across both shocks.",
        "path": PROCESSED_DIR / "volatility_features_country_wide.csv",
    },
    {
        "sheet_name": "05_gdp_stability",
        "description": "Preferred GDP growth stability feature output.",
        "path": PROCESSED_DIR / "gdp_growth_stability_features_country_shock.csv",
    },
    {
        "sheet_name": "06_quality_summary",
        "description": "Feature quality and coverage recommendation summary.",
        "path": DIAGNOSTICS_DIR / "volatility_feature_quality_summary.csv",
    },
    {
        "sheet_name": "07_recovery_diag",
        "description": "Diagnostic correlation with recovery outcomes; not causal and not used in feature construction.",
        "path": DIAGNOSTICS_DIR / "volatility_recovery_diagnostic_correlations.csv",
    },
    {
        "sheet_name": "08_dictionary",
        "description": "Volatility output data dictionary.",
        "path": PROCESSED_DIR / "volatility_features_data_dictionary.csv",
    },
    {
        "sheet_name": "09_method_notes",
        "description": "Methodological notes.",
        "path": DIAGNOSTICS_DIR / "volatility_methodological_notes.csv",
    },
]


def safe_sheet_name(name, used):
    cleaned = re.sub(r"[/\\*\[\]:?]", "_", str(name))[:31]
    base = cleaned
    i = 1

    while cleaned in used:
        suffix = f"_{i}"
        cleaned = base[:31 - len(suffix)] + suffix
        i += 1

    used.add(cleaned)
    return cleaned


def estimate_width(series, col_name, min_width=10, max_width=60):
    values = [str(col_name)] + series.dropna().astype(str).head(200).tolist()

    if not values:
        return min_width

    return max(min_width, min(max(len(v) for v in values) + 2, max_width))


used_sheets = set()

with pd.ExcelWriter(VOLATILITY_AUDIT_XLSX, engine="xlsxwriter") as writer:
    workbook = writer.book

    title_fmt = workbook.add_format({
        "bold": True,
        "font_size": 15,
        "font_color": "white",
        "bg_color": "#1F4E78",
        "align": "left",
        "valign": "vcenter",
    })

    desc_fmt = workbook.add_format({
        "text_wrap": True,
        "font_size": 10,
        "font_color": "#333333",
        "valign": "top",
    })

    header_fmt = workbook.add_format({
        "bold": True,
        "font_color": "white",
        "bg_color": "#5B9BD5",
        "border": 1,
        "align": "center",
        "valign": "vcenter",
        "text_wrap": True,
    })

    index_rows = []

    for item in audit_sources:
        path = Path(item["path"])

        if path.exists():
            try:
                df_temp = pd.read_csv(path)
                rows = len(df_temp)
                cols = len(df_temp.columns)
            except Exception:
                rows = np.nan
                cols = np.nan
        else:
            rows = 0
            cols = 0

        index_rows.append({
            "Sheet": item["sheet_name"],
            "Rows": rows,
            "Columns": cols,
            "Description": item["description"],
            "Path": str(path),
        })

    index_df = pd.DataFrame(index_rows)
    index_df.to_excel(writer, sheet_name="00_INDEX", index=False, startrow=5)

    ws = writer.sheets["00_INDEX"]
    ws.merge_range(0, 0, 0, max(4, len(index_df.columns) - 1), "04 Volatility Features Audit", title_fmt)
    ws.merge_range(1, 0, 3, max(4, len(index_df.columns) - 1), "Audit workbook for pre-shock volatility and stability feature construction.", desc_fmt)

    for col_idx, col_name in enumerate(index_df.columns):
        ws.write(5, col_idx, col_name, header_fmt)
        ws.set_column(col_idx, col_idx, estimate_width(index_df[col_name], col_name))

    ws.autofilter(5, 0, 5 + len(index_df), len(index_df.columns) - 1)
    ws.freeze_panes(6, 0)

    for item in audit_sources:
        path = Path(item["path"])

        if path.exists():
            try:
                df_sheet = pd.read_csv(path)
            except Exception as e:
                df_sheet = pd.DataFrame({"message": [f"Could not read file: {e}"]})
        else:
            df_sheet = pd.DataFrame({"message": ["File not found."]})

        if df_sheet.empty:
            df_sheet = pd.DataFrame({"message": ["No rows in this table."]})

        sheet_name = safe_sheet_name(item["sheet_name"], used_sheets)

        df_sheet.to_excel(writer, sheet_name=sheet_name, index=False, startrow=4)

        ws = writer.sheets[sheet_name]
        max_col = max(4, len(df_sheet.columns) - 1)

        ws.merge_range(0, 0, 0, max_col, item["sheet_name"], title_fmt)
        ws.merge_range(1, 0, 3, max_col, item["description"], desc_fmt)

        for col_idx, col_name in enumerate(df_sheet.columns):
            ws.write(4, col_idx, col_name, header_fmt)
            ws.set_column(col_idx, col_idx, estimate_width(df_sheet[col_name], col_name))

        ws.autofilter(4, 0, 4 + len(df_sheet), len(df_sheet.columns) - 1)
        ws.freeze_panes(5, 0)

print("Volatility audit workbook created:")
print(VOLATILITY_AUDIT_XLSX.resolve())

Volatility audit workbook created:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Audit\04_Volatility_Features_Audit.xlsx

In [14]:
# ------------------------------------------------------
# FINAL COMPLETION CHECK
# ------------------------------------------------------

print("04 VOLATILITY FEATURES COMPLETE")
print("=" * 80)

print("\nInput file:")
print(INPUT_FILE.resolve())

print("\nProcessed folder:")
print(PROCESSED_DIR.resolve())

print("\nDiagnostics folder:")
print(DIAGNOSTICS_DIR.resolve())

print("\nAudit workbook:")
print(VOLATILITY_AUDIT_XLSX.resolve())

print("\nMain processed outputs:")
main_outputs = [
    "volatility_features_country_shock_variable_long.csv",
    "volatility_features_country_shock_wide.csv",
    "volatility_features_country_wide.csv",
    "gdp_growth_stability_features_country_shock.csv",
    "volatility_features_data_dictionary.csv",
]

for file_name in main_outputs:
    path = PROCESSED_DIR / file_name
    status = "FOUND" if path.exists() else "MISSING"
    print(f"- {status}: {file_name}")

print("\nFeature quality summary:")
display(feature_quality_summary)

print("\nImportant notes:")
print("1. Only pre-shock years were used.")
print("2. Recovery outcomes were not used to construct features.")
print("3. Volatility is lower-is-better; stability versions are higher-is-better.")
print("4. GDP growth stability is the preferred first candidate from this notebook.")
print("5. Final variable selection still happens later in Pre-POSet EDA.")

print("\nNext notebook:")
print("05_Master_Dataset_Build.ipynb")

04 VOLATILITY FEATURES COMPLETE
================================================================================

Input file:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\00_Comparable_Raw_Files\Combined_Long\all_comparable_sources_long.csv

Processed folder:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Processed\Volatility_Features

Diagnostics folder:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Diagnostics\04_Volatility_Features

Audit workbook:
D:\Milano Bicocca\Course Materials\1st Year\02 - Data Science Lab - 2526-1-FDS02Q003\03 Projects\Index\Notebooks\Data\Audit\04_Volatility_Features_Audit.xlsx

Main processed outputs:
- FOUND: volatility_features_country_shock_variable_long.csv
- FOUND: volatility_features_country_shock_wide.csv
- FOUND: volatility_features_country_wide.csv
- FOUND: gdp_growth_stability_features_country_shock.csv
- FOUND: volatility_features_data_dictionary.csv

Feature quality summary:

,shock_id,variable,feature_slug,concept,countries_with_any_data,countries_with_sufficient_years,median_years_available,min_years_available,max_years_available,median_volatility_std,min_volatility_std,max_volatility_std,sufficient_years_country_rate,feature_quality_recommendation,note
0,2007,gdp_growth,gdp_growth,GDP growth volatility,44,44,8.0000,8,8,1.5573,0.7130,4.7569,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
1,2007,inflation_cpi,inflation,Inflation volatility,47,47,8.0000,8,8,1.0300,0.2330,21.4053,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
2,2007,productivity_gdp_per_hour,productivity_level,Productivity level volatility,40,40,8.0000,8,8,2.7752,0.3041,5.4931,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
3,2007,unemployment_rate,unemployment,Unemployment volatility,51,48,8.0000,1,8,0.8717,0.2387,4.7675,0.9412,strong_candidate,Diagnostic only; final variable selection happ...
4,2019,gdp_growth,gdp_growth,GDP growth volatility,44,44,8.0000,8,8,1.2124,0.3842,7.9289,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
5,2019,inflation_cpi,inflation,Inflation volatility,48,47,8.0000,2,8,1.0066,0.4288,3.9773,0.9792,strong_candidate,Diagnostic only; final variable selection happ...
6,2019,productivity_gdp_per_hour,productivity_level,Productivity level volatility,41,41,8.0000,8,8,1.6623,0.2607,12.3801,1.0000,strong_candidate,Diagnostic only; final variable selection happ...
7,2019,unemployment_rate,unemployment,Unemployment volatility,52,51,8.0000,3,8,1.1169,0.1771,4.6100,0.9808,strong_candidate,Diagnostic only; final variable selection happ...

Important notes:
1. Only pre-shock years were used.
2. Recovery outcomes were not used to construct features.
3. Volatility is lower-is-better; stability versions are higher-is-better.
4. GDP growth stability is the preferred first candidate from this notebook.
5. Final variable selection still happens later in Pre-POSet EDA.

Next notebook:
05_Master_Dataset_Build.ipynb